// Frontend Web Application for RA Products
// Developed by R2 Labs

import { immerable } from 'immer';
import ROSLIB from 'roslib';

// import { DatabaseMessageArray } from '@/lib/models/database_models';

import {
    AITrainingServiceType,
    availableTables,
    AxisServiceType,
    CameraServiceType,
    HardwareConfiguration,
    IOPointConfiguration,
    IOPointType,
} from '@/lib/models/api_models';
import {
    IRosTypeR2CInterfacesAnalogInData,
    IRosTypeR2CInterfacesAnalogInHardwareConfig,
    IRosTypeR2CInterfacesAnalogOutData,
    IRosTypeR2CInterfacesAnalogOutHardwareConfig,
    IRosTypeR2CInterfacesAxisState,
    IRosTypeR2CInterfacesAxisStateAxisIndex,
    IRosTypeR2CInterfacesClearErrorsRequest,
    IRosTypeR2CInterfacesConfigureAnalogInRequest,
    IRosTypeR2CInterfacesConfigureAnalogOutRequest,
    IRosTypeR2CInterfacesConfigureCameraStreamRequest,
    IRosTypeR2CInterfacesConfigureDigitalInRequest,
    IRosTypeR2CInterfacesConfigureDigitalOutRequest,
    IRosTypeR2CInterfacesCreateOpcuaSubscriptionRequest,
    IRosTypeR2CInterfacesCreateOpcuaSubscriptionResponse,
    IRosTypeR2CInterfacesDigitalInData,
    IRosTypeR2CInterfacesDigitalInHardwareConfig,
    IRosTypeR2CInterfacesDigitalOutData,
    IRosTypeR2CInterfacesDigitalOutHardwareConfig,
    IRosTypeR2CInterfacesEncoderEstimates,
    // IRosTypeR2CInterfacesGetApplicationStringRequest,
    IRosTypeR2CInterfacesGetApplicationStringResponse,
    IRosTypeR2CInterfacesGpioConfigurationState,
    IRosTypeR2CInterfacesHeartbeat,
    IRosTypeR2CInterfacesJogAxisRequest,
    IRosTypeR2CInterfacesJogAxisRequestConst,
    IRosTypeR2CInterfacesOpcuaData,
    IRosTypeR2CInterfacesSetAnalogOutputStatesRequest,
    IRosTypeR2CInterfacesSetApplicationStringRequest,
    IRosTypeR2CInterfacesSetAxisStateRequest,
    IRosTypeR2CInterfacesSetDigitalOutputStatesRequest,
    IRosTypeR2CInterfacesSetOpcuaVariableRequest,
    IRosTypeR2CInterfacesSetOpcuaVariableResponse,
    IRosTypeR2CInterfacesTorques,
} from '@/lib/models/ros_types';

import {
    ioConfigurationType,
    opcConfigurationType,
    opcDataPointType,
    uiConfigurationType,
} from '@/lib/models/autogenerated/configuration_models';
import timeoutServiceCall from '@/lib/utils/timeoutServiceCall';
import { logMessage } from '@/lib/utils/utilities';

type IOServicesMap = Record<IOPointType, ROSLIB.Service | null>;
type IOConfigurationRequest =
    | IRosTypeR2CInterfacesConfigureAnalogInRequest
    | IRosTypeR2CInterfacesConfigureDigitalInRequest
    | IRosTypeR2CInterfacesConfigureAnalogOutRequest
    | IRosTypeR2CInterfacesConfigureDigitalOutRequest;

type IOCommandRequestData =
    | IRosTypeR2CInterfacesSetDigitalOutputStatesRequest
    | IRosTypeR2CInterfacesSetAnalogOutputStatesRequest;

type CameraServiceMap = Record<CameraServiceType, ROSLIB.Service | null>;

type AITrainingServiceMap = Record<
    AITrainingServiceType,
    ROSLIB.Service | null
>;

export class ApplicationServices {
    protected _services: Record<string, ROSLIB.Service> = {};

    public set_service(name: string, service: ROSLIB.Service) {
        this._services[name] = service;
    }

    public get_service(name: string): ROSLIB.Service | null {
        if (Object.keys(this._services).includes(name)) {
            return this._services[name];
        }
        return null;
    }

    private _call_service(
        service_name: string,
        request_data: any,
        onSuccess: () => void,
        onFailure: () => void,
        onError: (error: any) => void,
        onComplete: () => void
    ) {
        let success = false;

        const service = this.get_service(service_name);
        if (!service) {
            console.error(`Service ${service_name} is not available`);
            onFailure();
            return success;
        }

        timeoutServiceCall(service, request_data, 3000)
            .then((result) => {
                if ((result as any).success) {
                    onSuccess();
                    success = true;
                } else {
                    onFailure();
                }
            })
            .catch((error) => {
                onError(error);
            })
            .finally(() => {
                onComplete();
            });
        return success;
    }

    public set_endpoint(
        path: string,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (e: any) => void,
        onComplete?: () => void
    ): boolean {
        const request_data: IRosTypeR2CInterfacesSetApplicationStringRequest = {
            payload: path,
        };

        return this._call_service(
            'set_endpoint',
            request_data,
            () => {
                console.log(`Successfully set endpoint path to ${path}`);
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(`Failed to set endpoint path to ${path}`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error setting endpoint path to ${path}: ${error}`);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    public set_state_variable(
        state_name: string,
        state_value: string | number,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (e: any) => void,
        onComplete?: () => void
    ): boolean {
        const request_data: IRosTypeR2CInterfacesSetApplicationStringRequest = {
            payload: JSON.stringify({ [state_name]: state_value }),
        };

        return this._call_service(
            'set_state',
            request_data,
            () => {
                console.log(
                    `Successfully set state ${state_name} to ${state_value}`
                );
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(
                    `Failed to set state ${state_name} to ${state_value}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error setting state ${state_name}: ${error}`);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    public send_robot_command(
        command: string,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (e: any) => void,
        onComplete?: () => void
    ): boolean {
        const request_data: IRosTypeR2CInterfacesSetApplicationStringRequest = {
            payload: command,
        };

        return this._call_service(
            'send_robot_command',
            request_data,
            () => {
                console.log(`Successfully sent robot command ${command}`);
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(`Failed to send command ${command}`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error sending command ${command}: ${error}`);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }
}

export class ApplicationState {
    _states: Record<string, string | number> = {};

    public get_state(state_name: string): string | number | null {
        if (Object.keys(this._states).includes(state_name)) {
            return this._states[state_name];
        }
        return null;
    }

    public set_state(state_name: string, state_value: string | number) {
        this._states[state_name] = state_value;
    }

    public set_states(state_values: Record<string, string | number>) {
        this._states = { ...this._states, ...state_values };
    }
}

class AxisService {
    [immerable] = true;

    protected _services: Record<AxisServiceType, ROSLIB.Service | null> = {
        [AxisServiceType.SET_STATE]: undefined,
        [AxisServiceType.CLEAR_ERRORS]: undefined,
        [AxisServiceType.JOG]: undefined,
    };

    public constructor() {}

    public get_service(service_type: AxisServiceType) {
        return this._services[service_type];
    }

    public set_service(service_type: AxisServiceType, service: ROSLIB.Service) {
        this._services[service_type] = service;
    }
}

export class AxisCommandServices extends AxisService {
    [immerable] = true;

    private _call_axis_service(
        request_data: any,
        service_type: AxisServiceType,
        onSuccess: () => void,
        onFailure: () => void,
        onError: (error: any) => void,
        onComplete?: () => void
    ) {
        let success = false;

        const service = this.get_service(service_type);
        if (!service) {
            console.error(
                `Service for ${AxisServiceType[service_type]} is not available`
            );
            onFailure();
            return success;
        }

        timeoutServiceCall(service, request_data, 3000)
            .then((result) => {
                if ((result as any).success) {
                    if (onSuccess) onSuccess();
                    success = true;
                } else {
                    onFailure();
                }
            })
            .catch((error) => {
                console.error(`Service call unsuccessful.`);
                onError(error);
            })
            .finally(() => {
                onComplete();
            });
        return success;
    }

    public clear_axis_errors(
        axis_index: number,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        let success = false;

        const service = this.get_service(AxisServiceType.CLEAR_ERRORS);
        if (!service) {
            console.error(
                `Service for ${AxisServiceType[AxisServiceType.CLEAR_ERRORS]} is not available`
            );
            onFailure();
            return success;
        }

        const request_data: IRosTypeR2CInterfacesClearErrorsRequest = {
            axis_index: axis_index,
            // state: target_state, // TODO CHECK THIS STATE FOR STATE CHANGE
            timeout_ms: 3000,
        };

        this._call_axis_service(
            request_data,
            AxisServiceType.CLEAR_ERRORS,
            () => {
                console.log(`Successfully cleared axis ${axis_index} errors.`);
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(`Failed to clear axis ${axis_index} errors.`);
                if (onFailure) onFailure();
            },
            (e) => {
                console.log(`Error clearing axis ${axis_index} errors: ${e}`);
                if (onError) onError(e);
            },
            () => {
                if (onComplete) onComplete();
            }
        );

        return success;
    }

    public jog_axis(
        axis_index: number,
        jog_type: IRosTypeR2CInterfacesJogAxisRequestConst,
        jog_amount: number,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data: IRosTypeR2CInterfacesJogAxisRequest = {
            axis_index: axis_index,
            mode: jog_type,
            amount: jog_amount,
        };

        return this._call_axis_service(
            request_data,
            AxisServiceType.JOG,
            () => {
                console.log(
                    `Successfully jogged axis ${axis_index} in ${IRosTypeR2CInterfacesJogAxisRequestConst[jog_type]} mode by ${jog_amount}`
                );
                if (onSuccess) onSuccess;
            },
            () => {
                console.log(
                    `Failed to jog axis ${axis_index} in ${IRosTypeR2CInterfacesJogAxisRequestConst[jog_type]} mode by ${jog_amount}`
                );
                if (onFailure) onFailure;
            },
            (e) => {
                console.log(
                    `Error jogging axis ${axis_index} in ${IRosTypeR2CInterfacesJogAxisRequestConst[jog_type]} mode by ${jog_amount}: ${e}`
                );
                if (onError) onError(e);
            },
            () => {
                if (onComplete) onComplete;
            }
        );
    }

    public set_axis_state(
        axis_index: number,
        target_state: IRosTypeR2CInterfacesAxisStateAxisIndex,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ): boolean {
        const request_data: IRosTypeR2CInterfacesSetAxisStateRequest = {
            axis_index: axis_index,
            state: {
                axis_index: axis_index,
                state: target_state, // TODO CHECK THIS STATE FOR STATE CHANGE
                stamp: {
                    sec: 0,
                    nanosec: 0,
                },
            },
            timeout_ms: 3000,
        };

        return this._call_axis_service(
            request_data,
            AxisServiceType.SET_STATE,
            () => {
                console.log(
                    `Successfully set axis ${axis_index} to state ${IRosTypeR2CInterfacesAxisStateAxisIndex[target_state]}`
                );
                if (onSuccess) onSuccess;
            },
            () => {
                console.log(
                    `Failed to set axis ${axis_index} to state ${IRosTypeR2CInterfacesAxisStateAxisIndex[target_state]}`
                );
                if (onFailure) onFailure;
            },
            (e) => {
                console.log(
                    `Error setting axis ${axis_index} to state ${IRosTypeR2CInterfacesAxisStateAxisIndex[target_state]}:`
                );
                if (onError) onError(e);
            },
            () => {
                if (onComplete) onComplete;
            }
        );
    }

    public set_axis_enable(axis_index: number, enable: boolean) {
        const target_state = enable
            ? IRosTypeR2CInterfacesAxisStateAxisIndex.STATE_CLOSED_LOOP_CONTROL
            : IRosTypeR2CInterfacesAxisStateAxisIndex.STATE_IDLE;
        this.set_axis_state(axis_index, target_state);
    }
}

export class AxisConfigurationServices {
    private axis_states: Record<number, IRosTypeR2CInterfacesAxisState> = {};

    constructor() {
        this.initializeAxes();
    }

    private initializeAxes(): void {
        this.axis_states = Object.fromEntries(
            Array.from({ length: 4 }, (_, index) => [
                index,
                {
                    stamp: { sec: 0, nanosec: 0 },
                    axis_index: index,
                    state: IRosTypeR2CInterfacesAxisStateAxisIndex.STATE_IDLE,
                },
            ])
        );
    }

    public getAxisState(index: number): IRosTypeR2CInterfacesAxisState | null {
        return this.axis_states[index] || null;
    }

    public setAxisState(
        index: number,
        state: IRosTypeR2CInterfacesAxisState
    ): void {
        this.axis_states[index] = state;
    }

    public get allAxisStates(): Record<number, IRosTypeR2CInterfacesAxisState> {
        return this.axis_states;
    }
}

interface ServiceCall<T> {
    (
        onSuccess?: () => void, // = () => {},
        onFailure?: () => void, // = () => {},
        onError?: (error: any) => void, // = (error) => {},
        onComplete?: () => void
    ): Promise<T>; // = () => {}): boolean
}

interface SubscribeServiceCall {
    (
        node_id: string,
        onSuccess?: () => void, // = () => {},
        onFailure?: () => void, // = () => {},
        onError?: (error: any) => void, // = (error) => {},
        onComplete?: () => void
    ): Promise<boolean>;
}

interface WriteServiceCall {
    (
        data_point: opcDataPointType,
        value: string | number | boolean,
        onSuccess?: () => void, // = () => {},
        onFailure?: () => void, // = () => {},
        onError?: (error: any) => void, // = (error) => {},
        onComplete?: () => void
    ): Promise<boolean>;
}

type ServiceResult<T> = T | null;

export class OPCUAServices {
    [immerable] = true;

    protected _ros: ROSLIB.Ros;
    protected _services: Record<string, ROSLIB.Service> = {
        connect: null,
        browse: null,
        subscribe: null,
        unsubscribe: null,
        write: null,
    };

    private async _call_service<T extends { success: boolean }>(
        service: ROSLIB.Service,
        request: ROSLIB.ServiceRequest,
        onSuccess?: () => void,
        onError?: (message: string) => void,
        onFailure?: () => void,
        onComplete?: () => void,
        onUndefined?: (error: string) => void
    ): Promise<ServiceResult<T>> {
        let service_result: ServiceResult<T> = null;

        if (!service) {
            onUndefined(`OPC-UA service not defined.`);
            return service_result;
        }

        try {
            const res = await timeoutServiceCall<T>(service, request, 3000);

            if (res.success) {
                if (onSuccess) onSuccess();
                return res; // Return the successful result
            } else {
                const errorMsg = `OPC-UA service call unsuccessful`;
                logMessage(errorMsg, 'error', 'ROS');
                if (onFailure) onFailure();
                return null; // Return null on failure
            }
        } catch (error) {
            const errorMsg = `OPC-UA service call failed: ${error}`;
            logMessage(errorMsg, 'error', 'ROS');
            if (onError) onError(error);
            return null; // Return null on a promise rejection
        } finally {
            if (onComplete) onComplete();
        }
    }

    public constructor(ros: ROSLIB.Ros) {
        this._ros = ros;

        this.initialize();
    }

    public initialize() {
        const connect_service = new ROSLIB.Service({
            ros: this._ros,
            name: '/opc/connect',
            serviceType: 'r2c_interfaces/SetApplicationString',
        });

        this._services.connect = connect_service;

        const browse_service = new ROSLIB.Service({
            ros: this._ros,
            name: '/opc/browse',
            serviceType: 'r2c_interfaces/GetApplicationString',
        });

        this._services.browse = browse_service;

        const subscribe_service = new ROSLIB.Service({
            ros: this._ros,
            name: '/opc/create_subscription',
            serviceType: 'r2c_interfaces/CreateOPCUASubscription',
        });

        this._services.subscribe = subscribe_service;

        const unsubscribe_service = new ROSLIB.Service({
            ros: this._ros,
            name: '/opc/delete_subscription',
            serviceType: 'r2c_interfaces/CreateOPCUASubscription',
        });

        this._services.unsubscribe = unsubscribe_service;

        const write_service = new ROSLIB.Service({
            ros: this._ros,
            name: '/opc/set_variable',
            serviceType: 'r2c_interfaces/SetOPCUAVariable',
        });

        this._services.write = write_service;
    }

    public connect_to_server(
        address: string,
        onSuccess: () => void = () => {},
        onFailure: () => void = () => {},
        onError: (error: any) => void = (error) => {},
        onComplete: () => void = () => {}
    ) {
        const request_data: IRosTypeR2CInterfacesSetApplicationStringRequest = {
            payload: address,
        };

        return this._call_service<IRosTypeR2CInterfacesGetApplicationStringResponse>(
            this._services.connect,
            request_data,
            onSuccess,
            onError,
            onFailure,
            onComplete,
            (error) => {
                throw new Error('OPC-UA connect service undefined.');
            }
        );
    }

    public browse_nodes: ServiceCall<string> = async (
        onSuccess = () => {},
        onFailure = () => {},
        onError = (e) => {},
        onComplete = () => {}
    ): Promise<string> => {
        const request_data = {};

        const res =
            await this._call_service<IRosTypeR2CInterfacesGetApplicationStringResponse>(
                this._services.browse,
                request_data,
                onSuccess,
                onError,
                onFailure,
                onComplete,
                (error) => {
                    throw new Error('OPC-UA browse service undefined.');
                }
            );

        return res.payload;
    };

    public subscribe: SubscribeServiceCall = async (
        node_id,
        onSuccess = () => {},
        onFailure = () => {},
        onError = (e) => {},
        onComplete = () => {}
    ): Promise<boolean> => {
        const request_data: IRosTypeR2CInterfacesCreateOpcuaSubscriptionRequest =
            {
                node_id: node_id,
            };

        const res =
            await this._call_service<IRosTypeR2CInterfacesCreateOpcuaSubscriptionResponse>(
                this._services.subscribe,
                request_data,
                onSuccess,
                onError,
                onFailure,
                onComplete,
                (error) => {
                    throw new Error('OPC-UA unsubscribe service undefined.');
                }
            );

        return res.success;
    };

    public unsubscribe: SubscribeServiceCall = async (
        node_id,
        onSuccess = () => {},
        onFailure = () => {},
        onError = (e) => {},
        onComplete = () => {}
    ): Promise<boolean> => {
        const request_data: IRosTypeR2CInterfacesCreateOpcuaSubscriptionRequest =
            {
                node_id: node_id,
            };

        const res =
            await this._call_service<IRosTypeR2CInterfacesCreateOpcuaSubscriptionResponse>(
                this._services.unsubscribe,
                request_data,
                onSuccess,
                onError,
                onFailure,
                onComplete,
                (error) => {
                    throw new Error('OPC-UA unsubscribe service undefined.');
                }
            );

        return res.success;
    };

    public write: WriteServiceCall = async (
        data_point: opcDataPointType,
        value,
        onSuccess = () => {},
        onFailure = () => {},
        onError = (e) => {},
        onComplete = () => {}
    ): Promise<boolean> => {
        const request_data: IRosTypeR2CInterfacesSetOpcuaVariableRequest = {
            data: {
                stamp: {
                    sec: 0,
                    nanosec: 0,
                },
                node_id: data_point.node_id,
                data_type: { type: data_point.type },
                numeric_value: typeof value === 'number' ? value : 0,
                string_value: typeof value === 'string' ? value : '',
                bool_value: typeof value === 'boolean' ? value : false,
            },
        };

        const res =
            await this._call_service<IRosTypeR2CInterfacesSetOpcuaVariableResponse>(
                this._services.write,
                request_data,
                onSuccess,
                onError,
                onFailure,
                onComplete,
                (error) => {
                    throw new Error('OPC-UA unsubscribe service undefined.');
                }
            );

        return res.success;
    };
}

class IOServices {
    [immerable] = true;

    protected _services: IOServicesMap = {
        [IOPointType.DIGITAL_INPUT]: null,
        [IOPointType.DIGITAL_OUTPUT]: null,
        [IOPointType.ANALOG_INPUT]: null,
        [IOPointType.ANALOG_OUTPUT]: null,
        [IOPointType.NULL]: null,
    };

    public constructor() {}

    public get_service(io_point_type: IOPointType) {
        return this._services[io_point_type];
    }

    public set_service(io_point_type: IOPointType, service: ROSLIB.Service) {
        this._services[io_point_type] = service;
    }
}

export class IOCommandServices extends IOServices {
    [immerable] = true;

    private _set_io_point(
        request_data: IOCommandRequestData,
        point_type: IOPointType,
        onSuccess: () => void,
        onFailure: () => void,
        onError: (error: any) => void,
        onComplete: () => void
    ) {
        let success = false;

        const service = this.get_service(point_type);
        if (!service) {
            console.error(
                `Service for IO point type ${IOPointType[point_type]} is not available`
            );
            onFailure();
            return success;
        }

        timeoutServiceCall(service, request_data, 3000)
            .then((result) => {
                if ((result as any).success) {
                    onSuccess();
                    success = true;
                } else {
                    onFailure();
                }
            })
            .catch((error) => {
                onError(error);
            })
            .finally(() => {
                onComplete();
            });
        return success;
    }

    public set_digital_output_point(
        point_index: number,
        state: boolean,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (e: any) => void,
        onComplete?: () => void
    ): boolean {
        let write_channels = new Array<boolean>(8).fill(false);
        write_channels[point_index] = true;

        let request_data: IRosTypeR2CInterfacesSetDigitalOutputStatesRequest;

        let values = new Array<boolean>(8).fill(false);
        values[point_index] = state;
        request_data = {
            states: {
                stamp: { sec: 0, nanosec: 0 },
                write_channels: write_channels,
                values: values,
            },
        };

        return this._set_io_point(
            request_data,
            IOPointType.DIGITAL_OUTPUT,
            () => {
                console.log(
                    `Successfully set digital output ${point_index} to ${state}`
                );
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(
                    `Failed to set digital output ${point_index} to ${state}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error setting digital output ${point_index} to ${state}: ${error}`
                );
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    public set_analog_output_point(
        point_index: number,
        state: number,
        onSuccess?: () => void,
        onFailure?: () => void,
        onError?: (e: any) => void,
        onComplete?: () => void
    ): boolean {
        let write_channels = new Array<boolean>(4).fill(false);
        write_channels[point_index] = true;

        let request_data: IRosTypeR2CInterfacesSetAnalogOutputStatesRequest;
        let values = new Array<number>(4).fill(0);

        values[point_index] = state;
        request_data = {
            states: {
                stamp: { sec: 0, nanosec: 0 },
                write_channels: write_channels,
                values: values,
            },
        };

        return this._set_io_point(
            request_data,
            IOPointType.ANALOG_OUTPUT,
            () => {
                console.log(
                    `Successfully set analog output ${point_index} to ${state}`
                );
                if (onSuccess) onSuccess();
            },
            () => {
                console.log(
                    `Failed to set analog output ${point_index} to ${state}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error setting analog output ${point_index} to ${state}: ${error}`
                );
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }
}

export class IOConfigurationServices extends IOServices {
    private _build_service_request(
        io_point_configuration: IOPointConfiguration,
        is_config_request: boolean,
        is_enable_disable_request: boolean
    ): IOConfigurationRequest {
        let request_data: IOConfigurationRequest;

        switch (io_point_configuration.type) {
            case IOPointType.ANALOG_INPUT: {
                request_data = {
                    is_enable_disable_request: is_enable_disable_request,
                    is_config_request: is_config_request,
                    config: {
                        channel: io_point_configuration.channel,
                        hardware_config: {
                            configured: io_point_configuration.configured,
                            enabled: io_point_configuration.enabled,
                            channel_type: io_point_configuration.analog_type,
                        },
                        label: io_point_configuration.label,
                        unit: io_point_configuration.measurement_unit,
                        max_electrical_value:
                            io_point_configuration.max_signal_v,
                        min_electrical_value:
                            io_point_configuration.min_signal_v,
                        max_measurement_value: io_point_configuration.max_value,
                        min_measurement_value: io_point_configuration.min_value,
                        transfer_function_type:
                            io_point_configuration.transfer_function_type,
                    },
                };
                break;
            }
            case IOPointType.ANALOG_OUTPUT: {
                request_data = {
                    is_enable_disable_request: is_enable_disable_request,
                    is_config_request: is_config_request,
                    config: {
                        channel: io_point_configuration.channel,
                        hardware_config: {
                            configured: io_point_configuration.configured,
                            enabled: io_point_configuration.enabled,
                            // channel_type: io_point_configuration.analog_type,
                        },
                        label: io_point_configuration.label,
                        unit: io_point_configuration.measurement_unit,
                        max_electrical_value:
                            io_point_configuration.max_signal_v,
                        min_electrical_value:
                            io_point_configuration.min_signal_v,
                        max_measurement_value: io_point_configuration.max_value,
                        min_measurement_value: io_point_configuration.min_value,
                        transfer_function_type:
                            io_point_configuration.transfer_function_type,
                    },
                };
                break;
            }
            case IOPointType.DIGITAL_INPUT:
            case IOPointType.DIGITAL_OUTPUT: {
                request_data = {
                    is_enable_disable_request: is_enable_disable_request,
                    is_config_request: is_config_request,
                    config: {
                        channel: io_point_configuration.channel,
                        hardware_config: {
                            configured: io_point_configuration.configured,
                            enabled: io_point_configuration.enabled,
                        },
                        label: io_point_configuration.label,
                    },
                };
                break;
            }
        }

        return request_data;
    }

    private _check_service_availability(
        point_type: IOPointType,
        reject: (reason: any) => void,
        onError?: (message: string) => void
    ): ROSLIB.Service | null {
        const service = this.get_service(point_type);
        if (!service) {
            const errorMsg = `Service for point type ${IOPointType[point_type]} not defined`;

            console.error(errorMsg);

            if (onError) onError(errorMsg);
            reject(errorMsg);
        }
        return service;
    }

    private _call_config_service(
        service: ROSLIB.Service,
        request: ROSLIB.ServiceRequest,
        onSuccess?: () => void,
        onError?: (message: string) => void,
        onFailure?: () => void,
        onComplete?: () => void
    ) {
        timeoutServiceCall(service, request, 3000)
            .then((result) => {
                if ((result as any).success) {
                    if (onSuccess) onSuccess();
                } else {
                    const errorMsg = `Configuration service call unsuccessful`;
                    console.error(errorMsg);
                    if (onFailure) onFailure();
                }
            })
            .catch((error) => {
                const errorMsg = `Configuration service call failed: ${error}`;
                console.error(errorMsg);
                if (onError) onError(error);
            })
            .finally(() => {
                if (onComplete) onComplete();
            });
    }

    public enable_io_point(
        io_point_configuration: IOPointConfiguration,
        onSuccess?: () => void,
        onError?: (message: string) => void,
        onFailure?: () => void,
        onComplete?: () => void
    ): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            const service = this._check_service_availability(
                io_point_configuration.type,
                reject,
                onError
            );

            const request_data = this._build_service_request(
                io_point_configuration,
                false,
                true
            );
            const request = new ROSLIB.ServiceRequest(request_data);

            this._call_config_service(
                service,
                request,
                () => {
                    console.log(
                        `Successfully enabled IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]}`
                    );
                    if (onSuccess) onSuccess();
                    resolve();
                },
                (error: any) => {
                    const errorMsg = `Enable/Disable for IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]} failed: ${error}`;
                    console.info(errorMsg);
                    if (onError) onError(errorMsg);
                    reject(errorMsg);
                },
                () => {
                    const errorMsg = `Enable/Disable for IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]} unsuccessful`;
                    console.error(errorMsg);
                    if (onFailure) onFailure();
                    reject(errorMsg);
                },
                onComplete
            );
        });
    }

    public configure_io_point(
        io_point_configuration: IOPointConfiguration,
        onSuccess?: () => void,
        onError?: (message: string) => void,
        onFailure?: () => void,
        onComplete?: () => void
    ): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            const service = this._check_service_availability(
                io_point_configuration.type,
                reject,
                onError
            );

            const request_data = this._build_service_request(
                io_point_configuration,
                true,
                false
            );
            const request = new ROSLIB.ServiceRequest(request_data);

            this._call_config_service(
                service,
                request,
                () => {
                    console.log(
                        `Successfully enabled IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]}`
                    );
                    if (onSuccess) onSuccess();
                    resolve;
                },
                (error: any) => {
                    const errorMsg = `Configuration update for IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]} failed: ${error}`;
                    console.info(errorMsg);
                    if (onError) onError(errorMsg);
                    reject(errorMsg);
                },
                () => {
                    const errorMsg = `Configuration update for IO channel ${io_point_configuration.channel} with type ${IOPointType[io_point_configuration.type]} unsuccessful`;
                    console.error(errorMsg);
                    if (onFailure) onFailure();
                    reject(errorMsg);
                },
                onComplete
            );
        });
    }
}

class CameraServices {
    [immerable] = true;

    protected _services: CameraServiceMap = {
        [CameraServiceType.START_STREAM]: null,
        [CameraServiceType.STOP_STREAM]: null,
        [CameraServiceType.DETECT_CAMERAS]: null,
        [CameraServiceType.ENABLE_AI]: null,
        [CameraServiceType.CAPTURE_FRAME]: null,
    };

    public constructor() {}

    public get_service(camera_command_type: CameraServiceType) {
        return this._services[camera_command_type];
    }

    public set_service(
        camera_command_type: CameraServiceType,
        service: ROSLIB.Service
    ) {
        this._services[camera_command_type] = service;
    }
}

export class CameraCommandServices extends CameraServices {
    [immerable] = true;

    public constructor() {
        super();
    }

    private _call_camera_service(
        request_data: any,
        camera_command_type: CameraServiceType,
        onSuccess: (result: any) => void,
        onFailure: () => void,
        onError: (error: any) => void,
        onComplete?: () => void
    ) {
        const service = this.get_service(camera_command_type);
        if (!service) {
            console.error('Camera service is not available');
            onFailure();
            return;
        }

        // console.log("=== CAMERA SERVICE CALL ===");
        // console.log("Service name:", service.name);
        // console.log("Service type:", service.serviceType);
        // console.log("Request data:", request_data);
        // console.log("ROS connected:", service.ros.isConnected);

        timeoutServiceCall(service, request_data, 10000)
            .then((result) => {
                if ((result as any).success) {
                    onSuccess(result);
                } else {
                    onFailure();
                }
            })
            .catch((error) => {
                console.error('Camera service call failed:', error);
                onError(error);
            })
            .finally(() => {
                if (onComplete) onComplete();
            });
    }

    public start_camera_stream(
        camera_id: number,
        uvc_camera: boolean,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data: IRosTypeR2CInterfacesConfigureCameraStreamRequest =
            {
                camera_id: camera_id,
                uvc_camera: uvc_camera,
            };

        this._call_camera_service(
            request_data,
            CameraServiceType.START_STREAM,
            (result) => {
                // console.log(`Successfully started camera ${camera_id} stream`);
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(`Failed to start camera ${camera_id} stream`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error starting camera ${camera_id} stream:`,
                    error
                );
                if (onError) onError(error);
            },
            onComplete
        );
    }

    public stop_camera_stream(
        camera_id: number,
        uvc_camera: boolean,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data: IRosTypeR2CInterfacesConfigureCameraStreamRequest =
            {
                camera_id: camera_id,
                uvc_camera: uvc_camera,
            };

        this._call_camera_service(
            request_data,
            CameraServiceType.STOP_STREAM,
            (result) => {
                // console.log(`Successfully stopped camera ${camera_id} stream`);
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(`Failed to stop camera ${camera_id} stream`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error stopping camera ${camera_id} stream:`,
                    error
                );
                if (onError) onError(error);
            },
            onComplete
        );
    }

    public detect_cameras(
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        // console.log("detect_cameras called - checking service availability...");

        const service = this.get_service(CameraServiceType.DETECT_CAMERAS);
        if (!service) {
            console.error('DETECT_CAMERAS service not found in service map');
            if (onFailure) onFailure();
            return;
        }

        // console.log("DETECT_CAMERAS service found, making request...");
        const request_data = {}; // Empty request for detect cameras

        this._call_camera_service(
            request_data,
            CameraServiceType.DETECT_CAMERAS,
            (result) => {
                // console.log("Successfully detected cameras:", result);
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log('Failed to detect cameras');
                if (onFailure) onFailure();
            },
            (error) => {
                console.log('Error detecting cameras:', error);
                if (onError) onError(error);
            },
            onComplete
        );
    }

    public toggle_ai(
        camera_id: number,
        enable: boolean,
        inferencing_type: string,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data = {
            camera_id: camera_id,
            enable: enable,
            inferencing_type: inferencing_type,
        };

        this._call_camera_service(
            request_data,
            CameraServiceType.ENABLE_AI,
            (result) => {
                console.log(`Successfully toggled AI for camera ${camera_id}`);
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(`Failed to toggle AI for camera ${camera_id}`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error toggling AI for camera ${camera_id}:`,
                    error
                );
                if (onError) onError(error);
            },
            onComplete
        );
    }
}

export class AITrainingServices {
    [immerable] = true;

    protected _services: AITrainingServiceMap = {
        [AITrainingServiceType.GET_STATUS]: null,
        [AITrainingServiceType.START_TRAINING]: null,
        [AITrainingServiceType.STOP_TRAINING]: null,
        [AITrainingServiceType.DEPLOY_MODEL]: null,
        [AITrainingServiceType.GET_PROJECTS]: null,
    };

    public constructor() {}

    public get_service(ai_training_command_type: AITrainingServiceType) {
        return this._services[ai_training_command_type];
    }

    public set_service(
        ai_training_command_type: AITrainingServiceType,
        service: ROSLIB.Service
    ) {
        this._services[ai_training_command_type] = service;
    }
}

export class AITrainingCommandServices extends AITrainingServices {
    [immerable] = true;

    public constructor() {
        super();
    }

    private _call_ai_training_service(
        request_data: any,
        ai_training_command_type: AITrainingServiceType,
        onSuccess: (result: any) => void,
        onFailure: () => void,
        onError: (error: any) => void,
        onComplete?: () => void
    ) {
        const service = this.get_service(ai_training_command_type);
        if (!service) {
            console.error('AI training service is not available');
            onFailure();
            return;
        }

        timeoutServiceCall(service, request_data, 5000) // ← Fixed: added request_data parameter
            .then((result) => {
                if ((result as any).success) {
                    onSuccess(result);
                } else {
                    onFailure();
                }
            })
            .catch((error) => {
                console.error('AI Training service call failed:', error);
                onError(error);
            })
            .finally(() => {
                if (onComplete) onComplete();
            });
    }

    // Keep existing get_ai_training_status method
    public get_ai_training_status(
        project_id: number,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data = {
            project_id: project_id,
        };

        this._call_ai_training_service(
            request_data,
            AITrainingServiceType.GET_STATUS,
            (result) => {
                console.log(
                    `Successfully retrieved AI training status for project ${project_id}`
                );
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(
                    `Failed to retrieve AI training status for project ${project_id}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error retrieving AI training status for project ${project_id}:`,
                    error
                );
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    public start_ai_training(
        train_project_id: number,
        val_project_id: number,
        model_type: string,
        epochs: number,
        batch_size: number,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        // ros2 service call /training/start_training r2c_interfaces/srv/ConfigureAITraining
        // "{train_project_id: 1, val_project_id: 2, model_type: 'yolo_nas_s', epochs: 3, batch_size: 4}"
        const request_data = {
            train_project_id: train_project_id,
            val_project_id: val_project_id,
            model_type: model_type,
            epochs: epochs,
            batch_size: batch_size,
        };

        this._call_ai_training_service(
            request_data,
            AITrainingServiceType.START_TRAINING,
            (result) => {
                console.log(
                    `Successfully started AI training with train: ${train_project_id}, val: ${val_project_id}`
                );
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(
                    `Failed to start AI training with train: ${train_project_id}, val: ${val_project_id}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error starting AI training:`, error);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    // Keep existing stop_ai_training method but fix it
    public stop_ai_training(
        project_id: number,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data = {
            project_id: project_id,
            model_type: '',
            epochs: 0,
            batch_size: 0,
        };

        this._call_ai_training_service(
            request_data,
            AITrainingServiceType.STOP_TRAINING,
            (result) => {
                console.log(
                    `Successfully stopped AI training for project ${project_id}`
                );
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(
                    `Failed to stop AI training for project ${project_id}`
                );
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(
                    `Error stopping AI training for project ${project_id}:`,
                    error
                );
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    // Updated get_projects method to match ROS2 service
    public get_projects(
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        // ros2 service call /training/get_projects r2c_interfaces/srv/GetAIProjects "{}"
        const request_data = {};

        this._call_ai_training_service(
            request_data,
            AITrainingServiceType.GET_PROJECTS,
            (result) => {
                console.log(`Successfully retrieved AI training projects:`);
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(`Failed to retrieve AI training projects`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error retrieving AI training projects:`, error);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }

    // TODO: Add deploy model
    public deploy_model(
        model_path: string,
        camera_id: number,
        onSuccess?: (result: any) => void,
        onFailure?: () => void,
        onError?: (error: any) => void,
        onComplete?: () => void
    ) {
        const request_data = {
            model_path: model_path,
            camera_id: camera_id,
        };

        this._call_ai_training_service(
            request_data,
            AITrainingServiceType.DEPLOY_MODEL,
            (result) => {
                console.log(
                    `Successfully deployed model to camera ${camera_id}`
                );
                if (onSuccess) onSuccess(result);
            },
            () => {
                console.log(`Failed to deploy model to camera ${camera_id}`);
                if (onFailure) onFailure();
            },
            (error) => {
                console.log(`Error deploying model:`, error);
                if (onError) onError(error);
            },
            () => {
                if (onComplete) onComplete();
            }
        );
    }
}

export interface RosState {
    ros: ROSLIB.Ros | null;
    connected: boolean;
}

export interface RosServices {
    opc_services: OPCUAServices;
    application_services: ApplicationServices;
}

export class ApplicationContext {
    [immerable] = true;

    // latest_document: DatabaseDocument | null = null;
    // messages: DatabaseMessageArray | null = null;
    // configuration: UIConfiguration | null = null;
    ui_configuration: uiConfigurationType = null;
    io_configuration: ioConfigurationType = null;
    opc_configuration: opcConfigurationType = null;
    // io_state: DatabaseIOStateDocumentArray | null = null;
    hardware_configuration: HardwareConfiguration | null = null;
    heartbeat: boolean = false;
    heartbeat_counter: number = 0;
    database_online: boolean = false;
    // ra_websocket: WebSocket | null = null;
    ra_ros_websocket: ROSLIB.Ros | null = null;
    ros_state: RosState = {
        ros: null,
        connected: false,
    };
    available_database_tables: availableTables | null = null;
    // plot_configuration: PlotConfiguration[] = [];
    io_configuration_services: IOConfigurationServices;
    io_command_services: IOCommandServices;
    application_services: ApplicationServices;
    axis_command_services: AxisCommandServices;
    camera_services: CameraCommandServices;
    ai_training_services: AITrainingCommandServices;
    // opc_ua_services: OPCUAServices;
    ros_services: RosServices | null = null;
    application_state: ApplicationState;

    // Machine State
    analog_in_data: IRosTypeR2CInterfacesAnalogInData = null;
    analog_out_data: IRosTypeR2CInterfacesAnalogOutData | null = null;
    digital_in_data: IRosTypeR2CInterfacesDigitalInData | null = null;
    digital_out_data: IRosTypeR2CInterfacesDigitalOutData | null = null;
    gpio_configuration_state: IRosTypeR2CInterfacesGpioConfigurationState | null =
        null;

    axis_data: Record<number, IRosTypeR2CInterfacesEncoderEstimates> = {};
    axis_torque: Record<number, IRosTypeR2CInterfacesTorques> = {};
    axis_heartbeat: Record<number, IRosTypeR2CInterfacesHeartbeat> = {};
    opc_ua_data: IRosTypeR2CInterfacesOpcuaData | null = null;

    constructor() {
        // this.latest_document = new DatabaseDocument();
        // this.configuration = new UIConfiguration();
        // this.ui_configuration = null;
        // this.messages = new DatabaseMessageArray();
        // this.io_state = new DatabaseIOStateDocumentArray();
        this.io_configuration_services = new IOConfigurationServices();
        this.io_command_services = new IOCommandServices();
        this.camera_services = new CameraCommandServices();
        this.ai_training_services = new AITrainingCommandServices();
        this.application_state = new ApplicationState();
        // this.ros_state = {
        //     ros: null,
        //     connected: false,
        // };
    }

    public getIOState(point_type: IOPointType) {
        switch (point_type) {
            case IOPointType.ANALOG_INPUT:
                return this.analog_in_data;
            case IOPointType.DIGITAL_INPUT:
                return this.digital_in_data;
            case IOPointType.DIGITAL_OUTPUT:
                return this.digital_out_data;
            case IOPointType.ANALOG_OUTPUT:
                return this.analog_out_data;
        }
    }

    public getGpioConfigurationState(
        point_type: IOPointType
    ):
        | IRosTypeR2CInterfacesDigitalInHardwareConfig[]
        | IRosTypeR2CInterfacesDigitalOutHardwareConfig[]
        | IRosTypeR2CInterfacesAnalogInHardwareConfig[]
        | IRosTypeR2CInterfacesAnalogOutHardwareConfig[]
        | null {
        switch (point_type) {
            case IOPointType.ANALOG_INPUT:
                return this.gpio_configuration_state?.analog_input_configs;
            case IOPointType.DIGITAL_INPUT:
                return this.gpio_configuration_state?.digital_input_configs;
            case IOPointType.DIGITAL_OUTPUT:
                return this.gpio_configuration_state?.digital_output_configs;
            case IOPointType.ANALOG_OUTPUT:
                return this.gpio_configuration_state?.analog_output_configs;
        }
    }
}

export default ApplicationContext;
