import { ioModuleDescriptionType } from '@/lib/models/autogenerated/configuration_models';
import {
    IRosTypeR2CInterfacesIoModuleStateModuleType,
    IRosTypeR2CInterfacesIoPointStatePointType,
} from './ros_types';

// --- PREDEFINED MODULE TYPES ---
export const ioModuleTypes: ioModuleDescriptionType[] = [
    {
        name: '8-Slot DI',
        icon: 'DigitalInIcon',
        ros_module_type: IRosTypeR2CInterfacesIoModuleStateModuleType.T8PT_DI,
        points: [
            {
                label: 'DI-1',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-2',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-3',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-4',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-5',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-6',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-7',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-8',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
        ],
    },
    {
        name: '8-Slot DO',
        icon: 'DigitalInIcon',
        ros_module_type: IRosTypeR2CInterfacesIoModuleStateModuleType.T8PT_DO,
        points: [
            {
                label: 'DO-1',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-2',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-3',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-4',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-5',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-6',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-7',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-8',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
        ],
    },
    {
        name: '16-Slot DIO',
        icon: 'DigitalIOIcon',
        ros_module_type:
            IRosTypeR2CInterfacesIoModuleStateModuleType.T16PT_DI_16PT_DO,
        points: [
            {
                label: 'DI-1',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-2',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-3',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-4',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-5',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-6',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-7',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DI-8',
                type: 'DI',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DI,
            },
            {
                label: 'DO-1',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-2',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-3',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-4',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-5',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-6',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-7',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
            {
                label: 'DO-8',
                type: 'DO',
                ros_point_type: IRosTypeR2CInterfacesIoPointStatePointType.DO,
            },
        ],
    },

    {
        name: '4-Slot AIO',
        icon: 'AnalogIOIcon',
        points: [
            { label: 'AI-1', type: 'AI' },
            { label: 'AI-2', type: 'AI' },
            { label: 'AO-1', type: 'AO' },
            { label: 'AO-2', type: 'AO' },
        ],
    },
    {
        name: '2-Slot AI',
        icon: 'AnalogInIcon',
        points: [
            { label: 'AI-1', type: 'AI' },
            { label: 'AI-2', type: 'AI' },
        ],
    },
    {
        name: 'Temperature',
        icon: 'TempIcon',
        points: [
            { label: 'Temp-1', type: 'AI' },
            { label: 'Temp-2', type: 'AI' },
        ],
    },
    {
        name: 'H.S. Counter',
        icon: 'CounterIcon',
        points: [
            { label: 'Count-A', type: 'DI' },
            { label: 'Count-B', type: 'DI' },
        ],
    },
];
