# This file is autogenerated by utilities/generate_models.py - DO NOT EDIT MANUALLY

from __future__ import annotations
from pydantic import BaseModel, Field, PrivateAttr
from datetime import datetime
from uuid import UUID, uuid4
from typing import Dict, Any, List, Optional
import re

class AutogeneratedPydanticModel(BaseModel):
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AutogeneratedPydanticModel':
        return AutogeneratedPydanticModel()

    def to_db_format(self) -> Dict[str, Any]:
        return {}

# --- Static Models for each table defined in schema.yml ---
class SensorData(AutogeneratedPydanticModel):
    __table_name__ = "sensor_data"

    stamp: datetime
    device_id: str
    temperature: Optional[float] = None
    humidity: Optional[float] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'SensorData':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class Logs(AutogeneratedPydanticModel):
    __table_name__ = "logs"

    time: datetime
    device_id: str
    message_level: Optional[str]
    message: Optional[str]

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'Logs':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class ProjectMetrics(AutogeneratedPydanticModel):
    __table_name__ = "project_metrics"

    timestamp: datetime
    project_name: str
    value: Optional[float] = None
    status: Optional[str]

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'ProjectMetrics':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class UserActivity(AutogeneratedPydanticModel):
    __table_name__ = "user_activity"

    activity_time: datetime
    user_id: str
    action: Optional[str]
    duration_ms: Optional[int]

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'UserActivity':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class FrontendConfigs(AutogeneratedPydanticModel):
    __table_name__ = "frontend_configs"

    client_id: str
    config_data: Optional[Dict[str, Any]]
    last_updated: datetime

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'FrontendConfigs':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class IoConfigs(AutogeneratedPydanticModel):
    __table_name__ = "io_configs"

    client_id: str
    config_data: Optional[Dict[str, Any]]
    last_updated: datetime

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'IoConfigs':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class OpcConfigs(AutogeneratedPydanticModel):
    __table_name__ = "opc_configs"

    client_id: str
    config_data: Optional[Dict[str, Any]]
    last_updated: datetime

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'OpcConfigs':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class Users(AutogeneratedPydanticModel):
    __table_name__ = "users"

    user_id: Any
    username: str
    hashed_password: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'Users':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class RealtimeSysState(AutogeneratedPydanticModel):
    __table_name__ = "realtime_sys_state"

    stamp: datetime
    state: Optional[int]

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'RealtimeSysState':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class AnalogInConfig(AutogeneratedPydanticModel):
    __table_name__ = "analog_in_config"

    stamp: datetime
    channel: int
    label: Optional[str]
    unit: Optional[str]
    min_electrical_value: Optional[float] = None
    max_electrical_value: Optional[float] = None
    min_measurement_value: Optional[float] = None
    max_measurement_value: Optional[float] = None
    transfer_function_type: Optional[int] = None
    hardware_config__configured: Optional[bool] = None
    hardware_config__enabled: Optional[bool] = None
    hardware_config__channel_type: Optional[int] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AnalogInConfig':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class AnalogInData(AutogeneratedPydanticModel):
    __table_name__ = "analog_in_data"

    read_channels: List[bool]
    values: List[float]
    types: List[int]
    stamp: datetime
    read_channels__0: Optional[bool] = None
    read_channels__1: Optional[bool] = None
    read_channels__2: Optional[bool] = None
    values__0: Optional[float] = None
    values__1: Optional[float] = None
    values__2: Optional[float] = None
    types__0: Optional[int] = None
    types__1: Optional[int] = None
    types__2: Optional[int] = None

    _read_channels__0: Optional[bool] = PrivateAttr(None)
    _read_channels__1: Optional[bool] = PrivateAttr(None)
    _read_channels__2: Optional[bool] = PrivateAttr(None)
    _values__0: Optional[float] = PrivateAttr(None)
    _values__1: Optional[float] = PrivateAttr(None)
    _values__2: Optional[float] = PrivateAttr(None)
    _types__0: Optional[int] = PrivateAttr(None)
    _types__1: Optional[int] = PrivateAttr(None)
    _types__2: Optional[int] = PrivateAttr(None)
    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AnalogInData':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        # Dynamically reconstruct lists from the flattened database format.
        read_channels = []
        i = 0
        while True:
            key = f"read_channels__{i}"
            if key in reconstructed_data:
                read_channels.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["read_channels"] = read_channels
        values = []
        i = 0
        while True:
            key = f"values__{i}"
            if key in reconstructed_data:
                values.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["values"] = values
        types = []
        i = 0
        while True:
            key = f"types__{i}"
            if key in reconstructed_data:
                types.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["types"] = types
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        read_channels = base_data.pop("read_channels", [])
        for i, val in enumerate(read_channels):
            base_data[f"read_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        types = base_data.pop("types", [])
        for i, val in enumerate(types):
            base_data[f"types__{i}"] = val
        return base_data

class AnalogOutConfig(AutogeneratedPydanticModel):
    __table_name__ = "analog_out_config"

    stamp: datetime
    channel: int
    label: Optional[str]
    unit: Optional[str]
    min_electrical_value: Optional[float] = None
    max_electrical_value: Optional[float] = None
    min_measurement_value: Optional[float] = None
    max_measurement_value: Optional[float] = None
    transfer_function_type: Optional[int] = None
    hardware_config__configured: Optional[bool] = None
    hardware_config__enabled: Optional[bool] = None
    hardware_config__pwm_period_ms: Optional[int]
    hardware_config__initial_value_volts: Optional[float] = None
    hardware_config__estop_configured: Optional[bool] = None
    hardware_config__estop_value_volts: Optional[float] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AnalogOutConfig':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class AnalogOutData(AutogeneratedPydanticModel):
    __table_name__ = "analog_out_data"

    write_channels: List[bool]
    values: List[float]
    stamp: datetime
    write_channels__0: Optional[bool] = None
    write_channels__1: Optional[bool] = None
    write_channels__2: Optional[bool] = None
    write_channels__3: Optional[bool] = None
    values__0: Optional[float] = None
    values__1: Optional[float] = None
    values__2: Optional[float] = None
    values__3: Optional[float] = None

    _write_channels__0: Optional[bool] = PrivateAttr(None)
    _write_channels__1: Optional[bool] = PrivateAttr(None)
    _write_channels__2: Optional[bool] = PrivateAttr(None)
    _write_channels__3: Optional[bool] = PrivateAttr(None)
    _values__0: Optional[float] = PrivateAttr(None)
    _values__1: Optional[float] = PrivateAttr(None)
    _values__2: Optional[float] = PrivateAttr(None)
    _values__3: Optional[float] = PrivateAttr(None)
    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AnalogOutData':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        # Dynamically reconstruct lists from the flattened database format.
        write_channels = []
        i = 0
        while True:
            key = f"write_channels__{i}"
            if key in reconstructed_data:
                write_channels.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["write_channels"] = write_channels
        values = []
        i = 0
        while True:
            key = f"values__{i}"
            if key in reconstructed_data:
                values.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["values"] = values
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        write_channels = base_data.pop("write_channels", [])
        for i, val in enumerate(write_channels):
            base_data[f"write_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        return base_data

class DigitalInConfig(AutogeneratedPydanticModel):
    __table_name__ = "digital_in_config"

    stamp: datetime
    channel: int
    label: Optional[str]
    hardware_config__configured: Optional[bool] = None
    hardware_config__enabled: Optional[bool] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'DigitalInConfig':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class DigitalInData(AutogeneratedPydanticModel):
    __table_name__ = "digital_in_data"

    read_channels: List[bool]
    values: List[bool]
    stamp: datetime
    read_channels__0: Optional[bool] = None
    read_channels__1: Optional[bool] = None
    read_channels__2: Optional[bool] = None
    read_channels__3: Optional[bool] = None
    read_channels__4: Optional[bool] = None
    read_channels__5: Optional[bool] = None
    read_channels__6: Optional[bool] = None
    read_channels__7: Optional[bool] = None
    values__0: Optional[bool] = None
    values__1: Optional[bool] = None
    values__2: Optional[bool] = None
    values__3: Optional[bool] = None
    values__4: Optional[bool] = None
    values__5: Optional[bool] = None
    values__6: Optional[bool] = None
    values__7: Optional[bool] = None

    _read_channels__0: Optional[bool] = PrivateAttr(None)
    _read_channels__1: Optional[bool] = PrivateAttr(None)
    _read_channels__2: Optional[bool] = PrivateAttr(None)
    _read_channels__3: Optional[bool] = PrivateAttr(None)
    _read_channels__4: Optional[bool] = PrivateAttr(None)
    _read_channels__5: Optional[bool] = PrivateAttr(None)
    _read_channels__6: Optional[bool] = PrivateAttr(None)
    _read_channels__7: Optional[bool] = PrivateAttr(None)
    _values__0: Optional[bool] = PrivateAttr(None)
    _values__1: Optional[bool] = PrivateAttr(None)
    _values__2: Optional[bool] = PrivateAttr(None)
    _values__3: Optional[bool] = PrivateAttr(None)
    _values__4: Optional[bool] = PrivateAttr(None)
    _values__5: Optional[bool] = PrivateAttr(None)
    _values__6: Optional[bool] = PrivateAttr(None)
    _values__7: Optional[bool] = PrivateAttr(None)
    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'DigitalInData':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        # Dynamically reconstruct lists from the flattened database format.
        read_channels = []
        i = 0
        while True:
            key = f"read_channels__{i}"
            if key in reconstructed_data:
                read_channels.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["read_channels"] = read_channels
        values = []
        i = 0
        while True:
            key = f"values__{i}"
            if key in reconstructed_data:
                values.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["values"] = values
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        read_channels = base_data.pop("read_channels", [])
        for i, val in enumerate(read_channels):
            base_data[f"read_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        return base_data

class DigitalOutConfig(AutogeneratedPydanticModel):
    __table_name__ = "digital_out_config"

    stamp: datetime
    channel: int
    label: Optional[str]
    hardware_config__configured: Optional[bool] = None
    hardware_config__enabled: Optional[bool] = None
    hardware_config__initial_value: Optional[bool] = None
    hardware_config__estop_configured: Optional[bool] = None
    hardware_config__estop_value: Optional[bool] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'DigitalOutConfig':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class DigitalOutData(AutogeneratedPydanticModel):
    __table_name__ = "digital_out_data"

    write_channels: List[bool]
    values: List[bool]
    stamp: datetime
    write_channels__0: Optional[bool] = None
    write_channels__1: Optional[bool] = None
    write_channels__2: Optional[bool] = None
    write_channels__3: Optional[bool] = None
    write_channels__4: Optional[bool] = None
    write_channels__5: Optional[bool] = None
    write_channels__6: Optional[bool] = None
    write_channels__7: Optional[bool] = None
    values__0: Optional[bool] = None
    values__1: Optional[bool] = None
    values__2: Optional[bool] = None
    values__3: Optional[bool] = None
    values__4: Optional[bool] = None
    values__5: Optional[bool] = None
    values__6: Optional[bool] = None
    values__7: Optional[bool] = None

    _write_channels__0: Optional[bool] = PrivateAttr(None)
    _write_channels__1: Optional[bool] = PrivateAttr(None)
    _write_channels__2: Optional[bool] = PrivateAttr(None)
    _write_channels__3: Optional[bool] = PrivateAttr(None)
    _write_channels__4: Optional[bool] = PrivateAttr(None)
    _write_channels__5: Optional[bool] = PrivateAttr(None)
    _write_channels__6: Optional[bool] = PrivateAttr(None)
    _write_channels__7: Optional[bool] = PrivateAttr(None)
    _values__0: Optional[bool] = PrivateAttr(None)
    _values__1: Optional[bool] = PrivateAttr(None)
    _values__2: Optional[bool] = PrivateAttr(None)
    _values__3: Optional[bool] = PrivateAttr(None)
    _values__4: Optional[bool] = PrivateAttr(None)
    _values__5: Optional[bool] = PrivateAttr(None)
    _values__6: Optional[bool] = PrivateAttr(None)
    _values__7: Optional[bool] = PrivateAttr(None)
    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'DigitalOutData':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        # Dynamically reconstruct lists from the flattened database format.
        write_channels = []
        i = 0
        while True:
            key = f"write_channels__{i}"
            if key in reconstructed_data:
                write_channels.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["write_channels"] = write_channels
        values = []
        i = 0
        while True:
            key = f"values__{i}"
            if key in reconstructed_data:
                values.append(reconstructed_data[key])
                # del reconstructed_data[key]
                i += 1
            else:
                break
        reconstructed_data["values"] = values
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        write_channels = base_data.pop("write_channels", [])
        for i, val in enumerate(write_channels):
            base_data[f"write_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        return base_data

class DefectDetection(AutogeneratedPydanticModel):
    __table_name__ = "defect_detection"

    stamp: datetime
    image_id: Optional[UUID]
    bbox_x_center: Optional[float] = None
    bbox_y_center: Optional[float] = None
    bbox_width: Optional[float] = None
    bbox_height: Optional[float] = None
    product_type: Optional[str]
    defect_type: Optional[str]
    confidence: Optional[float] = None
    model: Optional[str]

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'DefectDetection':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data

class AiModels(AutogeneratedPydanticModel):
    __table_name__ = "ai_models"

    stamp: datetime
    model: Optional[str]
    status: Optional[str]
    mAP: Optional[float] = None

    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AiModels':
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


# --- Dynamic Models based on 'number_of_tables' from schema.yml ---
class AxisEstimates(AutogeneratedPydanticModel):
    __table_name__ = "axis_estimates"
    """Base Pydantic model for the axis_estimates tables."""
    stamp: datetime
    axis_index: int
    position: Optional[float] = None
    velocity: Optional[float] = None
    
    @classmethod
    def from_db_format(cls, **data: Any) -> 'AxisEstimates':
        """
        Reconstructs the model from the flattened database format.
        """
        return cls.model_validate(data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        return self.model_dump(by_alias=True)

# --- Mapping Dictionaries ---

# Dictionary to map all table names to their corresponding Pydantic models.
DYNAMIC_TABLE_MODELS = {
    'sensor_data': SensorData,
    'logs': Logs,
    'project_metrics': ProjectMetrics,
    'user_activity': UserActivity,
    'frontend_configs': FrontendConfigs,
    'io_configs': IoConfigs,
    'opc_configs': OpcConfigs,
    'users': Users,
    'realtime_sys_state': RealtimeSysState,
    'analog_in_config': AnalogInConfig,
    'analog_in_data': AnalogInData,
    'analog_out_config': AnalogOutConfig,
    'analog_out_data': AnalogOutData,
    'digital_in_config': DigitalInConfig,
    'digital_in_data': DigitalInData,
    'digital_out_config': DigitalOutConfig,
    'digital_out_data': DigitalOutData,
    'defect_detection': DefectDetection,
    'ai_models': AiModels,
    'axis_estimates_0': AxisEstimates,
    'axis_estimates_1': AxisEstimates,
    'axis_estimates_2': AxisEstimates,
    'axis_estimates_3': AxisEstimates,
}