# This file is autogenerated by generate_models.py - DO NOT EDIT MANUALLY

from __future__ import annotations
from pydantic import BaseModel, Field, PrivateAttr
from datetime import datetime
from uuid import UUID, uuid4
from typing import Dict, Any, List, Optional


class SensorData(BaseModel):
    time: datetime
    device_id: str
    temperature: Optional[float]
    humidity: Optional[float]

    @classmethod
    def from_db_format(cls, **data: Any) -> "SensorData":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class Logs(BaseModel):
    time: datetime
    device_id: str
    message_level: Optional[str]
    message: Optional[str]

    @classmethod
    def from_db_format(cls, **data: Any) -> "Logs":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class ProjectMetrics(BaseModel):
    timestamp: datetime
    project_name: str
    value: Optional[float]
    status: Optional[str]

    @classmethod
    def from_db_format(cls, **data: Any) -> "ProjectMetrics":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class UserActivity(BaseModel):
    activity_time: datetime
    user_id: str
    action: Optional[str]
    duration_ms: Optional[int]

    @classmethod
    def from_db_format(cls, **data: Any) -> "UserActivity":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class FrontendConfigs(BaseModel):
    client_id: str
    config_data: Optional[Dict[str, Any]]
    last_updated: datetime

    @classmethod
    def from_db_format(cls, **data: Any) -> "FrontendConfigs":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class Users(BaseModel):
    user_id: Any
    username: str
    hashed_password: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @classmethod
    def from_db_format(cls, **data: Any) -> "Users":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class RealtimeSysState(BaseModel):
    stamp: datetime
    state: Optional[int]

    @classmethod
    def from_db_format(cls, **data: Any) -> "RealtimeSysState":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class AnalogInConfig(BaseModel):
    stamp: datetime
    channel: int
    label: Optional[str]
    unit: Optional[str]
    min_electrical_value: Optional[float]
    max_electrical_value: Optional[float]
    min_measurement_value: Optional[float]
    max_measurement_value: Optional[float]
    transfer_function_type: Optional[int]
    hardware_config__configured: Optional[bool]
    hardware_config__enabled: Optional[bool]
    hardware_config__channel_type: Optional[int]

    @classmethod
    def from_db_format(cls, **data: Any) -> "AnalogInConfig":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class AnalogInData(BaseModel):
    read_channels: List[bool]
    values: List[float]
    types: List[int]
    stamp: datetime
    read_channels__0: Optional[bool]
    read_channels__1: Optional[bool]
    read_channels__2: Optional[bool]
    read_channels__3: Optional[bool]
    read_channels__4: Optional[bool]
    read_channels__5: Optional[bool]
    read_channels__6: Optional[bool]
    read_channels__7: Optional[bool]
    values__0: Optional[float]
    values__1: Optional[float]
    values__2: Optional[float]
    values__3: Optional[float]
    values__4: Optional[float]
    values__5: Optional[float]
    values__6: Optional[float]
    values__7: Optional[float]
    types__0: Optional[int]
    types__1: Optional[int]
    types__2: Optional[int]
    types__3: Optional[int]
    types__4: Optional[int]
    types__5: Optional[int]
    types__6: Optional[int]
    types__7: Optional[int]

    @classmethod
    def from_db_format(cls, **data: Any) -> "AnalogInData":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        read_channels = [reconstructed_data[f"read_channels__{i}"] for i in range(8)]
        reconstructed_data["read_channels"] = read_channels
        values = [reconstructed_data[f"values__{i}"] for i in range(8)]
        reconstructed_data["values"] = values
        types = [reconstructed_data[f"types__{i}"] for i in range(8)]
        reconstructed_data["types"] = types
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        read_channels = base_data.pop("read_channels", [])
        for i, val in enumerate(read_channels):
            base_data[f"read_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        types = base_data.pop("types", [])
        for i, val in enumerate(types):
            base_data[f"types__{i}"] = val
        return base_data


class AnalogOutConfig(BaseModel):
    stamp: datetime
    channel: int
    label: Optional[str]
    unit: Optional[str]
    min_electrical_value: Optional[float]
    max_electrical_value: Optional[float]
    min_measurement_value: Optional[float]
    max_measurement_value: Optional[float]
    transfer_function_type: Optional[int]
    hardware_config__configured: Optional[bool]
    hardware_config__enabled: Optional[bool]
    hardware_config__pwm_period_ms: Optional[int]
    hardware_config__initial_value_volts: Optional[float]
    hardware_config__estop_configured: Optional[bool]
    hardware_config__estop_value_volts: Optional[float]

    @classmethod
    def from_db_format(cls, **data: Any) -> "AnalogOutConfig":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class DigitalInConfig(BaseModel):
    stamp: datetime
    channel: int
    label: Optional[str]
    hardware_config__configured: Optional[bool]
    hardware_config__enabled: Optional[bool]

    @classmethod
    def from_db_format(cls, **data: Any) -> "DigitalInConfig":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class DigitalInData(BaseModel):
    read_channels: List[bool]
    values: List[bool]
    stamp: datetime
    read_channels__0: Optional[bool]
    read_channels__1: Optional[bool]
    read_channels__2: Optional[bool]
    read_channels__3: Optional[bool]
    read_channels__4: Optional[bool]
    read_channels__5: Optional[bool]
    read_channels__6: Optional[bool]
    read_channels__7: Optional[bool]
    values__0: Optional[bool]
    values__1: Optional[bool]
    values__2: Optional[bool]
    values__3: Optional[bool]
    values__4: Optional[bool]
    values__5: Optional[bool]
    values__6: Optional[bool]
    values__7: Optional[bool]

    @classmethod
    def from_db_format(cls, **data: Any) -> "DigitalInData":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        read_channels = [reconstructed_data[f"read_channels__{i}"] for i in range(8)]
        reconstructed_data["read_channels"] = read_channels
        values = [reconstructed_data[f"values__{i}"] for i in range(8)]
        reconstructed_data["values"] = values
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        read_channels = base_data.pop("read_channels", [])
        for i, val in enumerate(read_channels):
            base_data[f"read_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        return base_data


class DigitalOutConfig(BaseModel):
    stamp: datetime
    channel: int
    label: Optional[str]
    hardware_config__configured: Optional[bool]
    hardware_config__enabled: Optional[bool]
    hardware_config__initial_value: Optional[bool]
    hardware_config__estop_configured: Optional[bool]
    hardware_config__estop_value: Optional[bool]

    @classmethod
    def from_db_format(cls, **data: Any) -> "DigitalOutConfig":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


class DigitalOutData(BaseModel):
    write_channels: List[bool]
    values: List[bool]
    stamp: datetime
    write_channels__0: Optional[bool]
    write_channels__1: Optional[bool]
    write_channels__2: Optional[bool]
    write_channels__3: Optional[bool]
    write_channels__4: Optional[bool]
    write_channels__5: Optional[bool]
    write_channels__6: Optional[bool]
    write_channels__7: Optional[bool]
    values__0: Optional[bool]
    values__1: Optional[bool]
    values__2: Optional[bool]
    values__3: Optional[bool]
    values__4: Optional[bool]
    values__5: Optional[bool]
    values__6: Optional[bool]
    values__7: Optional[bool]

    @classmethod
    def from_db_format(cls, **data: Any) -> "DigitalOutData":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        write_channels = [reconstructed_data[f"write_channels__{i}"] for i in range(8)]
        reconstructed_data["write_channels"] = write_channels
        values = [reconstructed_data[f"values__{i}"] for i in range(8)]
        reconstructed_data["values"] = values
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        write_channels = base_data.pop("write_channels", [])
        for i, val in enumerate(write_channels):
            base_data[f"write_channels__{i}"] = val
        values = base_data.pop("values", [])
        for i, val in enumerate(values):
            base_data[f"values__{i}"] = val
        return base_data


class AxisEstimates(BaseModel):
    stamp: datetime
    axis_index: int
    position: Optional[float]
    velocity: Optional[float]

    @classmethod
    def from_db_format(cls, **data: Any) -> "AxisEstimates":
        """
        Reconstructs the model from the flattened database format, handling all fields.
        """
        reconstructed_data = data.copy()
        return cls.model_validate(reconstructed_data)

    def to_db_format(self) -> Dict[str, Any]:
        """
        Converts the model to a flattened format for database storage.
        """
        base_data = self.model_dump(by_alias=True)
        return base_data


DYNAMIC_TABLE_MODELS = {
    "sensor_data": SensorData,
    "logs": Logs,
    "project_metrics": ProjectMetrics,
    "user_activity": UserActivity,
    "frontend_configs": FrontendConfigs,
    "users": Users,
    "realtime_sys_state": RealtimeSysState,
    "analog_in_config": AnalogInConfig,
    "analog_in_data": AnalogInData,
    "analog_out_config": AnalogOutConfig,
    "digital_in_config": DigitalInConfig,
    "digital_in_data": DigitalInData,
    "digital_out_config": DigitalOutConfig,
    "digital_out_data": DigitalOutData,
    "axis_estimates": AxisEstimates,
}
