# This file is auto-generated by utilities/generate_models.py
# Do not edit this file manually.

from pydantic import BaseModel, Field
from datetime import datetime
from typing import Dict, Any, Optional
import uuid # Needed for UUID type

# Dynamically created Pydantic models for each table

DYNAMIC_TABLE_MODELS: Dict[str, type[BaseModel]] = {}

class SensorData(BaseModel):
    time: datetime
    device_id: str
    temperature: Optional[float]
    humidity: Optional[float]

DYNAMIC_TABLE_MODELS['sensor_data'] = SensorData

class ProjectMetrics(BaseModel):
    timestamp: datetime
    project_name: str
    value: Optional[float]
    status: str

DYNAMIC_TABLE_MODELS['project_metrics'] = ProjectMetrics

class UserActivity(BaseModel):
    activity_time: datetime
    user_id: str
    action: str
    duration_ms: Optional[int]

DYNAMIC_TABLE_MODELS['user_activity'] = UserActivity

class FrontendConfigs(BaseModel):
    client_id: str
    config_data: Optional[Dict[str, Any]]
    last_updated: datetime

DYNAMIC_TABLE_MODELS['frontend_configs'] = FrontendConfigs

class Users(BaseModel):
    user_id: uuid.UUID
    username: str
    hashed_password: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

DYNAMIC_TABLE_MODELS['users'] = Users
