# # ./tools/generate_zod_models.py

import os
import sys
import yaml
from pathlib import Path
from typing import Dict, Any, List, Optional
from loguru import logger
import re

# Adjust sys.path to ensure 'backend' is recognized as a package root
current_dir = os.path.dirname(os.path.abspath(__file__))
backend_root = os.path.join(current_dir, "..")  # THIS LINE WAS CORRECTED
sys.path.insert(0, backend_root)

# --- Configuration ---
SCHEMA_FILE_PATH = os.getenv(
    "SCHEMA_FILE_PATH", os.path.join(backend_root, "config", "schema.yml")
)
GENERATED_MODELS_DIR = os.getenv(
    "GENERATED_MODELS_DIR",
    os.path.join(backend_root, "frontend", "src", "autogenerated"),
)
GENERATED_MODELS_FILE = os.path.join(GENERATED_MODELS_DIR, "generated_models.ts")

# --- Loguru Configuration ---
logger.remove()
logger.add(
    sys.stderr,
    level="INFO",
    format="{time} | {level} | {module}:{function}:{line} - {message}",
    colorize=True,
)

# --- PostgreSQL to Zod/TypeScript Type Mappings ---
TYPE_MAPPINGS = {
    "TEXT": "z.string().optional()",
    "TEXT NOT NULL": "z.string()",
    "TEXT NOT NULL UNIQUE": "z.string()",
    "INTEGER": "z.number().optional()",
    "INTEGER NOT NULL": "z.number()",
    "SMALLINT": "z.number().optional()",
    "SMALLINT NOT NULL": "z.number()",
    "DOUBLE PRECISION": "z.number().optional()",
    "DOUBLE PRECISION NOT NULL": "z.number()",
    "NUMERIC": "z.number().optional()",
    "NUMERIC NOT NULL": "z.number()",
    "BOOLEAN": "z.boolean().optional()",
    "BOOLEAN NOT NULL": "z.boolean()",
    "TIMESTAMPTZ": "z.string().datetime().optional()",
    "TIMESTAMPTZ NOT NULL": "z.string().datetime()",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "z.string().datetime().default(new Date().toISOString())",
    "JSONB": "z.record(z.unknown()).optional()",
    "JSONB NOT NULL": "z.record(z.unknown())",
    "UUID": "z.string().uuid().optional()",
    "UUID NOT NULL": "z.string().uuid()",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "z.string().uuid().default(crypto.randomUUID())",
}

# Special handling for tables with list-like columns
SPECIAL_TABLE_LIST_FIELDS = {
    "analog_in_data": {
        "read_channels": "z.array(z.boolean())",
        "values": "z.array(z.number())",
        "types": "z.array(z.number())",
    },
    "digital_in_data": {
        "read_channels": "z.array(z.boolean())",
        "values": "z.array(z.boolean())",
    },
    "digital_out_data": {
        "write_channels": "z.array(z.boolean())",
        "values": "z.array(z.boolean())",
    },
}

# Mapping for TypeScript interfaces
TS_TYPE_MAPPINGS = {
    "TEXT": "string | undefined",
    "TEXT NOT NULL": "string",
    "TEXT NOT NULL UNIQUE": "string",
    "INTEGER": "number | undefined",
    "INTEGER NOT NULL": "number",
    "SMALLINT": "number | undefined",
    "SMALLINT NOT NULL": "number",
    "DOUBLE PRECISION": "number | undefined",
    "DOUBLE PRECISION NOT NULL": "number",
    "NUMERIC": "number | undefined",
    "NUMERIC NOT NULL": "number",
    "BOOLEAN": "boolean | undefined",
    "BOOLEAN NOT NULL": "boolean",
    "TIMESTAMPTZ": "string | undefined",
    "TIMESTAMPTZ NOT NULL": "string",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "string",
    "JSONB": "Record<string, unknown> | undefined",
    "JSONB NOT NULL": "Record<string, unknown>",
    "UUID": "string | undefined",
    "UUID NOT NULL": "string",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "string",
}


def postgres_type_to_zod_type(pg_type: str) -> str:
    """
    Maps a PostgreSQL type string to a Zod type string.
    """
    normalized_pg_type = pg_type.upper().strip()
    return TYPE_MAPPINGS.get(normalized_pg_type, "z.any()")


def postgres_type_to_ts_type(pg_type: str) -> str:
    """
    Maps a PostgreSQL type string to a TypeScript type string.
    """
    normalized_pg_type = pg_type.upper().strip()
    return TS_TYPE_MAPPINGS.get(normalized_pg_type, "any")


def to_camel_case(snake_case_str: str) -> str:
    """Converts a snake_case string to camelCase."""
    components = snake_case_str.split("_")
    return components[0] + "".join(x.title() for x in components[1:])


def to_pascal_case(snake_case_str: str) -> str:
    """Converts a snake_case string to PascalCase."""
    return "".join(x.title() for x in snake_case_str.split("_"))


def generate_zod_models(schema_file: Path, output_file: Path):
    """
    Generates Zod schemas and TypeScript interfaces from a YAML schema definition.
    """
    logger.info(f"Starting Zod model generation from '{schema_file}'")

    if not schema_file.exists():
        logger.error(f"Schema file not found: {schema_file}")
        raise FileNotFoundError(f"Schema file not found: {schema_file}")

    with open(schema_file, "r") as f:
        raw_yaml_data = yaml.safe_load(f)

    models_code_lines: List[str] = [
        "// This file is auto-generated by tools/generate_zod_models.py",
        "// Do not edit this file manually.",
        "",
        "import { z } from 'zod';",
        "",
        "// Zod schemas for the database tables",
        "// These schemas define the data structure and validation rules.",
        "",
    ]

    interface_code_lines: List[str] = [
        "// TypeScript interfaces derived from the Zod schemas",
        "// These interfaces provide type safety for your data.",
        "",
    ]

    for table_name, table_def in raw_yaml_data.get("tables", {}).items():
        class_name = to_pascal_case(table_name)

        # Start Zod schema definition
        models_code_lines.append(
            f"export const {to_camel_case(table_name)}Schema = z.object({{"
        )

        # Start TypeScript interface definition
        interface_code_lines.append(f"export interface I{class_name} {{")

        columns = table_def.get("columns", {})
        is_special_table = table_name in SPECIAL_TABLE_LIST_FIELDS

        if is_special_table:
            # Handle special list-based tables
            special_fields = SPECIAL_TABLE_LIST_FIELDS[table_name]

            # Add the core fields from the schema
            for col_name, pg_type in columns.items():
                if col_name in special_fields:
                    continue  # Skip the indexed columns
                zod_type = postgres_type_to_zod_type(pg_type)
                ts_type = postgres_type_to_ts_type(pg_type)

                models_code_lines.append(f"    {to_camel_case(col_name)}: {zod_type},")
                interface_code_lines.append(
                    f"    {to_camel_case(col_name)}: {ts_type};"
                )

            # Add the list-based fields and the flattened fields
            for field_name, zod_type in special_fields.items():
                camel_field_name = to_camel_case(field_name)
                models_code_lines.append(f"    {camel_field_name}: {zod_type},")

                # Derive TypeScript type from Zod type
                ts_list_type = re.sub(r"z\.array\(z\.(\w+)\(\)\)", r"\1[]", zod_type)
                ts_list_type = ts_list_type.replace("boolean", "boolean").replace(
                    "number", "number"
                )
                interface_code_lines.append(f"    {camel_field_name}: {ts_list_type};")

                # Add the flattened fields
                for i in range(8):
                    flattened_field = f"{field_name}__{i}"
                    flattened_camel_field = to_camel_case(flattened_field)

                    zod_inner_type = (
                        zod_type.replace("z.array(", "").replace(")", "")
                        + ".optional()"
                    )
                    ts_inner_type = ts_list_type.replace("[]", " | undefined")

                    models_code_lines.append(
                        f"    {flattened_camel_field}: {zod_inner_type},"
                    )
                    interface_code_lines.append(
                        f"    {flattened_camel_field}: {ts_inner_type};"
                    )

        else:
            # Handle all other tables (non-special cases)
            for col_name, pg_type in columns.items():
                zod_type = postgres_type_to_zod_type(pg_type)
                ts_type = postgres_type_to_ts_type(pg_type)
                models_code_lines.append(f"    {to_camel_case(col_name)}: {zod_type},")
                interface_code_lines.append(
                    f"    {to_camel_case(col_name)}: {ts_type};"
                )

        # End Zod schema definition
        models_code_lines.append("});\n")

        # End TypeScript interface definition
        interface_code_lines.append("}\n")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(models_code_lines))
        f.write("\n---\n\n")  # Separator between Zod schemas and interfaces
        f.write("\n".join(interface_code_lines))

    logger.info(f"Successfully generated Zod models and interfaces to '{output_file}'.")


if __name__ == "__main__":
    try:
        generate_zod_models(Path(SCHEMA_FILE_PATH), Path(GENERATED_MODELS_FILE))
    except Exception as e:
        logger.error(f"Error during Zod model generation: {e}")
        sys.exit(1)
