# ./utilities/generate_models.py
import os
import yaml
from pathlib import Path
from typing import Dict, Any, List, Optional
from loguru import logger
from datetime import datetime
import sys

# Adjust sys.path to ensure 'backend' is recognized as a package root
current_dir = os.path.dirname(os.path.abspath(__file__))
backend_root = os.path.join(current_dir, "..")
sys.path.insert(0, backend_root)

# --- Configuration ---
# These paths are now configurable via environment variables or sensible defaults
SCHEMA_FILE_PATH = os.getenv(
    "SCHEMA_FILE_PATH", os.path.join(backend_root, "config", "schema.yml")
)
GENERATED_MODELS_DIR = os.getenv(
    "GENERATED_MODELS_DIR", os.path.join(backend_root, "api", "autogenerated")
)
GENERATED_MODELS_FILE = os.path.join(GENERATED_MODELS_DIR, "generated_models.py")

# --- Loguru Configuration ---
logger.remove()
logger.add(
    sys.stderr,
    level="INFO",
    format="{time} | {level} | {module}:{function}:{line} - {message}",
    colorize=True,
)

# --- PostgreSQL to Python Type Mappings ---
# NEW: Added mappings for UUID and TIMESTAMPTZ with defaults
TYPE_MAPPINGS = {
    "TEXT": "str",
    "TEXT NOT NULL": "str",
    "TEXT NOT NULL UNIQUE": "str",  # NEW: Specific mapping for unique text fields
    "INTEGER": "Optional[int]",
    "INTEGER NOT NULL": "int",
    "DOUBLE PRECISION": "Optional[float]",
    "DOUBLE PRECISION NOT NULL": "float",
    "NUMERIC": "Optional[float]",
    "NUMERIC NOT NULL": "float",
    "BOOLEAN": "Optional[bool]",
    "BOOLEAN NOT NULL": "bool",
    "TIMESTAMPTZ": "Optional[datetime]",
    "TIMESTAMPTZ NOT NULL": "datetime",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "datetime",  # NEW: Specific mapping
    "JSONB": "Optional[Dict[str, Any]]",
    "JSONB NOT NULL": "Dict[str, Any]",
    "UUID": "Optional[uuid.UUID]",
    "UUID NOT NULL": "uuid.UUID",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "uuid.UUID",  # NEW: Specific mapping
    # Add more mappings as needed
}


def postgres_type_to_python_type(pg_type: str) -> str:
    """
    Maps a PostgreSQL type string to a Python type string, handling common variations.
    """
    # Normalize common variations for lookup
    normalized_pg_type = pg_type.upper().strip()

    # Attempt exact match first for specific combinations
    python_type = TYPE_MAPPINGS.get(normalized_pg_type)
    if python_type:
        return python_type

    # Handle JSONB specifically
    if "JSONB" in normalized_pg_type:
        if "NOT NULL" in normalized_pg_type:
            return TYPE_MAPPINGS.get("JSONB NOT NULL", "Dict[str, Any]")
        return TYPE_MAPPINGS.get("JSONB", "Optional[Dict[str, Any]]")

    # Handle UUID specifically
    if "UUID" in normalized_pg_type:
        if "PRIMARY KEY DEFAULT" in normalized_pg_type:
            return TYPE_MAPPINGS.get(
                "UUID PRIMARY KEY DEFAULT gen_random_uuid()", "uuid.UUID"
            )
        if "NOT NULL" in normalized_pg_type:
            return TYPE_MAPPINGS.get("UUID NOT NULL", "uuid.UUID")
        return TYPE_MAPPINGS.get("UUID", "Optional[uuid.UUID]")

    # Handle TIMESTAMPTZ specifically
    if "TIMESTAMPTZ" in normalized_pg_type:
        if "DEFAULT NOW()" in normalized_pg_type:
            return TYPE_MAPPINGS.get("TIMESTAMPTZ NOT NULL DEFAULT NOW()", "datetime")
        if "NOT NULL" in normalized_pg_type:
            return TYPE_MAPPINGS.get("TIMESTAMPTZ NOT NULL", "datetime")
        return TYPE_MAPPINGS.get("TIMESTAMPTZ", "Optional[datetime]")

    # Fallback to direct lookup for simpler types
    python_type = TYPE_MAPPINGS.get(normalized_pg_type)
    if python_type:
        return python_type

    logger.warning(
        f"No Python type mapping found for PostgreSQL type '{pg_type}'. Defaulting to 'Any'."
    )
    return "Any"


def generate_pydantic_models(schema_file: Path, output_file: Path):
    """
    Generates Pydantic BaseModel classes from a YAML schema definition.
    """
    logger.info(f"Starting Pydantic model generation from '{schema_file}'")

    if not schema_file.exists():
        logger.error(f"Schema file not found: {schema_file}")
        raise FileNotFoundError(f"Schema file not found: {schema_file}")

    with open(schema_file, "r") as f:
        schema_config = yaml.safe_load(f)

    if not schema_config or "tables" not in schema_config:
        logger.error("Invalid schema.yml format. 'tables' key is missing.")
        raise ValueError("Invalid schema.yml format.")

    models_code_lines: List[str] = [
        "# This file is auto-generated by utilities/generate_models.py",
        "# Do not edit this file manually.",
        "",
        "from pydantic import BaseModel, Field",
        "from datetime import datetime",
        "from typing import Dict, Any, Optional",
        "import uuid # Needed for UUID type",  # NEW: Import uuid
        "",
        "# Dynamically created Pydantic models for each table",
        "",
        "DYNAMIC_TABLE_MODELS: Dict[str, type[BaseModel]] = {}",
        "",
    ]

    for table_name, table_def in schema_config["tables"].items():
        class_name = "".join([part.capitalize() for part in table_name.split("_")])
        models_code_lines.append(f"class {class_name}(BaseModel):")

        columns = table_def.get("columns", {})
        if not columns:
            models_code_lines.append("    pass # No columns defined")

        for col_name, pg_type in columns.items():
            python_type = postgres_type_to_python_type(pg_type)

            # Special handling for UUID and datetime fields with defaults
            if pg_type.upper().strip() == "UUID PRIMARY KEY DEFAULT gen_random_uuid()":
                models_code_lines.append(
                    f"    {col_name}: {python_type} = Field(default_factory=uuid.uuid4)"
                )
            elif pg_type.upper().strip() == "TIMESTAMPTZ NOT NULL DEFAULT NOW()":
                models_code_lines.append(
                    f"    {col_name}: {python_type} = Field(default_factory=datetime.utcnow)"
                )
            else:
                models_code_lines.append(f"    {col_name}: {python_type}")

        models_code_lines.append(
            f"\nDYNAMIC_TABLE_MODELS['{table_name}'] = {class_name}\n"
        )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(models_code_lines))

    logger.info(f"Successfully generated Pydantic models to '{output_file}'.")


if __name__ == "__main__":
    try:
        generate_pydantic_models(Path(SCHEMA_FILE_PATH), Path(GENERATED_MODELS_FILE))
    except Exception as e:
        logger.error(f"Error during Pydantic model generation: {e}")
        sys.exit(1)
