import asyncio, uuid

from fastapi import WebSocket
from loguru import logger
from typing import Dict, Any, Set, Optional, List, Type
from asyncpg.pool import Pool as AsyncpgPool
from datetime import datetime

from backend.api.schema_models import (
    LOADED_RAW_SCHEMA,
)  # To get table names for historical data
from common_models.autogenerated.database_models import (
    DYNAMIC_TABLE_MODELS,
    AutogeneratedPydanticModel
)

# --- Helper Function to Fetch Historical Data (refactored from get_data) ---
async def _fetch_historical_data(
    local_db_pool: AsyncpgPool,
    table_name: str,
    limit: int,
    order_by_column: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Fetches historical data from the local database.
    Assumes LOADED_RAW_SCHEMA and DYNAMIC_TABLE_MODELS are correctly initialized.
    Intelligently defaults to the table's hypertable_column for ordering if not provided or invalid.
    """
    if LOADED_RAW_SCHEMA is None or table_name not in LOADED_RAW_SCHEMA.tables:
        logger.warning(
            f"Historical fetch: Table '{table_name}' not found in loaded schema config."
        )
        return []

    if table_name not in DYNAMIC_TABLE_MODELS:
        logger.warning(f"Historical fetch: Table '{table_name}' not defined in models.")
        return []

    PydanticModel: Type[AutogeneratedPydanticModel] = DYNAMIC_TABLE_MODELS[table_name]
    table_def = LOADED_RAW_SCHEMA.tables[table_name]
    schema_columns = table_def.columns
    column_names = list(schema_columns.keys())

    if not column_names:
        logger.warning(
            f"Historical fetch: No columns defined for table '{table_name}'."
        )
        return []

    actual_order_by_column = order_by_column
    if actual_order_by_column not in schema_columns:
        if (
            table_def.hypertable_column
            and table_def.hypertable_column in schema_columns
        ):
            actual_order_by_column = table_def.hypertable_column
            if order_by_column:
                logger.warning(
                    f"Historical fetch: Order by column '{order_by_column}' not found in schema for table '{table_name}'. Defaulting to hypertable column '{actual_order_by_column}'."
                )
        else:
            if order_by_column:
                logger.warning(
                    f"Historical fetch: Order by column '{order_by_column}' not found, and no valid hypertable column defined for table '{table_name}'. No ordering applied."
                )
            else:
                logger.warning(
                    f"Historical fetch: No order_by_column provided, and no valid hypertable column defined for table '{table_name}'. No ordering applied."
                )
            actual_order_by_column = None

    select_columns = ", ".join(column_names)
    query = f"SELECT {select_columns} FROM {table_name}"
    params = []

    if actual_order_by_column:
        query += f" ORDER BY {actual_order_by_column} DESC"

    query += " LIMIT $1;"
    params.append(limit)

    result = []
    try:
        async with local_db_pool.acquire() as conn:
            logger.debug(f"Executing historical SQL: {query} with params: {params}")
            data_records = await conn.fetch(query, *params)

            for record in data_records:
                row_dict = {}
                for col_name in column_names:
                    value = record[col_name]
                    if isinstance(value, datetime):
                        row_dict[col_name] = (
                            value.isoformat(timespec="milliseconds").replace(
                                "+00:00", "Z"
                            )
                            if value.tzinfo
                            else value.isoformat(timespec="milliseconds") + "Z"
                        )
                    else:
                        row_dict[col_name] = value
                result.append(
                    PydanticModel.from_db_format(**row_dict).model_dump()
                    if hasattr(PydanticModel, "model_dump")
                    else PydanticModel(**row_dict).dict()
                )
        logger.info(
            f"Successfully fetched {len(result)} historical records from '{table_name}'."
        )
        return result
    except Exception as e:
        logger.error(f"Error fetching historical data from '{table_name}': {e}")
        return []

class Connection:
    """Represents a single active WebSocket connection and its subscriptions."""

    def __init__(self, websocket: WebSocket, client_id: str):
        self.websocket: WebSocket = websocket
        self.client_id: str = client_id
        self.queue: asyncio.Queue = asyncio.Queue()  # Personal queue for this client
        self.subscriptions: Set[str] = (
            set()
        )  # Set of table_names this client is subscribed to
        logger.info(f"Connection {self.client_id} initialized.")

    async def send_json(self, data: Dict[str, Any]):
        """Sends JSON data over the WebSocket."""
        await self.websocket.send_json(data)
        logger.debug(f"Connection {self.client_id}: Sent data over WebSocket.")

    async def receive_json(self) -> Dict[str, Any]:
        """Receives JSON data over the WebSocket."""
        data = await self.websocket.receive_json()
        logger.debug(f"Connection {self.client_id}: Received data from WebSocket.")
        return data

    def subscribe(self, table_name: str):
        """Subscribes the client to a table."""
        self.subscriptions.add(table_name)
        logger.info(f"Connection {self.client_id} subscribed to '{table_name}'.")

    def unsubscribe(self, table_name: str):
        """Unsubscribes the client from a table."""
        self.subscriptions.discard(table_name)
        logger.info(f"Connection {self.client_id} unsubscribed from '{table_name}'.")

    @property
    def is_subscribed(self, table_name: str) -> bool:
        """Checks if the client is subscribed to a given table."""
        return table_name in self.subscriptions


class SubscriptionManager:
    """Manages all active WebSocket connections and their subscriptions."""

    def __init__(self):
        self.active_connections: Dict[str, Connection] = {}  # {client_id: Connection}
        self.table_subscribers: Dict[str, Set[str]] = (
            {}
        )  # {table_name: {client_id, ...}}
        logger.info("SubscriptionManager initialized.")

    async def connect(self, websocket: WebSocket) -> Connection:
        """Handles a new WebSocket connection."""
        client_id = str(uuid.uuid4())
        connection = Connection(websocket, client_id)
        self.active_connections[client_id] = connection
        logger.info(
            f"Client {client_id} connected. Total active connections: {len(self.active_connections)}"
        )
        return connection

    async def disconnect(self, client_id: str):
        """Handles a WebSocket disconnection."""
        if client_id in self.active_connections:
            connection = self.active_connections.pop(client_id)
            # Remove client from all tables they were subscribed to
            for table_name in connection.subscriptions:
                self.table_subscribers.get(table_name, set()).discard(client_id)
                if not self.table_subscribers[table_name]:
                    del self.table_subscribers[table_name]  # Clean up empty sets
            logger.info(
                f"Client {client_id} disconnected. Remaining active connections: {len(self.active_connections)}"
            )

    async def subscribe(
        self,
        client_id: str,
        table_name: str,
        send_historical: bool = False,
        historical_limit: int = 100,
    ):
        """Subscribes a client to a specific table."""
        if client_id not in self.active_connections:
            logger.warning(f"Subscribe failed: Client {client_id} not found.")
            return

        connection = self.active_connections[client_id]
        if table_name not in LOADED_RAW_SCHEMA.tables:
            logger.warning(
                f"Client {client_id}: Attempted to subscribe to unknown table '{table_name}'."
            )
            await connection.send_json(
                {
                    "type": "error",
                    "message": f"Table '{table_name}' not found or not defined in schema.",
                }
            )
            return

        connection.subscribe(table_name)
        self.table_subscribers.setdefault(table_name, set()).add(client_id)
        logger.info(f"Client {client_id} successfully subscribed to '{table_name}'.")

        # Optionally send historical data upon subscription
        if send_historical:
            logger.info(
                f"Client {client_id}: Fetching historical data for {table_name} (limit={historical_limit})..."
            )
            local_db_pool = (
                connection.websocket.app.state.local_db_pool
            )  # Access pool from app state
            historical_data_raw = await _fetch_historical_data(
                local_db_pool, table_name, historical_limit
            )

            serializable_historical_data = []
            for record in historical_data_raw:
                serializable_record = {
                    key: (
                        value.isoformat(timespec="milliseconds").replace("+00:00", "Z")
                        if isinstance(value, datetime.datetime)
                        else value
                    )
                    for key, value in record.items()
                }
                serializable_historical_data.append(serializable_record)

            await connection.send_json(
                {
                    "type": "historical",
                    "table": table_name,
                    "data": serializable_historical_data,
                }
            )
            logger.info(
                f"Client {client_id}: Sent {len(serializable_historical_data)} historical records for {table_name}."
            )

        await connection.send_json(
            {"type": "status", "table": table_name, "status": "subscribed"}
        )

    async def unsubscribe(self, client_id: str, table_name: str):
        """Unsubscribes a client from a specific table."""
        if client_id not in self.active_connections:
            logger.warning(f"Unsubscribe failed: Client {client_id} not found.")
            return

        connection = self.active_connections[client_id]
        connection.unsubscribe(table_name)
        self.table_subscribers.get(table_name, set()).discard(client_id)
        if not self.table_subscribers[table_name]:
            del self.table_subscribers[table_name]  # Clean up empty sets
        logger.info(
            f"Client {client_id} successfully unsubscribed from '{table_name}'."
        )
        await connection.send_json(
            {"type": "status", "table": table_name, "status": "unsubscribed"}
        )

    async def publish(self, table_name: str, message: Dict[str, Any]):
        """Publishes a message to all clients subscribed to a specific table."""
        if table_name in self.table_subscribers:
            for client_id in list(
                self.table_subscribers[table_name]
            ):  # Iterate over a copy to avoid issues if clients disconnect
                connection = self.active_connections.get(client_id)
                if connection:
                    try:
                        await connection.queue.put(message)
                        logger.debug(
                            f"Published message for '{table_name}' to client {client_id}'s queue."
                        )
                    except Exception as e:
                        logger.error(
                            f"Error publishing to client {client_id} for table '{table_name}': {e}"
                        )
                        # Consider removing client if their queue causes consistent errors
                else:
                    logger.warning(
                        f"Client {client_id} for table '{table_name}' not found in active connections during publish. Cleaning up."
                    )
                    self.table_subscribers[table_name].discard(client_id)