# RA Backend Routers
# Developed by R2 Labs

import secrets, time, asyncio, random, subprocess, re, httpx, os, time

from fastapi import WebSocket, APIRouter, Body
from datetime import datetime
from typing import List, Dict, Callable, Literal
from loguru import logger

from common_models.models import NetworkInterfaces
from common_models.autogenerated.system_models import ApiResponse, HostServicesError, NetworkInterfaceDefinition
from common_models.system_utilities import is_running_in_docker

system_router = APIRouter(tags=["System"])


###############################################################################
################################### SYSTEM ####################################
###############################################################################

SIMULATED_NETWORK_SSID = "network_a"


def get_host_ip() -> str:
    if is_running_in_docker():
        default_route = subprocess.check_output(
            ["ip", "route", "show", "default"]
        ).decode()
        host_ip = re.findall(
            r"default via \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b", default_route
        )[0].replace("default via ", "")
        return host_ip
    else:
        return "localhost"


def execute_host_service_api_request(
    endpoint: str, method: Literal["GET", "POST"] = "GET"
) -> ApiResponse:
    try:
        host_ip = get_host_ip()
        host_port = int(os.environ.get("HOST_SERVICES_API_PORT", 8001))
        http_client = httpx.Client(timeout=15)
        if method == "GET":
            response = http_client.get(f"http://{host_ip}:{host_port}/{endpoint}")
        elif method == "POST":
            response = http_client.post(f"http://{host_ip}:{host_port}/{endpoint}")
        else:
            return ApiResponse(
                success=False, message=f"Unrecognized HTTP method {method}"
            )

        return ApiResponse(**response.json())
    except Exception as e:
        return ApiResponse(
            # error=True,
            success=False,
            message=f"Host services API error: {e}",
            data=HostServicesError(
                description=f"Error calling host service endpoint /{endpoint}",
                details=f"{e}",
            ).model_dump(),
        )


@system_router.get("/ssids", response_model=ApiResponse)
async def get_ssid() -> ApiResponse:
    if os.environ.get("SIMULATE_WIFI_CONNECTIONS", "false").lower() == "true":
        ssids = ["network_a", "network_b", "network_c"]
        time.sleep(2)
        return ApiResponse(success=True, data=ssids)
    else:
        return execute_host_service_api_request(endpoint="scan")


@system_router.get("/connected_ssids", response_model=ApiResponse)
def current_ssid() -> ApiResponse:
    if os.environ.get("SIMULATE_WIFI_CONNECTIONS", "false").lower() == "true":
        return ApiResponse(success=True, message='', data={"ssid": SIMULATED_NETWORK_SSID})
    else:
        return execute_host_service_api_request(endpoint="connected_ssids")


@system_router.get("/wifi_ip", response_model=ApiResponse)
def wifi_ip() -> ApiResponse:
    if os.environ.get("SIMULATE_WIFI_CONNECTIONS", "false").lower() == "true":
        # return APIResponse(error=False, data="0.0.0.0")
        return ApiResponse(success=True, data="0.0.0.0")
    else:
        return execute_host_service_api_request(endpoint="wifi_ip")

@system_router.get("/interfaces", response_model=ApiResponse)
def get_interfaces() -> ApiResponse:
    return execute_host_service_api_request(endpoint="interfaces")

@system_router.get("/interface_ip", response_model=ApiResponse)
def interface_ip(interface_name: str) -> ApiResponse:
    if os.environ.get("SIMULATE_WIFI_CONNECTIONS", "false").lower() == "true":
        return ApiResponse(success=True, message="Got interface IP", data="0.0.0.0")
    else:
        network_interfaces_response = execute_host_service_api_request(endpoint="interfaces")
        network_interfaces = NetworkInterfaces.model_validate(network_interfaces_response.data)

        interface_ip = network_interfaces.get_interface_ip(interface_name=interface_name)
        
        if interface_name in network_interfaces.interface_names:
            return ApiResponse(
                success=True,
                message='',
                data=interface_ip
            )
        else:
            return ApiResponse(success=False, message=f"No network interface named {interface_name} found", data=None)

@system_router.post("/connect_wifi", response_model=ApiResponse)
async def connect_to_wifi_network(ssid: str, password: str) -> ApiResponse:
    global SIMULATED_NETWORK_SSID

    if os.environ.get("SIMULATE_WIFI_CONNECTIONS", "false").lower() == "true":
        time.sleep(3)
        SIMULATED_NETWORK_SSID = ssid
        return ApiResponse(success=True, message=f"Connected to SSID {ssid}")
    else:
        try:
            return execute_host_service_api_request(
                endpoint=f"connect_wifi?ssid={ssid}&password={password}", method="POST"
            )

        except Exception as e:
            return ApiResponse(success=False, message=f"{e}")


