'use client';

import { AITrainingContainer } from '@/lib/components/client_components/AITrainingContainer';
import { SimplifiedDashboardHeaderContainer } from '@/lib/components/server_components/SimplifiedDashboardHeaderContainer';
import { trainingMetadataType } from '@/lib/models/autogenerated/configuration_models';
import React from 'react';
import { DashboardHeaderContainerProps } from '../models/dashboard_types';

interface AITrainingPanelProps extends DashboardHeaderContainerProps {
    metadata: trainingMetadataType;
}
export const AITrainingPanel: React.FC<AITrainingPanelProps> = ({
    className,
    metadata,
}) => {
    const { variant = 'compact' } = metadata;

    return (
        <SimplifiedDashboardHeaderContainer
            title={`AI Training`}
            icon_path={'/icons/device.svg'}
            className={className || ''}
        >
            <div className="w-full h-full bg-gray-900">
                {variant === 'compact' && (
                    <AITrainingContainer
                        layout="compact"
                        showProjects={true}
                        showJobs={true}
                        showModels={false}
                    />
                )}

                {variant === 'simple' && (
                    <AITrainingContainer
                        layout="full"
                        showProjects={true}
                        showJobs={false}
                        showModels={false}
                    />
                )}

                {variant === 'full' && (
                    <AITrainingContainer
                        layout="full"
                        showProjects={true}
                        showJobs={true}
                        showModels={true}
                    />
                )}
            </div>
        </SimplifiedDashboardHeaderContainer>
    );
};

// Export different variations
export const CompactAITrainingPanel = (props: AITrainingPanelProps) => {
    return (
        <AITrainingPanel
            {...props}
            metadata={{ ...props.metadata, variant: 'compact' }}
        />
    );
};

export const SimpleAITrainingPanel = (props: AITrainingPanelProps) => {
    return (
        <AITrainingPanel
            {...props}
            metadata={{ ...props.metadata, variant: 'simple' }}
        />
    );
};
