// Frontend Web Application for RA Products
// Developed by R2 Labs

'use client';

import CameraStreamContainer from '@/lib/components/client_components/CameraStreamContainer';
import { SimplifiedDashboardHeaderContainer } from '@/lib/components/server_components/SimplifiedDashboardHeaderContainer';
import { cameraMetadataType } from '@/lib/models/autogenerated/configuration_models';
import { DashboardHeaderContainerProps } from '@/lib/models/dashboard_types';

// Export different variations
interface CameraStreamPanelProps extends DashboardHeaderContainerProps {
    metadata: cameraMetadataType;
    variant?: 'full' | 'compact' | 'simple';
    cameraId?: string;
}

// export const CameraStreamPanel = (props: {
//     id: string;
//     className?: string;
//     fill_tile_callback?: Dispatch<SetStateAction<string>>;
//     force_expanded?: boolean;
//     variant?: 'full' | 'compact' | 'simple';
//     cameraId?: string;
// }) => {
export const CameraStreamPanel: React.FC<CameraStreamPanelProps> = ({
    className,
    metadata,
    variant = 'full',
    cameraId,
}) => {
    //const { variant = 'full', cameraId } = props;

    return (
        <SimplifiedDashboardHeaderContainer
            title={`Camera ${cameraId || 'Stream'}`}
            icon_path={'/icons/device.svg'}
            className={className || ''}
            // fill_tile_id={props.id}
            // fill_tile_callback={props.fill_tile_callback}
        >
            <div className="w-full h-full bg-gray-900">
                {variant === 'compact' && (
                    <CameraStreamContainer
                        layout="compact"
                        showControls={true}
                        showSelection={true}
                        cameraId={cameraId}
                    />
                )}

                {variant === 'simple' && (
                    <CameraStreamContainer
                        layout="full"
                        showControls={false}
                        showSelection={false}
                        cameraId={cameraId}
                    />
                )}

                {variant === 'full' && (
                    <CameraStreamContainer
                        layout="full"
                        showControls={true}
                        showSelection={true}
                        cameraId={cameraId}
                    />
                )}
            </div>
        </SimplifiedDashboardHeaderContainer>
    );
};

export const CompactCameraStreamPanel = (
    props: Omit<CameraStreamPanelProps, 'variant'>
) => {
    return <CameraStreamPanel {...props} variant="compact" />;
};

export const SimpleCameraStreamPanel = (
    props: Omit<CameraStreamPanelProps, 'variant'>
) => {
    return <CameraStreamPanel {...props} variant="simple" />;
};
