// Frontend Web Application for RA Products
// Developed by R2 Labs

'use client';

import { DashboardHeaderContainer } from '@/lib/components/client_components/DashboardHeaderContainer';
import { useEffect, useState } from 'react';
import { DashboardHeaderContainerProps } from '../models/dashboard_types';
import { cameraMetadataType } from '@/lib/models/autogenerated/configuration_models';

interface CameraStreamPanelInterface extends DashboardHeaderContainerProps {
    metadata: cameraMetadataType;
}

export function CameraStreamPanel<CameraStreamPanelInterface>(props: {
    id: string;
    className?: string;
    fill_tile_callback?: React.Dispatch<React.SetStateAction<string>>;
    force_expanded?: boolean;
    title?: string;
    cameraId?: string;
}) {
    const cameraId = props.cameraId || 'camera0';
    const streamUrl = `/api/camera/${cameraId}`;
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    // Camera connection states
    const [isConnected, setIsConnected] = useState<boolean | null>(null); // null = unknown, true = connected, false = disconnected
    const [isStreaming, setIsStreaming] = useState(false);
    const [checkingConnection, setCheckingConnection] = useState(false);

    // Control states
    const [isRecording, setIsRecording] = useState(false);
    const [modelEnabled, setModelEnabled] = useState(false);
    const [isCapturing, setIsCapturing] = useState(false);

    // Check camera connection status on mount
    useEffect(() => {
        checkCameraConnection();
    }, [cameraId]);

    const checkCameraConnection = async () => {
        setCheckingConnection(true);
        try {
            // Use the modified route with status action
            const response = await fetch(
                `/api/camera/${cameraId}?action=status`
            );
            const data = await response.json();

            console.log(`Camera ${cameraId} status check:`, data);

            if (response.ok) {
                setIsConnected(data.connected);
                setError(null);
            } else {
                setIsConnected(false);
                setError(data.message || 'Failed to check camera status');
            }
        } catch (error) {
            console.error('Failed to check camera connection:', error);
            setIsConnected(false);
            setError('Unable to communicate with camera service');
        } finally {
            setCheckingConnection(false);
        }
    };

    const startStream = async () => {
        if (!isConnected) {
            setError('Camera not connected');
            return;
        }

        setLoading(true);
        setError(null);
        setIsStreaming(true);

        setTimeout(() => setLoading(false), 2000);
    };

    const stopStream = async () => {
        setIsStreaming(false);
        setLoading(false);
        setError(null);
    };

    const handleImageLoad = () => {
        setLoading(false);
    };

    const handleImageError = () => {
        setLoading(false);
        setError('Failed to load camera stream');
        setIsStreaming(false);
    };

    const handleCaptureFrame = async () => {
        if (!isStreaming) return;

        setIsCapturing(true);
        try {
            console.log(`Capturing frame from ${cameraId}`);
            // TODO: Implement capture logic
            await new Promise((resolve) => setTimeout(resolve, 500));
        } catch (error) {
            console.error('Failed to capture frame:', error);
        } finally {
            setIsCapturing(false);
        }
    };

    const handleToggleModel = async () => {
        if (!isStreaming) return;

        try {
            console.log(
                `${modelEnabled ? 'Disabling' : 'Enabling'} AI model for ${cameraId}`
            );
            // TODO: Implement model toggle
            setModelEnabled(!modelEnabled);
        } catch (error) {
            console.error('Failed to toggle model:', error);
        }
    };

    const handleToggleRecording = async () => {
        if (!isStreaming) return;

        try {
            console.log(
                `${isRecording ? 'Stopping' : 'Starting'} recording for ${cameraId}`
            );
            // TODO: Implement recording toggle
            setIsRecording(!isRecording);
        } catch (error) {
            console.error('Failed to toggle recording:', error);
        }
    };

    // Get connection status color and text
    const getConnectionStatus = () => {
        if (checkingConnection)
            return {
                color: 'text-yellow-400',
                text: 'Checking...',
                icon: '🔄',
            };
        if (isConnected === null)
            return { color: 'text-gray-400', text: 'Unknown', icon: '❓' };
        if (isConnected)
            return { color: 'text-green-400', text: 'Connected', icon: '🟢' };
        return { color: 'text-red-400', text: 'Disconnected', icon: '🔴' };
    };

    const connectionStatus = getConnectionStatus();

    return (
        <DashboardHeaderContainer
            header_text={(`${props.title ?? 'Camera'} Stream ${cameraId.slice(-1)}`).toUpperCase()}
            icon_path={'/icons/device.svg'}
            className={props.className || ''}
            fill_tile_id={props.id}
            fill_tile_callback={props.fill_tile_callback}
        >
            <div className="w-full h-full flex flex-col">
                {/* Camera Stream or Connection UI */}
                <div className="flex-1 flex items-center justify-center relative">
                    {!isConnected ? (
                        /* Camera Not Connected */
                        <div className="text-center text-gray-400">
                            <div className="text-4xl mb-4">📷</div>
                            <p className="text-lg mb-2">
                                Camera {cameraId.slice(-1)}
                            </p>
                            <p
                                className={`text-sm mb-4 ${connectionStatus.color}`}
                            >
                                {connectionStatus.icon} {connectionStatus.text}
                            </p>
                            {error && (
                                <p className="text-red-400 text-xs mb-4">
                                    {error}
                                </p>
                            )}
                            <button
                                onClick={checkCameraConnection}
                                disabled={checkingConnection}
                                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 text-white rounded text-sm"
                            >
                                {checkingConnection
                                    ? 'Checking...'
                                    : 'Check Connection'}
                            </button>
                        </div>
                    ) : !isStreaming ? (
                        /* Camera Connected but Not Streaming */
                        <div className="text-center text-gray-400">
                            <div className="text-4xl mb-4">📷</div>
                            <p className="text-lg mb-2">
                                Camera {cameraId.slice(-1)} Ready
                            </p>
                            <p
                                className={`text-sm mb-4 ${connectionStatus.color}`}
                            >
                                {connectionStatus.icon} {connectionStatus.text}
                            </p>
                            <button
                                onClick={startStream}
                                disabled={loading}
                                className="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 text-white rounded text-sm"
                            >
                                {loading ? 'Starting...' : '▶️ Start Stream'}
                            </button>
                        </div>
                    ) : (
                        /* Camera Streaming */
                        <>
                            <img
                                src={streamUrl}
                                alt={`Camera ${cameraId} stream`}
                                className="max-w-full max-h-full object-contain"
                                style={{ imageRendering: 'auto' }}
                                onLoad={handleImageLoad}
                                onError={handleImageError}
                            />

                            {loading && (
                                <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50">
                                    <div className="text-white text-center">
                                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-white mx-auto mb-2"></div>
                                        <p>Loading stream...</p>
                                    </div>
                                </div>
                            )}

                            {error && (
                                <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-75">
                                    <div className="text-center text-red-400">
                                        <p>Stream Error:</p>
                                        <p className="text-sm">{error}</p>
                                        <button
                                            onClick={() => {
                                                setError(null);
                                                startStream();
                                            }}
                                            className="mt-2 px-2 py-1 bg-blue-600 text-white rounded text-xs"
                                        >
                                            Retry
                                        </button>
                                    </div>
                                </div>
                            )}
                        </>
                    )}
                </div>

                {/* Control Buttons */}
                <div className="p-3 bg-gray-800 border-t border-gray-600">
                    {/* Connection Controls */}
                    <div className="flex gap-2 justify-center mb-2">
                        <button
                            onClick={isStreaming ? stopStream : startStream}
                            disabled={!isConnected || loading}
                            className={`
                px-3 py-1 text-xs font-medium rounded-md transition-colors
                ${
                    isStreaming
                        ? 'bg-red-600 hover:bg-red-700 text-white'
                        : 'bg-green-600 hover:bg-green-700 text-white'
                }
                disabled:opacity-50 disabled:cursor-not-allowed
              `}
                        >
                            {isStreaming ? '⏹️ Stop' : '▶️ Start'}
                        </button>

                        <button
                            onClick={checkCameraConnection}
                            disabled={checkingConnection}
                            className="px-3 py-1 bg-gray-600 hover:bg-gray-700 disabled:bg-gray-700 text-white rounded text-xs"
                        >
                            {checkingConnection ? '🔄' : '🔍'} Check
                        </button>
                    </div>

                    {/* Camera Controls - Only show when streaming */}
                    {isStreaming && (
                        <>
                            <div className="flex gap-2 justify-center">
                                <button
                                    onClick={handleCaptureFrame}
                                    disabled={isCapturing || !isStreaming}
                                    className="px-3 py-2 text-xs font-medium rounded-md transition-colors bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:opacity-50 text-white"
                                >
                                    {isCapturing
                                        ? '📸 Capturing...'
                                        : '📸 Capture'}
                                </button>

                                <button
                                    onClick={handleToggleModel}
                                    disabled={!isStreaming}
                                    className={`px-3 py-2 text-xs font-medium rounded-md transition-colors ${
                                        modelEnabled
                                            ? 'bg-green-600 hover:bg-green-700'
                                            : 'bg-gray-600 hover:bg-gray-700'
                                    } text-white disabled:opacity-50`}
                                >
                                    🤖 AI {modelEnabled ? 'ON' : 'OFF'}
                                </button>

                                <button
                                    onClick={handleToggleRecording}
                                    disabled={!isStreaming}
                                    className={`px-3 py-2 text-xs font-medium rounded-md transition-colors ${
                                        isRecording
                                            ? 'bg-red-600 hover:bg-red-700 animate-pulse'
                                            : 'bg-gray-600 hover:bg-gray-700'
                                    } text-white disabled:opacity-50`}
                                >
                                    {isRecording ? '⏹️ Stop Rec' : '🔴 Record'}
                                </button>
                            </div>

                            {/* Status indicators */}
                            <div className="flex gap-4 justify-center mt-2 text-xs text-gray-400">
                                <span className={connectionStatus.color}>
                                    {connectionStatus.icon}{' '}
                                    {connectionStatus.text}
                                </span>
                                {isRecording && (
                                    <span className="text-red-400 animate-pulse">
                                        ● Recording
                                    </span>
                                )}
                                {modelEnabled && (
                                    <span className="text-green-400">
                                        🤖 AI Active
                                    </span>
                                )}
                            </div>
                        </>
                    )}
                </div>
            </div>
        </DashboardHeaderContainer>
    );
}
