import { visionStatisticsMetadataType } from "@/lib/models/autogenerated/configuration_models";
import { DashboardHeaderContainerProps } from "@/lib/models/dashboard_types";
import { DashboardHeaderContainer } from "../components/client_components/DashboardHeaderContainer";

interface TestInferencePanelInterface extends DashboardHeaderContainerProps {
    metadata: visionStatisticsMetadataType
}

export const TestStatisticsPanel: React.FC<TestInferencePanelInterface> = (
    {
        title,
        metadata
    }

) => {
    return (
        <DashboardHeaderContainer
            header_text={title}
            icon_path="/icons/gears.svg"
            fill_tile_id={title}
        >
            <div>
                <p>STATISTICS</p>
                <p>{JSON.stringify(metadata)}</p>
            </div>
        </DashboardHeaderContainer>
    )
}