import { SimplifiedDashboardHeaderContainer } from '@/lib/components/server_components/SimplifiedDashboardHeaderContainer';
import { visionStatisticsMetadataType } from '@/lib/models/autogenerated/configuration_models';
import { DashboardHeaderContainerProps } from '@/lib/models/dashboard_types';

interface TestInferencePanelInterface extends DashboardHeaderContainerProps {
    metadata: visionStatisticsMetadataType;
}

export const TestStatisticsPanel: React.FC<TestInferencePanelInterface> = ({
    title,
    metadata,
}) => {
    return (
        <SimplifiedDashboardHeaderContainer
            id={title}
            title={title}
            icon_path="/icons/gears.svg"
            isLoading={false}
        >
            <div>
                <p>STATISTICS</p>
                <p>{JSON.stringify(metadata)}</p>
            </div>
        </SimplifiedDashboardHeaderContainer>
    );
};
