version: "3.8"
services:
  mongo:
    image: mongo
    container_name: ra_database
    hostname: ra_database
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
    volumes:
      - $HOST_DB_STORAGE_PATH:/data/db
    ports:
      - 27017:27017
    networks:
      backend:
        ipv4_address: 172.23.0.51
    restart: unless-stopped
  
  mongo_ui:
    image: samueltallet/mongodb-php-gui
    container_name: ra_database_ui
    hostname: ra_database_ui
    ports:
      - 5001:5000
    extra_hosts:
      - "localhost:172.17.0.1"
    networks:
      backend:
        ipv4_address: 172.23.0.52
    restart: unless-stopped

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24