// Frontend Web Application for RA Products
// Developed by R2 Labs

'use client';

import { DashboardContext } from '@/lib/components/client_components/DashboardContextWrapper';
import { useContext, useEffect, useState } from 'react'; // useState is still used for internal component state, not alerts
import { digitalOutData, digitalOutDataSchema, digitalOutDataBatch, digitalOutDataBatchSchema } from '@/lib/models/autogenerated/generated_models';
import { z } from 'zod';

import {
    UiConfig,
    UiConfigApiResponse,
    uiConfigApiResponseSchema,
    DEFAULT_UI_CONFIG,
} from '@/lib/models/ui_configuration';
import { fetchFromBackendApi } from '@/lib/utils/timeoutFetch';
import { useAlert } from '@/lib/components/client_components/AlertContext'; // NEW: Import useAlert hook
import { AlertType } from '@/lib/components/client_components/AlertPopup';

export const SimpleDataUpdater = () => {
    const { setDashboardContext } = useContext(DashboardContext);
    const { showAlert } = useAlert(); // NEW: Use the showAlert function from context

    useEffect(() => {
        // Define an async function to handle the API call and configuration logic
        const fetchConfig = async () => {
            let configToSet: UiConfig = DEFAULT_UI_CONFIG; // Start with default config
            let message: string | null = null; // Message for potential alerts
            let type: AlertType = 'warning'; // Default alert type

            try {
                const apiResponse: UiConfigApiResponse = await fetchFromBackendApi<UiConfigApiResponse>(
                    '/api/backend/ui/config/abc',
                    uiConfigApiResponseSchema // Pass the schema for the *entire API response*
                );
                
                // If we reach here, apiResponse is a valid UiConfigApiResponse object.
                // Now, check if the actual config_data is present and valid within this response.
                if (apiResponse && apiResponse.config_data) {
                    configToSet = apiResponse.config_data;
                    message = `UI configuration successfully loaded. Client ID: ${apiResponse.client_id}, Last Updated: ${new Date(apiResponse.last_updated).toLocaleString()}.`;
                    type = 'success'; // Set alert type to success
                    console.log(`Got UI configuration: ${JSON.stringify(configToSet)}`);
                } 
                // Scenario 2: API call successful, but no config_data returned (e.g., config not found in DB)
                // This means apiResponse was valid, but its config_data field was empty or null.
                else if (apiResponse && !apiResponse.config_data) {
                    message = "No UI configuration detected in the backend. Default configuration has been loaded.";
                    type = 'warning'; // Set alert type to warning
                    console.warn(message);
                    // configToSet is already DEFAULT_UI_CONFIG
                }

            } catch (err: any) {
                if (err.message && err.message.includes('API returned a failure:')) {
                    message = `No UI configuration detected in the backend. Default configuration has been loaded. Error: ${err.message}`;
                    type = 'warning'; // Still a warning if no config, even if API reported failure
                    console.warn(message);
                } else {
                    message = `Failed to fetch UI configuration from the backend. Default configuration has been loaded. Error: ${err.message || String(err)}.`;
                    type = 'error'; // Set alert type to error for general failures
                    console.error(`Error loading UI configuration: ${err}`);
                }
                // configToSet remains DEFAULT_UI_CONFIG in all catch scenarios.
            } finally {
                // Always set a configuration (either fetched or default)
                setDashboardContext({
                    payload: { configuration: configToSet },
                    type: 'ui_config/set',
                });
                if (message) {
                    showAlert(message, type, undefined, 'Configuration Alert:'); // NEW: Call showAlert from context
                }
            }
        };

        // const fetchFromDatabase = async () => {
        //     // type a = z.infer<typeof z.array(digitalOutData)>
        //     try {
        //         const apiResponse = await fetchFromBackendApi<
        //             digitalOutDataBatch
        //         >(
        //             '/api/backend/database/get_data/digital_out_data?limit=10',
        //             digitalOutDataBatchSchema // Pass the schema for the *entire API response*
        //         );
        //         let b = 5;
        //     } catch (err: any) {
        //         if (
        //             err.message &&
        //             err.message.includes('API returned a failure:')
        //         ) {
        //             let a = 5;
        //         }
        //         // configToSet remains DEFAULT_UI_CONFIG in all catch scenarios.
        //     }
        // }

        // Call the async function when the component mounts
        fetchConfig();
        // fetchFromDatabase();
    // }, [setDashboardContext, showAlert]); // Dependency array includes showAlert
    }, [setDashboardContext]); // Dependency array includes showAlert

    // REMOVED: All alert-related state (alertState, isAlertDismissing) and effects (auto-dismissal useEffect)
    // REMOVED: handleDismissAlert function

    return <></>; // This component no longer renders the alert UI directly
};

