// Frontend Web Application for RA Products
// Developed by R2 Labs

'use client';

import { DashboardContext } from '@/lib/components/client_components/DashboardContextWrapper';
import { useContext, useEffect } from 'react'; // useState is still used for internal component state, not alerts

import { useAlert } from '@/lib/components/client_components/AlertContext'; // NEW: Import useAlert hook
import { AlertType } from '@/lib/components/client_components/AlertPopup';
import {
    availableTables,
    availableTablesSchema,
} from '@/lib/models/api_models';
import {
    fullConfiguration,
    fullConfigurationType,
    ioConfigurationType,
    opcConfigurationType,
    uiConfigurationType,
} from '@/lib/models/autogenerated/configuration_models';
import {
    DEFAULT_IO_CONFIG,
    DEFAULT_OPC_CONFIG,
    DEFAULT_UI_CONFIG,
} from '@/lib/models/defaults';
import { getUsernameForConfiguration } from '@/lib/utils/configUserName';
import {
    asyncExponentialBackoffRetry,
    fetchFromBackendApi,
} from '@/lib/utils/timeoutFetch';
import { logMessage } from '@/lib/utils/utilities';
import { useSession } from 'next-auth/react';

export const DataUpdater = () => {
    const { setDashboardContext } = useContext(DashboardContext);
    const { showAlert } = useAlert(); // NEW: Use the showAlert function from context
    const { data: session } = useSession();

    useEffect(() => {
        const fetchTables = async () => {
            let message: string | null = null; // Message for potential alerts
            let type: AlertType = 'warning'; // Default alert type

            try {
                const apiResponse: availableTables =
                    await asyncExponentialBackoffRetry(() =>
                        fetchFromBackendApi<availableTables>(
                            '/api/backend/status/tables',
                            'GET',
                            null,
                            availableTablesSchema
                        )
                    );

                if (apiResponse) {
                    message = `Got available tables: ${apiResponse.map((table_def) => `${table_def.table_name}`).join(', ')}`;
                    type = 'success';
                    logMessage(message, 'info');

                    setDashboardContext({
                        payload: { tables: apiResponse },
                        type: 'database/tables/set',
                    });
                } else {
                    message = `Backend has no available database tables`;
                    type = 'warning';
                    logMessage(message, 'warning');
                }
            } catch (err: any) {
                message = `Failed to fetch available database tables from the backend after multiple retries. Error: ${err.message || String(err)}.`;
                type = 'error';
                logMessage(message, type);
                // console.error(`Final error loading UI configuration: ${err}`);
            } finally {
                if (message) {
                    showAlert(message, type, 'Database Alert');
                }
            }
        };

        const fetchConfigs = async () => {
            let uiConfigToSet: uiConfigurationType = DEFAULT_UI_CONFIG; // Start with default config
            let ioConfigToSet: ioConfigurationType = DEFAULT_IO_CONFIG; // Start with default config
            let opcConfigToSet: opcConfigurationType = DEFAULT_OPC_CONFIG; // Start with default config
            let message: string | null = null; // Message for potential alerts
            let type: AlertType = 'warning'; // Default alert type

            try {
                const apiResponse: fullConfigurationType =
                    await asyncExponentialBackoffRetry(() =>
                        fetchFromBackendApi<fullConfigurationType>(
                            `/api/backend/ui/full_config/${getUsernameForConfiguration(session)}`,
                            'GET',
                            null,
                            fullConfiguration
                        )
                    );

                if (apiResponse) {
                    if (apiResponse.io_configuration) {
                        ioConfigToSet = apiResponse.io_configuration;
                        message = `IO configuration successfully loaded. Client ID: ${apiResponse.client_id}, Last Updated: ${new Date(apiResponse.io_configuration.last_updated).toLocaleString()}.`;
                        type = 'success';
                        logMessage(
                            `Got IO configuration: ${JSON.stringify(ioConfigToSet)}`,
                            'info'
                        );
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    } else {
                        message =
                            'No IO configuration detected in the backend. Default configuration has been loaded.';
                        type = 'warning';
                        console.warn(message);
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    }

                    if (apiResponse.ui_configuration) {
                        if (
                            apiResponse.ui_configuration.tiles.length == 0
                        ) {
                            message =
                                'Received empty UI configuration from backend. Falling back to default.';
                            type = 'warning';
                        } else {
                            uiConfigToSet = apiResponse.ui_configuration;
                            message = `UI configuration successfully loaded. Client ID: ${apiResponse.client_id}, Last Updated: ${new Date(apiResponse.ui_configuration.last_updated).toLocaleString()}.`;
                            type = 'success';
                        }

                        logMessage(
                            `Using UI configuration: ${JSON.stringify(uiConfigToSet)}`,
                            'info'
                        );
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    } else {
                        message =
                            'No UI configuration detected in the backend. Default configuration has been loaded.';
                        type = 'warning';
                        console.warn(message);
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    }

                    if (apiResponse.opc_configuration) {
                        opcConfigToSet = apiResponse.opc_configuration;
                        message = `OPC configuration successfully loaded. Client ID: ${apiResponse.client_id}, Last Updated: ${new Date(apiResponse.opc_configuration.last_updated).toLocaleString()}.`;
                        type = 'success';
                        logMessage(
                            `Got OPC configuration: ${JSON.stringify(opcConfigToSet)}`,
                            'info'
                        );
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    } else {
                        message =
                            'No OPC configuration detected in the backend. Default configuration has been loaded.';
                        type = 'warning';
                        console.warn(message);
                        if (message) {
                            showAlert(
                                message,
                                type,
                                'Configuration Alert'
                            );
                        }
                    }
                }
            } catch (err: any) {
                message = `Failed to fetch configurations from the backend after multiple retries. Default configurations have been loaded. Error: ${err.message || String(err)}.`;
                type = 'error';
                console.error(`Final error loading configurations: ${err}`);
            } finally {
                setDashboardContext({
                    payload: uiConfigToSet,
                    type: 'ui_config/set',
                });
                setDashboardContext({
                    payload: ioConfigToSet,
                    type: 'io_config/set',
                });
                setDashboardContext({
                    payload: opcConfigToSet,
                    type: 'opc_config/set',
                });
            }
        };

        // Call the async function when the component mounts
        // fetchConfig();
        fetchTables();
        fetchConfigs();
    }, [setDashboardContext]);

    return <></>; // This component no longer renders the alert UI directly
};
