'use client';

import { useAlert } from '@/lib/components/client_components/AlertContext';
import { DashboardContext } from '@/lib/components/client_components/DashboardContextWrapper';
import {
    CloseIcon,
    DownloadIcon,
    GripIcon,
    PlusIcon,
    PlusSquareIcon,
    SaveIcon,
    SettingsIcon,
    SpinnerIcon,
    TrashIcon,
    UploadIcon,
} from '@/lib/components/server_components/svg/icons';
import {
    ioConfiguration,
    ioModuleType,
    ioModule,
    ioPoint,
    ioPointType,
    ioRack

    // IOConfigurationSchema,
    // IOModule,
    // ioModuleTypes,
    // IOPoint,
    // IORack,
} from '@/lib/models/autogenerated/io_configuration_models';
import { fetchFromBackendApi } from '@/lib/utils/timeoutFetch';
import React, { useContext, useEffect, useRef, useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

// const CloudDownloadIcon = () => (
//     <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="24"
//         height="24"
//         viewBox="0 0 24 24"
//         fill="none"
//         stroke="currentColor"
//         strokeWidth="2"
//         strokeLinecap="round"
//         strokeLinejoin="round"
//         className="lucide lucide-cloud-download"
//     >
//         <path d="M4 14.5V14a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v.5" />
//         <path d="M12 10V20" />
//         <path d="m15 17-3 3-3-3" />
//         <path d="M20 16.5A5 5 0 0 0 18 7h-1.5a4 4 0 0 0-8-.5 4 4 0 0 0-4 4" />
//     </svg>
// );
// const UploadIcon = () => (
//     <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="24"
//         height="24"
//         viewBox="0 0 24 24"
//         fill="none"
//         stroke="currentColor"
//         strokeWidth="2"
//         strokeLinecap="round"
//         strokeLinejoin="round"
//         className="lucide lucude-upload"
//     >
//         <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
//         <polyline points="17 8 12 3 7 8" />
//         <line x1="12" x2="12" y1="3" y2="15" />
//     </svg>
// );
// const SpinnerIcon = () => (
//     <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="24"
//         height="24"
//         viewBox="0 0 24 24"
//         fill="none"
//         stroke="currentColor"
//         strokeWidth="2"
//         strokeLinecap="round"
//         strokeLinejoin="round"
//         className="lucide lucide-loader-2 animate-spin"
//     >
//         <path d="M21 12a9 9 0 1 1-6.219-8.56" />
//     </svg>
// );
// const CloudIcon = () => (
//     <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="24"
//         height="24"
//         viewBox="0 0 24 24"
//         fill="none"
//         stroke="currentColor"
//         strokeWidth="2"
//         strokeLinecap="round"
//         strokeLinejoin="round"
//         className="lucide lucide-cloud"
//     >
//         <path d="M4 14.5a5 5 0 0 1 1.5-9.4M17 14.5a5 5 0 0 1 1.5-9.4M10 14a6 6 0 0 1 6-6h1a4 4 0 0 1 4 4v2.5M10 14a6 6 0 0 0 6 6h1a4 4 0 0 0 4-4v-2.5M10 14a6 6 0 0 1-6-6h-1a4 4 0 0 1-4 4v2.5" />
//     </svg>
// );
// const ServerIcon = () => (
//     <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="24"
//         height="24"
//         viewBox="0 0 24 24"
//         fill="none"
//         stroke="currentColor"
//         strokeWidth="2"
//         strokeLinecap="round"
//         strokeLinejoin="round"
//         className="lucide lucide-server-cog"
//     >
//         <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
//         <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
//         <path d="M6 6h.01" />
//         <path d="M6 18h.01" />
//         <path d="M13 18h.01" />
//         <path d="M16 18h.01" />
//         <path d="M19 18h.01" />
//     </svg>
// );
const InputIcon = () => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="lucide lucide-arrow-down-to-dot"
    >
        <path d="M12 2v14" />
        <path d="m15 13-3 3-3-3" />
        <circle cx="12" cy="21" r="1" />
    </svg>
);
const OutputIcon = () => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="lucide lucide-arrow-up-to-dot"
    >
        <path d="M12 16V2" />
        <path d="m15 5-3-3-3 3" />
        <circle cx="12" cy="21" r="1" />
    </svg>
);
const SignalIcon = () => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="lucide lucide-signal"
    >
        <path d="M2 20h.01" />
        <path d="M7 20h.01" />
        <path d="M12 20h.01" />
        <path d="M17 20h.01" />
        <path d="M22 20h.01" />
    </svg>
);

export const IOConfigurationComponent: React.FC = () => {
    const { dashboardContext, setDashboardContext } =
        useContext(DashboardContext);

    // --- IO POINT COMPONENT (within Modal) ---
    interface IOPointProps {
        point: ioPointType;
        onUpdateValue: (id: string, value: any) => void;
    }
    const IOPointComponent: React.FC<IOPointProps> = ({
        point,
        onUpdateValue,
    }) => {
        const isDigital = point.point_type.type.startsWith('D');
        const isInput = point.point_type.type.endsWith('I');
        
        const handleDigitalToggle = () => onUpdateValue(point.id, !point.point_value);
        
        const handleAnalogChange = (e: React.ChangeEvent<HTMLInputElement>) => {
            const value = e.target.value === '' ? '' : Number(e.target.value);
            if (value !== '' && isNaN(value)) return;
            onUpdateValue(point.id, value);
        };
        
        return (
            <div className="flex items-center justify-between gap-2 px-3 py-2 bg-gray-50 rounded-lg min-h-[48px]">
                <div className="flex items-center gap-2">
                    <span
                        className={`p-1 rounded-full ${isDigital ? 'bg-blue-200 text-blue-800' : 'bg-purple-200 text-purple-800'}`}
                    >
                        {isDigital ? (
                            isInput ? (
                                <InputIcon />
                            ) : (
                                <OutputIcon />
                            )
                        ) : (
                            <SignalIcon />
                        )}
                    </span>
                    <span className="text-sm font-medium text-gray-700 truncate">
                        {point.point_type.label}
                    </span>
                </div>
                {isDigital ? (
                    <button    
                        onClick={isInput ? undefined : handleDigitalToggle}
                        type="button"
                        className={`h-6 w-12 rounded-full p-0.5 transition-colors duration-200 relative flex items-center justify-center ${isInput ? 'bg-gray-200 cursor-not-allowed' : point.point_value ? 'bg-green-500' : 'bg-gray-400'}`}
                        disabled={isInput}
                    >
                        <div
                            className={`h-5 w-5 rounded-full bg-white shadow-md transition-transform duration-200 ${point.point_value ? 'translate-x-3' : '-translate-x-3'}`}
                        ></div>
                    </button>
                ) : (
                    <div className="flex items-center gap-1 w-full">
                        <input
                            type="number"
                            value={point.point_value as number}
                            onChange={handleAnalogChange}
                            disabled={isInput}
                            min={-100}
                            max={100}
                            step={0.1}
                            className={`w-16 p-1 text-sm rounded-md text-center border focus:outline-none focus:ring-2 focus:ring-blue-500 ${isInput ? 'bg-gray-200 text-gray-500 cursor-not-allowed' : 'bg-white text-gray-800 border-gray-300'}`}
                        />
                    </div>
                )}
            </div>
        );
    };

    // --- MODULE CONFIGURATION MODAL ---
    interface ModuleModalProps {
        isOpen: boolean;
        onClose: () => void;
        module: ioModuleType | null;
        onSave: (updatedModule: ioModuleType) => void;
    }
    const ModuleModal: React.FC<ModuleModalProps> = ({
        isOpen,
        onClose,
        module,
        onSave,
    }) => {
        if (!isOpen || !module) return null;
        const [formData, setFormData] = useState(module);
        
        useEffect(() => {
            setFormData(module);
        }, [module]);

        const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
            const { name, value } = e.target;
            setFormData((prev) => ({ ...prev, [name]: value }));
        };
        
        const handleTypeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
            const selectedTypeName = e.target.value;
            const newType = ioModuleTypes.find(
                (t) => t.name === selectedTypeName
            );
            if (newType) {
                setFormData((prev) => ({
                    ...prev,
                    type: newType,
                    points: newType.points.map((p) => ({
                        ...p,
                        id: uuidv4(),
                        value:
                            p.type === 'DO'
                                ? false
                                : p.type === 'AO'
                                  ? 0
                                  : false,
                    })),
                }));
            }
        };
        
        const handleUpdatePointValue = (pointId: string, value: any) => {
            setFormData((prev) => ({
                ...prev,
                points: prev.points.map((p) =>
                    p.id === pointId ? { ...p, value: value } : p
                ),
            }));
        };

        const handleSave = () => {
            onSave(formData);
            onClose();
        };

        return (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900 bg-opacity-75 p-4">
                <div className="bg-white rounded-2xl shadow-xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-2xl font-bold text-gray-800">
                            Configure Module
                        </h3>
                        <button
                            onClick={onClose}
                            className="p-2 text-gray-500 hover:text-gray-800"
                        >
                            <CloseIcon/>
                            {/* <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-6 w-6"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M6 18L18 6M6 6l12 12"
                                />
                            </svg> */}
                        </button>
                    </div>
                    <form
                        onSubmit={(e) => {
                            e.preventDefault();
                            handleSave();
                        }}
                    >
                        <div className="mb-4">
                            <label className="block text-gray-700 font-semibold mb-1">
                                Module Name:
                            </label>
                            <input
                                type="text"
                                name="name"
                                value={formData.name}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 font-semibold mb-1">
                                Module Type:
                            </label>
                            <select
                                value={formData.type.name}
                                onChange={handleTypeChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            >
                                {ioModuleTypes.map((type) => (
                                    <option key={type.name} value={type.name}>
                                        {type.name}
                                    </option>
                                ))}
                            </select>
                        </div>
                        <h4 className="text-lg font-bold text-gray-800 mt-6 mb-2">
                            I/O Points
                        </h4>
                        <div className="space-y-2">
                            {formData.points.map((point) => (
                                <IOPointComponent
                                    key={point.id}
                                    point={point}
                                    onUpdateValue={handleUpdatePointValue}
                                    // onUpdateValue={() => {}}
                                />
                            ))}
                        </div>
                        <div className="flex justify-end mt-6">
                            <button
                                type="submit"
                                className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-bold"
                            >
                                Save Changes
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        );
    };

    // --- RACK CONFIGURATION MODAL ---
    interface RackModalProps {
        isOpen: boolean;
        onClose: () => void;
        rack: IORack | null;
        onSave: (updatedRack: IORack) => void;
        onDelete: () => void;
    }
    const RackModal: React.FC<RackModalProps> = ({
        isOpen,
        onClose,
        rack,
        onSave,
        onDelete,
    }) => {
        if (!isOpen || !rack) return null;
        
        const [formData, setFormData] = useState(rack);
        
        useEffect(() => {
            setFormData(rack);
        }, [rack]);
        
        const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
            const { name, value } = e.target;
            setFormData((prev) => ({
                ...prev,
                rackConfig: {
                    ...prev.rackConfig,
                    [name]:
                        name === 'maxModules' ? parseInt(value) || 0 : value,
                },
            }));
        };
        
        const handleSave = () => {
            onSave(formData);
            onClose();
        };
        
        return (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900 bg-opacity-75 p-4">
                <div className="bg-white rounded-2xl shadow-xl p-6 w-full max-w-lg">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-2xl font-bold text-gray-800">
                            Configure Rack
                        </h3>
                        <button
                            onClick={onClose}
                            className="p-2 text-gray-500 hover:text-gray-800"
                        >
                            <CloseIcon/>
                            {/* <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-6 w-6"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M6 18L18 6M6 6l12 12"
                                />
                            </svg> */}
                        </button>
                    </div>
                    <form
                        onSubmit={(e) => {
                            e.preventDefault();
                            handleSave();
                        }}
                    >
                        <div className="mb-4">
                            <label className="block text-gray-700 font-semibold mb-1">
                                Rack Name:
                            </label>
                            <input
                                type="text"
                                name="name"
                                value={formData.rackConfig.name}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 font-semibold mb-1">
                                Address:
                            </label>
                            <input
                                type="text"
                                name="address"
                                value={formData.rackConfig.address}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 font-semibold mb-1">
                                Max Modules:
                            </label>
                            <input
                                type="number"
                                name="maxModules"
                                value={formData.rackConfig.maxModules}
                                onChange={handleInputChange}
                                min="1"
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="flex justify-between mt-6">
                            <button
                                type="button"
                                onClick={onDelete}
                                className="px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors font-bold"
                            >
                                Delete Rack
                            </button>
                            <button
                                type="submit"
                                className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-bold"
                            >
                                Save Changes
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        );
    };

    // --- MODULE COMPONENT (on backplane) ---
    interface ModuleProps {
        module: IOModule;
        index: number;
        onRemove: (id: string) => void;
        onEdit: (id: string) => void;
        onDragStart: (e: React.DragEvent, item: any) => void;
        onDragEnd: () => void;
    }
    const ModuleComponent: React.FC<ModuleProps> = ({
        module,
        index,
        onRemove,
        onEdit,
        onDragStart,
        onDragEnd,
    }) => {
        return (
            <div
                className="flex-shrink-0 w-[240px] h-[400px] flex flex-col bg-white rounded-2xl shadow-xl border border-gray-200 p-4 relative cursor-grab active:cursor-grabbing"
                draggable
                onDragStart={(e) => onDragStart(e, { moduleIndex: index })}
                onDragEnd={onDragEnd}
            >
                <div className="flex items-center justify-between mb-2">
                    <span className="text-lg font-bold text-gray-800 truncate">
                        {module.name}
                    </span>
                    <div className="flex items-center gap-1">
                        <button
                            onClick={() => onEdit(module.id)}
                            className="p-1 text-gray-400 hover:text-blue-500 transition-colors"
                        >
                            <SettingsIcon />
                        </button>
                        <button
                            onClick={() => onRemove(module.id)}
                            className="p-1 text-gray-400 hover:text-red-500 transition-colors"
                        >
                            <TrashIcon size={20} />
                        </button>
                        <div className="p-1 text-gray-400 cursor-grab">
                            {/* <GripVerticalIcon /> */}
                            <GripIcon />
                        </div>
                    </div>
                </div>
                <div className="text-sm text-gray-500 mb-4 font-mono">
                    Slot {index + 1}: {module.type.name}
                </div>
                <div className="flex-grow space-y-2 overflow-y-auto pr-2">
                    {module.points.map((point) => (
                        <div
                            key={point.id}
                            className="flex items-center justify-between gap-2 px-3 py-2 bg-gray-50 rounded-lg min-h-[48px]"
                        >
                            <span className="text-sm font-medium text-gray-700 truncate">
                                {point.label}
                            </span>
                            <span className="text-sm font-mono text-gray-600">
                                {point.type.startsWith('D')
                                    ? point.value
                                        ? 'ON'
                                        : 'OFF'
                                    : `${point.value}`}
                            </span>
                        </div>
                    ))}
                </div>
            </div>
        );
    };

    interface DragItem {
        rackId: string;
        moduleIndex: number;
    }

    // --- RACK COMPONENT CONTAINER ---
    interface RackComponentProps {
        rack: IORack;
        onAddModule: (rackId: string) => void;
        onDeleteRack: (rackId: string) => void;
        onEditRack: (rack: IORack) => void;
        onRemoveModule: (rackId: string, moduleId: string) => void;
        onEditModule: (rackId: string, moduleId: string) => void;
        onSaveModule: (rackId: string, updatedModule: IOModule) => void;
        // dragItem: React.MutableRefObject<any>;
        // dragOverItem: React.MutableRefObject<any>;
        dragItem: React.MutableRefObject<DragItem>;
        dragOverItem: React.MutableRefObject<DragItem>;
        // handleDragStart: (e: React.DragEvent, item: any) => void;
        handleDragStart: (e: React.DragEvent, item: DragItem) => void;
        handleDragEnd: () => void;
    }
    const RackComponent: React.FC<RackComponentProps> = ({
        rack,
        onAddModule,
        onDeleteRack,
        onEditRack,
        onRemoveModule,
        onEditModule,
        onSaveModule,
        dragItem,
        dragOverItem,
        handleDragStart,
        handleDragEnd,
    }) => {
        const handleDragEnter = (e: React.DragEvent, index: number) => {
            e.preventDefault();
            dragOverItem.current = { rackId: rack.id, moduleIndex: index };
        };
        const handleDrop = () => {
            if (
                !dragItem.current ||
                !dragOverItem.current ||
                dragItem.current.rackId !== dragOverItem.current.rackId
            )
                return;
            const newModules = [...rack.modules];
            const [reorderedItem] = newModules.splice(
                dragItem.current.moduleIndex,
                1
            );
            newModules.splice(
                dragOverItem.current.moduleIndex,
                0,
                reorderedItem
            );

            // onSaveModule(rack.id, null); // Placeholder to trigger re-render
            // onSaveModule(rack.id, rack.modules[dragItem.current.moduleIndex]); // Placeholder to trigger re-render
            setRacks((racks) => {
                const newRacks = [...racks];
                const rack_index = newRacks.findIndex((r) => r.id === rack.id);
                newRacks[rack_index].modules = newModules;
                return newRacks;
            });
        };

        return (
            <div className="flex-shrink-0 w-full max-w-7xl">
                <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                        <h2 className="text-xl font-semibold text-gray-800">
                            {rack.rackConfig.name}
                        </h2>
                        <span className="text-sm text-gray-500">
                            ({rack.rackConfig.address})
                        </span>
                        <button
                            onClick={() => onEditRack(rack)}
                            className="text-gray-400 hover:text-gray-800"
                        >
                            <SettingsIcon />
                        </button>
                        {/* <button
                            onClick={() => onDeleteRack(rack.id)}
                            className="text-gray-400 hover:text-gray-800"
                        >
                            <TrashIcon />
                        </button> */}
                        <button
                            onClick={() => onDeleteRack(rack.id)}
                            className="p-1 text-gray-400 hover:text-red-500 transition-colors"
                        >
                            <TrashIcon size={20} />
                        </button>
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={() => onAddModule(rack.id)}
                            disabled={
                                rack.modules.length >=
                                rack.rackConfig.maxModules
                            }
                            className={`flex items-center gap-1 px-3 py-1 text-sm font-bold rounded-lg shadow transition-colors ${
                                rack.modules.length >=
                                rack.rackConfig.maxModules
                                    ? 'bg-blue-300 text-gray-200 cursor-not-allowed'
                                    : 'bg-blue-600 text-white hover:bg-blue-700'
                            }`}
                        >
                            <PlusIcon /> Add Module
                        </button>
                    </div>
                </div>
                <div className="w-full overflow-x-auto p-4 bg-gray-200 rounded-xl shadow-inner mb-8">
                    <div
                        className="flex items-start gap-4 min-w-max"
                        onDragOver={(e) => e.preventDefault()}
                        onDrop={handleDrop}
                    >
                        {rack.modules.map((module, index) => (
                            <div
                                key={module.id}
                                onDragEnter={(e) => handleDragEnter(e, index)}
                            >
                                <ModuleComponent
                                    module={module}
                                    index={index}
                                    onRemove={() =>
                                        onRemoveModule(rack.id, module.id)
                                    }
                                    onEdit={() =>
                                        onEditModule(rack.id, module.id)
                                    }
                                    onDragStart={(e) =>
                                        handleDragStart(e, {
                                            rackId: rack.id,
                                            moduleIndex: index,
                                        })
                                    }
                                    onDragEnd={handleDragEnd}
                                />
                            </div>
                        ))}
                        {rack.modules.length === 0 && (
                            <div className="p-8 text-center text-gray-500 italic flex-grow">
                                This rack is empty.
                            </div>
                        )}
                    </div>
                </div>
            </div>
        );
    };

    // --- MAIN APP COMPONENT ---
    const [racks, setRacks] = useState<IORack[]>([]);
    const [editingModule, setEditingModule] = useState<{
        rackId: string;
        moduleId: string;
    } | null>(null);
    const [editingRack, setEditingRack] = useState<string | null>(null);
    const [isSaving, setIsSaving] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [isExportModalOpen, setIsExportModalOpen] = useState(false);
    const [isImportModalOpen, setIsImportModalOpen] = useState(false);
    // const { db, userId, isAuthReady } = useContext(FirebaseContext);
    // const { showAlert } = useContext(AlertContext);
    const { showAlert } = useAlert();
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Drag and Drop State
    const dragItem = useRef<any>(null);
    const dragOverItem = useRef<any>(null);
    const handleDragStart = (e: React.DragEvent, item: any) =>
        (dragItem.current = item);
    const handleDragEnd = () => {
        dragItem.current = null;
        dragOverItem.current = null;
    };

    useEffect(() => {
        if (racks.length === 0) {
            handleAddRack();
        }
    }, []);

    useEffect(() => {
        if (dashboardContext?.io_configuration) {
            setRacks(dashboardContext.io_configuration)
        }
    }, [dashboardContext?.io_configuration !== null])

    // Rack and Module CRUD
    const handleAddRack = () => {
        const newRack: IORack = {
            id: uuidv4(),
            rackConfig: {
                name: `Rack ${racks.length + 1}`,
                address: `192.168.1.${100 + racks.length}`,
                maxModules: 8,
            },
            modules: [],
        };
        setRacks((prev) => [...prev, newRack]);
    };
    
    const handleSaveRack = (updatedRack: IORack) => {
        setRacks((prev) =>
            prev.map((r) => (r.id === updatedRack.id ? updatedRack : r))
        );
        setEditingRack(null);
    };
    
    const handleDeleteRack = (rackId: string) => {
        setRacks((prev) => prev.filter((r) => r.id !== rackId));
        setEditingRack(null);
    };

    const handleAddModule = (rackId: string) => {
        setRacks((prev) =>
            prev.map((rack) => {
                if (
                    rack.id === rackId &&
                    rack.modules.length < rack.rackConfig.maxModules
                ) {
                    const defaultType = ioModuleTypes[0];
                    const newModule: IOModule = {
                        id: uuidv4(),
                        name: `Module_${rack.modules.length + 1}`,
                        type: defaultType,
                        points: defaultType.points.map((p) => ({
                            ...p,
                            id: uuidv4(),
                            value:
                                p.type === 'DO'
                                    ? false
                                    : p.type === 'AO'
                                      ? 0
                                      : false,
                        })),
                    };
                    return { ...rack, modules: [...rack.modules, newModule] };
                }
                return rack;
            })
        );
    };

    const handleRemoveModule = (rackId: string, moduleId: string) => {
        setRacks((prev) =>
            prev.map((rack) =>
                rack.id === rackId
                    ? {
                          ...rack,
                          modules: rack.modules.filter(
                              (m) => m.id !== moduleId
                          ),
                      }
                    : rack
            )
        );
    };
    
    const handleEditModule = (rackId: string, moduleId: string) => {
        setEditingModule({ rackId, moduleId });
    };

    const handleSaveModule = (updatedModule: IOModule) => {
        if (!editingModule) return;
        setRacks((prev) =>
            prev.map((rack) =>
                rack.id === editingModule.rackId
                    ? {
                          ...rack,
                          modules: rack.modules.map((m) =>
                              m.id === updatedModule.id ? updatedModule : m
                          ),
                      }
                    : rack
            )
        );
        setEditingModule(null);
    };

    // Firebase Save & Load
    const saveConfig = async () => {
        // if (!isAuthReady || !userId) {
        //     showAlert('Authentication in progress. Please wait.', 'error');
        //     return;
        // }
        setIsSaving(true);
        // showAlert('Saving configuration...', 'success');

        // const updatedConfig = { ...dashboardContext.io_configuration };
        // updatedConfig.io_configuration = racks;

        try {
            fetchFromBackendApi(`/api/backend/ui/io_config/${'abc'}`, 'POST', {
                config_json: {racks: racks},
            })
                .then(() => {
                    setDashboardContext({
                        payload: racks,
                        type: 'io/config/set',
                    });
                    showAlert(
                        'IO configuration saved successfully!',
                        'success'
                    );
                })
                .catch((error) => {
                    showAlert(
                        `Failed to save IO configuration: ${error}`,
                        'error'
                    );
                })
                .finally(() => setIsSaving(false));

            // const userDocRef = doc(
            //     db,
            //     'artifacts',
            //     appId,
            //     'users',
            //     userId,
            //     'config',
            //     'plc_config'
            // );
            // await setDoc(userDocRef, { racks: JSON.stringify(racks) });
            // showAlert('Configuration saved to the cloud!', 'success');
        } catch (error) {
            console.error('Error saving config:', error);
            showAlert('Failed to save configuration.', 'error');
        } finally {
            // setIsSaving(false);
        }
    };
    const loadConfigFromCloud = async () => {
        // if (!isAuthReady || !userId) {
        //     showAlert('Authentication in progress. Please wait.', 'error');
        //     return;
        // }
        setIsLoading(true);
        showAlert('Loading configuration...', 'success');
        try {
            // const userDocRef = doc(
            //     db,
            //     'artifacts',
            //     appId,
            //     'users',
            //     userId,
            //     'config',
            //     'plc_config'
            // );
            // const docSnap = await getDoc(userDocRef);
            // if (docSnap.exists()) {
            //     const data = docSnap.data();
            //     if (data.racks) {
            //         const parsedRacks = JSON.parse(data.racks);
            //         ConfigurationSchema.parse(parsedRacks); // Zod validation
            //         setRacks(parsedRacks);
            //         showAlert(
            //             'Configuration loaded from the cloud!',
            //             'success'
            //         );
            //     } else {
            //         throw new Error('No racks data found.');
            //     }
            // } else {
            //     showAlert('No saved configuration found.', 'info');
            // }
        } catch (error) {
            console.error('Error loading config:', error);
            showAlert(
                `Failed to load configuration. ${error.message}`,
                'error'
            );
        } finally {
            setIsLoading(false);
        }
    };

    // Export & Import
    const exportConfig = () => {
        const configJson = JSON.stringify(racks, null, 2);
        const blob = new Blob([configJson], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'plc_config.json';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        showAlert('Configuration exported as JSON!', 'success');
    };

    const importConfig = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) {
            showAlert('No file selected.', 'error');
            return;
        }
        const reader = new FileReader();
        reader.onload = (event) => {
            try {
                const importedData = JSON.parse(event.target?.result as string);
                IOConfigurationSchema.parse(importedData); // Zod validation
                setRacks(importedData);
                showAlert('Configuration imported successfully!', 'success');
            } catch (error: any) {
                showAlert(`Failed to import config: ${error.message}`, 'error');
                console.error('Import error:', error);
            }
        };
        reader.readAsText(file);
    };

    const currentModule = editingModule
        ? racks
              .find((r) => r.id === editingModule.rackId)
              ?.modules.find((m) => m.id === editingModule.moduleId) || null
        : null;
    const currentRack = editingRack
        ? racks.find((r) => r.id === editingRack) || null
        : null;

    const ToolTipButton = (props: {
        svgIcon: () => React.JSX.Element;
        bgColor: string;
        onHoverBgColor: string;
        isLoading: boolean;
        onClick?: () => void;
        text?: string;
        tooltipText?: string;
    }) => {
        return (
            <div className="relative group">
                <button
                    onClick={props.onClick}
                    // disabled={isSaving || isLoading}
                    className={`flex items-center gap-2 px-4 py-2 ${props.bgColor} text-white font-bold rounded-lg shadow hover:${props.onHoverBgColor} transition-colors`}
                >
                    {props.isLoading ? <SpinnerIcon /> : props.svgIcon()}{' '}
                    {props.text ?? null}
                </button>
                {/* The tooltip itself */}
                {props.tooltipText ? (
                    <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 -translate-y-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none">
                        <div className="bg-gray-800 text-white text-xs rounded py-1 px-2 whitespace-nowrap">
                            {props.tooltipText}
                        </div>
                        {/* A small triangle for the tooltip's arrow */}
                        <svg
                            className="absolute text-gray-800 h-2 w-full left-0 top-full"
                            x="0px"
                            y="0px"
                            viewBox="0 0 255 255"
                            fill="currentColor"
                        >
                            <polygon points="0,0 127.5,127.5 255,0" />
                        </svg>
                    </div>
                ) : (
                    <></>
                )}
            </div>
        );
    };

    const ButtonsColumn = () => {
        return (
            <div className="w-full max-w-7xl flex flex-col items-center h-full py-10">
                <div className="flex flex-col h-full justify-between items-center">
                    <ToolTipButton
                        svgIcon={PlusSquareIcon}
                        onClick={handleAddRack}
                        tooltipText="Add New Rack"
                        isLoading={false}
                        bgColor="bg-gray-600"
                        onHoverBgColor="bg-gray-700"
                    />
                    <ToolTipButton
                        svgIcon={SaveIcon}
                        onClick={saveConfig}
                        tooltipText="Save IO Configuration"
                        isLoading={isSaving}
                        bgColor="bg-gray-600"
                        onHoverBgColor="bg-gray-700"
                    />
                    <ToolTipButton
                        svgIcon={UploadIcon}
                        // onClick={() => fileInputRef.current?.click()}
                        onClick={() => setIsImportModalOpen(true)}
                        tooltipText="Upload IO Configuration"
                        isLoading={false}
                        bgColor="bg-gray-600"
                        onHoverBgColor="bg-gray-700"
                    />
                    <ToolTipButton
                        svgIcon={DownloadIcon}
                        // onClick={exportConfig}
                        onClick={() => setIsExportModalOpen(true)}
                        tooltipText="Export IO Configuration"
                        isLoading={false}
                        bgColor="bg-gray-600"
                        onHoverBgColor="bg-gray-700"
                    />
                    <input
                        type="file"
                        ref={fileInputRef}
                        onChange={importConfig}
                        className="hidden"
                        accept=".json"
                    />
                </div>
            </div>
        );
    };

    const ImportModal = ({ isOpen, onClose, onImport }) => {
        if (!isOpen) return null;
        const [importText, setImportText] = useState('');

        const handleImport = () => {
            try {
                const parsedPlots = IOConfigurationSchema.parse(
                    JSON.parse(importText)
                );
                onImport(parsedPlots);
                onClose();
            } catch (error) {
                console.error('Import error:', error);
                alert(
                    'Failed to import IO configuration. The data format is invalid.'
                );
            }
        };

        return (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900 bg-opacity-75 p-4">
                <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-lg max-h-[80vh] overflow-y-auto">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-2xl font-bold text-gray-800">
                            Import IO Configuration
                        </h3>
                        <button
                            onClick={onClose}
                            className="p-2 text-gray-500 hover:text-gray-800"
                        >
                            <CloseIcon />
                        </button>
                    </div>
                    <p className="mb-4 text-gray-700">
                        Paste your exported JSON here to import IO
                        configuration.
                    </p>
                    <textarea
                        value={importText}
                        onChange={(e) => setImportText(e.target.value)}
                        className="w-full h-64 p-4 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none"
                        placeholder="Paste your JSON here..."
                    />
                    <div className="flex justify-end mt-4">
                        <button
                            onClick={handleImport}
                            className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors text-sm font-semibold"
                        >
                            Import IO Configuration
                        </button>
                    </div>
                </div>
            </div>
        );
    };

    const ExportModal = ({ isOpen, onClose, configuration }) => {
        if (!isOpen) return null;
        const exportText = JSON.stringify(configuration, null, 2);

        const handleCopyToClipboard = () => {
            navigator.clipboard.writeText(exportText);
        };

        return (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900 bg-opacity-75 p-4">
                <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-lg max-h-[80vh] overflow-y-auto">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-2xl font-bold text-gray-800">
                            Export IO Configuration
                        </h3>
                        <button
                            onClick={onClose}
                            className="p-2 text-gray-500 hover:text-gray-800"
                        >
                            <CloseIcon />
                        </button>
                    </div>
                    <p className="mb-4 text-gray-700">
                        Copy the JSON below to export your IO configuration.
                    </p>
                    <textarea
                        readOnly
                        value={exportText}
                        className="w-full h-64 p-4 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none"
                    />
                    <div className="flex justify-end mt-4">
                        <button
                            onClick={handleCopyToClipboard}
                            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm font-semibold"
                        >
                            Copy to Clipboard
                        </button>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className="grid grid-cols-[93%_7%] h-full">
            <div className="h-full bg-gray-100 p-4 flex flex-col items-center font-sans overflow-y-scroll">
                <div className="w-full max-w-7xl">
                    {racks.map((rack) => (
                        <RackComponent
                            key={rack.id}
                            rack={rack}
                            onAddModule={handleAddModule}
                            onDeleteRack={() => handleDeleteRack(rack.id)}
                            onEditRack={() => setEditingRack(rack.id)}
                            onRemoveModule={handleRemoveModule}
                            onEditModule={handleEditModule}
                            onSaveModule={(rackId, updatedModule) => {
                                if (updatedModule) {
                                    setRacks((prev) =>
                                        prev.map((r) =>
                                            r.id === rackId
                                                ? {
                                                      ...r,
                                                      modules: r.modules.map(
                                                          (m) =>
                                                              m.id ===
                                                              updatedModule.id
                                                                  ? updatedModule
                                                                  : m
                                                      ),
                                                  }
                                                : r
                                        )
                                    );
                                }
                            }}
                            dragItem={dragItem}
                            dragOverItem={dragOverItem}
                            handleDragStart={handleDragStart}
                            handleDragEnd={handleDragEnd}
                        />
                    ))}
                </div>

                <ModuleModal
                    isOpen={!!currentModule}
                    // isOpen={true}
                    onClose={() => setEditingModule(null)}
                    // onClose={() => {}}
                    module={currentModule}
                    onSave={handleSaveModule}
                />

                <RackModal
                    isOpen={!!currentRack}
                    onClose={() => setEditingRack(null)}
                    rack={currentRack}
                    onSave={handleSaveRack}
                    onDelete={() => handleDeleteRack(editingRack)}
                />

                <ExportModal
                    isOpen={isExportModalOpen}
                    onClose={() => setIsExportModalOpen(false)}
                    configuration={racks}
                />

                <ImportModal
                    isOpen={isImportModalOpen}
                    onClose={() => setIsImportModalOpen(false)}
                    onImport={() => {}}
                />
            </div>
            {ButtonsColumn()}
        </div>
    );
};

// export default function Root() {
//     return (
//         <FirebaseProvider>
//             <AlertProvider>
//                 <ZodLoader>
//                     <App />
//                 </ZodLoader>
//             </AlertProvider>
//         </FirebaseProvider>
//     );
// }
