'use client';

import { useAlert } from '@/lib/components/client_components/AlertContext';
import { AlertType } from '@/lib/components/client_components/AlertPopup';
import { DashboardContext } from '@/lib/components/client_components/DashboardContextWrapper';
import { Modal } from '@/lib/components/client_components/Modal';
import { ToolTipButtonProps } from '@/lib/components/client_components/ToolTipButtonsColumn';
import {
    useWebSocket,
    WebSocketMessage,
} from '@/lib/components/client_components/WebsocketSubscriptionProvider';
import LoadingIndicator from '@/lib/components/server_components/LoadingIndicator';
import { MultiColumnPanelContainer } from '@/lib/components/server_components/MultiColumnPanelContainer';
import {
    DownloadIcon,
    GripIcon,
    InfoIcon,
    PlusSquareIcon,
    SaveIcon,
    SearchIcon,
    SettingsIcon,
    TrashIcon,
    UploadIcon,
} from '@/lib/components/server_components/svg/icons';
import {
    plotConfigurations,
    plotConfigurationType,
} from '@/lib/models/autogenerated/configuration_models';
import {
    DatabaseData,
    TableSchemaMap,
} from '@/lib/models/autogenerated/database_models';
import { validateWebsocketData } from '@/lib/models/validators';
import { fetchFromBackendApi } from '@/lib/utils/timeoutFetch';
import { logMessage } from '@/lib/utils/utilities';
import { useCallback, useContext, useEffect, useRef, useState } from 'react';
import {
    Bar,
    BarChart,
    CartesianGrid,
    Legend,
    Line,
    LineChart,
    ResponsiveContainer,
    Scatter,
    ScatterChart,
    Tooltip,
    XAxis,
    YAxis,
} from 'recharts';
import { v4 as uuidv4 } from 'uuid';

interface MultiPlotProperties extends plotConfigurationType {
    onEdit: () => void;
    onRemove: () => void;
    onDragStart: (e: any) => void;
    onDragOver: (e: any) => void;
}

interface PlotDataPoint {
    time: Date;
    value: number;
}

const PlotModal = ({
    isOpen,
    onClose,
    plot,
    onUpdatePlot,
    availableTables,
    getAvailableColumns,
}) => {
    if (!isOpen || !plot) return null;
    const [nameInputValue, setNameInputValue] = useState(plot.name);
    const [lengthInputValue, setLengthInputValue] = useState(plot.max_length);
    const [typeInputValue, setTypeInputValue] = useState(plot.type);
    const [traces, setTraces] = useState(plot.traces);
    const [searchTerm, setSearchTerm] = useState('');

    const handleApplyChanges = () => {
        const updatedPlot = {
            ...plot,
            name: nameInputValue,
            max_length: Number(lengthInputValue),
            type: typeInputValue,
            traces: traces,
        };
        onUpdatePlot(updatedPlot);
        onClose();
    };

    const handleAddTrace = (table, column) => {
        const newTrace = {
            table_name: table,
            column: column,
            color: '#8884d8',
        };
        if (
            !traces.some((t) => t.table_name === table && t.column === column)
        ) {
            setTraces([...traces, newTrace]);
        }
    };

    const handleRemoveTrace = (traceToRemove) => {
        setTraces(
            traces.filter(
                (trace) =>
                    !(
                        trace.table_name === traceToRemove.table_name &&
                        trace.column === traceToRemove.column
                    )
            )
        );
    };

    const handleUpdateTraceColor = (traceToUpdate, newColor) => {
        setTraces(
            traces.map((trace) => {
                if (
                    trace.table_name === traceToUpdate.table_name &&
                    trace.column === traceToUpdate.column
                ) {
                    return { ...trace, color: newColor };
                }
                return trace;
            })
        );
    };

    const filteredTables = availableTables.filter(
        (table) =>
            table.toLowerCase().includes(searchTerm.toLowerCase()) ||
            getAvailableColumns(table).some((col) =>
                col.toLowerCase().includes(searchTerm.toLowerCase())
            )
    );

    return (
        <Modal onClose={onClose} isOpen={isOpen} modalTitle="Edit Plot">
            <>
                <div className="mb-4">
                    <label
                        htmlFor="plotName"
                        className="font-semibold text-gray-700 mb-1 block"
                    >
                        Plot Name:
                    </label>
                    <input
                        id="plotName"
                        type="text"
                        value={nameInputValue}
                        onChange={(e) => setNameInputValue(e.target.value)}
                        placeholder="Enter plot name..."
                        className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                </div>

                {/* Plot Type Selection */}
                <div className="mb-4">
                    <label
                        htmlFor="plotType"
                        className="font-semibold text-gray-700 mb-1 block"
                    >
                        Plot Type:
                    </label>
                    <select
                        id="plotType"
                        value={typeInputValue}
                        onChange={(e) => setTypeInputValue(e.target.value)}
                        className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                        <option value="Line">Line Chart</option>
                        <option value="Bar">Bar Chart</option>
                        <option value="Scatter">Scatter Plot</option>
                    </select>
                </div>

                <h4 className="font-semibold text-gray-700 mb-2">
                    Active Traces:
                </h4>
                <div className="flex flex-wrap gap-2 mb-6">
                    {traces.map((trace, traceIndex) => (
                        <div
                            key={traceIndex}
                            className="flex items-center gap-1 bg-gray-200 text-gray-800 rounded-full px-3 py-1 text-xs"
                        >
                            {trace.table_name}:{trace.column}
                            <input
                                type="color"
                                value={trace.color || '#8884d8'}
                                onChange={(e) =>
                                    handleUpdateTraceColor(
                                        trace,
                                        e.target.value
                                    )
                                }
                                className="w-4 h-4 ml-1 rounded-full border-none cursor-pointer"
                            />
                            <button
                                onClick={() => handleRemoveTrace(trace)}
                                className="text-red-500 hover:text-red-700 ml-1"
                            >
                                <TrashIcon size={10} />
                            </button>
                        </div>
                    ))}
                    {traces.length === 0 && (
                        <span className="text-gray-500 text-sm italic">
                            No traces added yet.
                        </span>
                    )}
                </div>

                <div className="w-full mb-6">
                    <h4 className="font-semibold text-gray-700 mb-2">
                        Add New Trace:
                    </h4>
                    <div className="relative mb-2">
                        <input
                            type="text"
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            placeholder="Search for traces..."
                            className="w-full pl-10 pr-4 py-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <SearchIcon />
                        </div>
                    </div>
                    <select
                        onChange={(e) => {
                            const [table, column] = e.target.value.split(':');
                            if (table && column) {
                                handleAddTrace(table, column);
                                e.target.value = ''; // Reset select to prompt
                            }
                        }}
                        className="w-full p-2 rounded-md bg-white border border-gray-300 text-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        defaultValue=""
                    >
                        <option value="" disabled>
                            Select a trace...
                        </option>
                        {filteredTables.map((tableName) => (
                            <optgroup key={tableName} label={tableName}>
                                {getAvailableColumns(tableName)
                                    .filter((col) =>
                                        col
                                            .toLowerCase()
                                            .includes(searchTerm.toLowerCase())
                                    )
                                    .map((columnName) => (
                                        <option
                                            key={`${tableName}:${columnName}`}
                                            value={`${tableName}:${columnName}`}
                                        >
                                            {columnName}
                                        </option>
                                    ))}
                            </optgroup>
                        ))}
                    </select>
                </div>

                <div className="flex items-center gap-2 mb-4">
                    <label
                        htmlFor={`maxLengthInput-${plot.id}`}
                        className="font-semibold text-gray-700 text-sm"
                    >
                        Chart Length:
                    </label>
                    <input
                        id={`maxLengthInput-${plot.id}`}
                        type="number"
                        value={lengthInputValue}
                        onChange={(e) =>
                            setLengthInputValue(Number(e.target.value))
                        }
                        onKeyDown={(e) => {
                            if (e.key === 'Enter') handleApplyChanges();
                        }}
                        className="w-24 p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                        min="1"
                    />
                </div>
                <div className="flex justify-end">
                    <button
                        onClick={handleApplyChanges}
                        className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm font-semibold"
                    >
                        Save Changes
                    </button>
                </div>
            </>
        </Modal>
    );
};

const ExportModal = ({ isOpen, onClose, plots }) => {
    const { showAlert } = useAlert();

    const exportText = JSON.stringify(plots, null, 2);

    const handleCopyToClipboard = () => {
        if (!navigator.clipboard) {
            showAlert('Clipboard API not available, copy manually', 'warning');
        } else {
            navigator.clipboard.writeText(exportText);
        }
    };

    return (
        <Modal onClose={onClose} isOpen={isOpen} modalTitle="Export Plots">
            <>
                <p className="mb-4 text-r2-dark-modal-subtext">
                    Copy the JSON below to export your plot configurations.
                </p>
                <textarea
                    readOnly
                    value={exportText}
                    className="w-full h-64 p-4 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none"
                />
                <div className="flex justify-end mt-4">
                    <button
                        onClick={handleCopyToClipboard}
                        className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm font-semibold"
                    >
                        Copy to Clipboard
                    </button>
                </div>
            </>
        </Modal>
    );
};

const ImportModal = ({ isOpen, onClose, onImport }) => {
    const [importText, setImportText] = useState('');
    const { showAlert } = useAlert();

    const handleImport = () => {
        let message: string;
        let log_level: AlertType;
        try {
            const parsedPlots = plotConfigurations.parse(
                JSON.parse(importText)
            );
            onImport(parsedPlots);
            onClose();

            message = 'Successfully imported plot configurations';
            log_level = 'success';
        } catch (error) {
            message = `Failed to import plots. The data format is invalid: ${error}`;
            log_level = 'error';
        }

        logMessage(message, log_level);
        showAlert(message, log_level);
    };

    useEffect(() => setImportText(''), [isOpen])

    return (
        <Modal onClose={onClose} isOpen={isOpen} modalTitle="Import Plots">
            <>
                <p className="mb-4 text-r2-dark-modal-subtext">
                    Paste your exported JSON here to import plot configurations.
                </p>
                <textarea
                    value={importText}
                    onChange={(e) => setImportText(e.target.value)}
                    className="w-full h-64 p-4 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none"
                    placeholder="Paste your JSON here..."
                />
                <div className="flex justify-end mt-4">
                    <button
                        onClick={handleImport}
                        // className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors text-sm font-semibold"
                        className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm font-semibold"
                    >
                        Import Plots
                    </button>
                </div>
            </>
        </Modal>
    );
};

const PlotComponent = ({
    id,
    name,
    type,
    traces,
    max_length = 100,
    onEdit,
    onRemove,
    onDragStart,
    onDragOver,
}: MultiPlotProperties) => {
    const [chartData, setChartData] = useState<{
        [name: string]: PlotDataPoint[];
    }>({});
    const [dataStatus, setDataStatus] = useState('historical');
    const plotLength = useRef(max_length);

    const { registerMessageListener, subscribe, unsubscribe, isConnected } =
        useWebSocket();
    const { showAlert } = useAlert();

    const uniqueTables = Array.from(new Set(traces.map((t) => t.table_name)));

    const websocketMessageCallback = useCallback(
        (message: WebSocketMessage) => {
            logMessage(`Plot received: ${JSON.stringify(message)}`, 'debug');

            try {
                if (!message || !message.data || !Array.isArray(message.data)) {
                    return;
                }

                const validatedData = validateWebsocketData<DatabaseData>(
                    message,
                    TableSchemaMap[message.table]
                );

                if (
                    !validatedData ||
                    !validatedData.data ||
                    !Array.isArray(validatedData.data)
                ) {
                    logMessage('Received message has no data.', 'info');
                    return;
                }

                if (validatedData.type) {
                    setDataStatus(validatedData.type);
                }

                const tracesToUpdate = traces.filter(
                    (t) => t.table_name === validatedData.table
                );
                if (tracesToUpdate.length === 0) return;

                setChartData((prevData) => {
                    const updatedData = { ...prevData };
                    tracesToUpdate.forEach((trace) => {
                        const traceId = `${trace.table_name}-${trace.column}`;
                        const currentTraceData = updatedData[traceId] || [];

                        const parsedTraceData = validatedData.data
                            .map((item) => ({
                                time: new Date(item.stamp).toLocaleTimeString(),
                                value: item[trace.column],
                                ...item,
                            }))
                            .filter((point) => typeof point.value === 'number');

                        const newTraceData = [
                            ...currentTraceData,
                            ...parsedTraceData,
                        ];
                        const maxLengthToUse = plotLength.current;
                        updatedData[traceId] =
                            newTraceData.slice(-maxLengthToUse);
                    });
                    return updatedData;
                });
            } catch (error) {
                showAlert(
                    `Unvalidated websocket data: ${error.message}`,
                    'error'
                );
            }
        },
        [traces, showAlert]
    );

    useEffect(() => {
        if (!isConnected) return;

        const subscriptions: string[] = [];

        const listenerId = traces
            .map((t) => `${t.table_name}-${t.column}`)
            .join(',');
        const unregisterListener = registerMessageListener(
            listenerId,
            websocketMessageCallback
        );

        uniqueTables.forEach((tableName) => {
            subscribe(tableName, true, max_length);
            subscriptions.push(tableName);
        });

        return () => {
            subscriptions.forEach((tableName) => unsubscribe(tableName));
            unregisterListener();
        };
    }, [
        isConnected,
        uniqueTables.join(','),
        max_length,
        websocketMessageCallback,
    ]);

    useEffect(() => {
        plotLength.current = max_length;
        setChartData((prevData) => {
            const updatedData = {};
            Object.entries(prevData).forEach(([key, value]) => {
                updatedData[key] = value.slice(-max_length);
            });
            return updatedData;
        });
    }, [max_length]);

    const hasData = Object.values(chartData).some((data) => data.length > 0);

    const mergedChartData = () => {
        const dataMap = new Map();

        // // Iterate directly over the chartData array of traces
        Object.entries(chartData).forEach(([traceId, dataPoints]) => {
            dataPoints.forEach((point) => {
                const { time, value } = point;
                if (!dataMap.has(time)) {
                    dataMap.set(time, { time });
                }
                dataMap.get(time)[traceId] = value;
            });
        });
        return Array.from(dataMap.values());
    };

    const getScatterData = () => {
        const data = mergedChartData();
        return traces
            .map((trace) => {
                const traceId = `${trace.table_name}-${trace.column}`;
                return data.map((point) => ({
                    x: point.time,
                    y: point[traceId],
                    z: 1, // for dot size, though not used in recharts by default
                }));
            })
            .flat();
    };

    const plotTitle = name || 'New Plot';
    const mergedData = mergedChartData();

    const renderChart = () => {
        if (!traces.length) {
            return (
                <div className="flex flex-row items-center h-full w-full justify-center content-center space-x-2 text-gray-500">
                    <InfoIcon />
                    <p className="font-bold dark:text-r2-white">
                        Select Traces
                    </p>
                </div>
            );
        }

        if (!hasData) {
            return (
                <LoadingIndicator
                    className="text-gray-500"
                    text={'Waiting for valid data...'.toUpperCase()}
                />
            );
        }

        switch (type) {
            case 'bar':
                return (
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart
                            data={mergedData}
                            margin={{ top: 5, right: 10, left: -20, bottom: 5 }}
                        >
                            <CartesianGrid
                                strokeDasharray="3 3"
                                stroke="#e5e7eb"
                            />
                            <XAxis
                                dataKey="time"
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <YAxis
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <Tooltip
                                contentStyle={{
                                    backgroundColor: '#fff',
                                    border: '1px solid #d1d5db',
                                    borderRadius: '8px',
                                    fontSize: '12px',
                                }}
                            />
                            <Legend wrapperStyle={{ fontSize: '12px' }} />
                            {traces.map((trace, index) => {
                                const traceId = `${trace.table_name}-${trace.column}`;
                                return (
                                    <Bar
                                        key={traceId}
                                        dataKey={traceId}
                                        name={`${trace.table_name}:${trace.column}`}
                                        fill={trace.color}
                                        isAnimationActive={false}
                                    />
                                );
                            })}
                        </BarChart>
                    </ResponsiveContainer>
                );
            case 'scatter':
                const scatterData = getScatterData();
                return (
                    <ResponsiveContainer width="100%" height="100%">
                        <ScatterChart
                            margin={{ top: 5, right: 10, left: -20, bottom: 5 }}
                            data={scatterData}
                        >
                            <CartesianGrid strokeDasharray="3 3" />
                            <XAxis
                                type="category"
                                dataKey="x"
                                name="Time"
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <YAxis
                                type="number"
                                dataKey="y"
                                name="Value"
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <Tooltip cursor={{ strokeDasharray: '3 3' }} />
                            <Legend wrapperStyle={{ fontSize: '12px' }} />
                            {traces.map((trace, index) => (
                                <Scatter
                                    key={`${trace.table_name}-${trace.column}`}
                                    name={`${trace.table_name}:${trace.column}`}
                                    data={
                                        chartData[
                                            `${trace.table_name}-${trace.column}`
                                        ]
                                    }
                                    fill={trace.color}
                                    isAnimationActive={false}
                                />
                            ))}
                        </ScatterChart>
                    </ResponsiveContainer>
                );
            case 'line':
            default:
                return (
                    <ResponsiveContainer width="100%" height="100%">
                        <LineChart
                            data={mergedData}
                            margin={{ top: 5, right: 10, left: -20, bottom: 5 }}
                        >
                            <CartesianGrid
                                strokeDasharray="3 3"
                                stroke="#e5e7eb"
                            />
                            <XAxis
                                dataKey="time"
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <YAxis
                                stroke="#6b7280"
                                style={{ fontSize: '12px' }}
                            />
                            <Tooltip
                                contentStyle={{
                                    backgroundColor: '#fff',
                                    border: '1px solid #d1d5db',
                                    borderRadius: '8px',
                                    fontSize: '12px',
                                }}
                            />
                            <Legend wrapperStyle={{ fontSize: '12px' }} />
                            {traces.map((trace, index) => {
                                const traceId = `${trace.table_name}-${trace.column}`;
                                return (
                                    <Line
                                        key={traceId}
                                        type="monotone"
                                        dataKey={traceId}
                                        name={`${trace.table_name}:${trace.column}`}
                                        stroke={trace.color}
                                        strokeWidth={2}
                                        dot={false}
                                        activeDot={{ r: 8 }}
                                        isAnimationActive={false}
                                    />
                                );
                            })}
                        </LineChart>
                    </ResponsiveContainer>
                );
        }
    };

    const statusClasses =
        dataStatus === 'live' ? 'bg-green-500 animate-pulse' : 'bg-blue-500';

    return (
        <div
            className="flex flex-col rounded-2xl shadow-xl m-2 border border-gray-200 bg-white w-full h-[350px] p-4"
            draggable="true"
            onDragStart={onDragStart}
            onDragOver={onDragOver}
        >
            <div className="flex justify-between items-center mb-2">
                <div className="flex items-center gap-2">
                    <div
                        className={`w-3 h-3 rounded-full ${statusClasses}`}
                        title={
                            dataStatus === 'live'
                                ? 'Receiving live data'
                                : 'Displaying historical data'
                        }
                    ></div>
                    <h2 className="text-xl font-bold text-gray-800 truncate">
                        {plotTitle}
                    </h2>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={onEdit}
                        className="p-2 text-gray-500 hover:text-blue-600 transition-colors"
                    >
                        <SettingsIcon />
                    </button>
                    <button
                        onClick={onRemove}
                        className="p-2 text-gray-500 hover:text-red-600 transition-colors"
                    >
                        <TrashIcon size={20} />
                    </button>
                    <span className="cursor-grab text-gray-400">
                        <GripIcon />
                    </span>
                </div>
            </div>

            <div className="flex-grow w-full">{renderChart()}</div>
        </div>
    );
};

export const MultiPlotComponent = () => {
    const [plots, setPlots] = useState<plotConfigurationType[]>([]);
    const [editingPlotId, setEditingPlotId] = useState(null);
    const [isExportModalOpen, setIsExportModalOpen] = useState(false);
    const [isImportModalOpen, setIsImportModalOpen] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const { dashboardContext, setDashboardContext } =
        useContext(DashboardContext);
    const dragItem = useRef(null);
    const dragOverItem = useRef(null);
    const { showAlert } = useAlert();

    const availableTables =
        dashboardContext.available_database_tables?.map(
            (table_def) => table_def.table_name
        ) ?? [];

    useEffect(() => {
        if (dashboardContext.ui_configuration)
            setPlots(dashboardContext?.ui_configuration?.plots);
    }, [dashboardContext?.ui_configuration == null]);

    const getAvailableColumns = (tableName: string) => {
        const matching_tables =
            dashboardContext.available_database_tables?.filter(
                (table) => table.table_name === tableName
            ) ?? [];
        if (matching_tables.length === 1) {
            if (matching_tables.length > 1) {
                logMessage(`More than one table found with name ${tableName}`);
            }
            return matching_tables[0].columns.filter(
                (column) => column !== 'stamp'
            );
        } else {
            return [];
        }
    };

    const handleAddPlot = () => {
        setPlots([
            ...plots,
            {
                id: uuidv4(),
                name: 'New Plot',
                type: 'line',
                traces: [],
                max_length: 100,
            },
        ]);
    };

    const handleRemovePlot = (id) => {
        setPlots(plots.filter((plot) => plot.id !== id));
    };

    const handleUpdatePlot = (updatedPlot) => {
        setPlots(
            plots.map((plot) =>
                plot.id === updatedPlot.id ? updatedPlot : plot
            )
        );
    };

    const savePlots = async () => {
        const plotsToSave = plots.map(
            ({ id, name, type, traces, max_length }) => ({
                id,
                name,
                type,
                traces,
                max_length,
            })
        );

        const updatedConfig = { ...dashboardContext.ui_configuration };
        updatedConfig.plots = plotsToSave;

        setIsSaving(true);
        fetchFromBackendApi(
            `/api/backend/ui/config/${'abc'}`,
            'POST',
            updatedConfig
        )
            .then(() => {
                setDashboardContext({
                    payload: plotsToSave,
                    type: 'ui/config/set_plot_config',
                });
                showAlert('Plots saved successfully!', 'success');
            })
            .catch((error) => {
                showAlert(
                    `Failed to save plot configuration: ${error}`,
                    'error'
                );
            })
            .finally(() => setIsSaving(false));
    };

    const currentEditingPlot = plots.find((plot) => plot.id === editingPlotId);

    // Drag and Drop Handlers
    const handleDragStart = (e, index) => {
        dragItem.current = index;
    };

    const handleDragOver = (e, index) => {
        e.preventDefault();
        dragOverItem.current = index;
    };

    const handleDrop = (e) => {
        const dragItemIndex = dragItem.current;
        const dragOverItemIndex = dragOverItem.current;

        if (
            dragItemIndex === null ||
            dragOverItemIndex === null ||
            dragItemIndex === dragOverItemIndex
        ) {
            return;
        }

        const newPlots = [...plots];
        const [reorderedItem] = newPlots.splice(dragItemIndex, 1);
        newPlots.splice(dragOverItemIndex, 0, reorderedItem);

        setPlots(newPlots);
        dragItem.current = null;
        dragOverItem.current = null;
    };

    const buttons: ToolTipButtonProps[] = [
        {
            svgIcon: PlusSquareIcon,
            isLoading: false,
            onClick: handleAddPlot,
            tooltipText: 'Add New Plot',
        },
        {
            svgIcon: SaveIcon,
            isLoading: isSaving,
            onClick: savePlots,
            tooltipText: 'Save Plots',
        },
        {
            svgIcon: DownloadIcon,
            isLoading: false,
            onClick: () => setIsExportModalOpen(true),
            tooltipText: 'Export Plot Configuration',
        },
        {
            svgIcon: UploadIcon,
            isLoading: false,
            onClick: () => setIsImportModalOpen(true),
            tooltipText: 'Import Plot Configuration',
        },
    ];

    return (
        <>
            <MultiColumnPanelContainer buttons={buttons}>
                <div
                    className="w-full max-w-6xl grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
                    onDrop={handleDrop}
                    onDragOver={(e) => e.preventDefault()}
                >
                    {plots.map((plot, index) => (
                        <PlotComponent
                            key={plot.id}
                            id={plot.id}
                            name={plot.name}
                            type={plot.type}
                            traces={plot.traces}
                            max_length={plot.max_length}
                            onRemove={() => handleRemovePlot(plot.id)}
                            onEdit={() => setEditingPlotId(plot.id)}
                            onDragStart={(e) => handleDragStart(e, index)}
                            onDragOver={(e) => handleDragOver(e, index)}
                        />
                    ))}
                </div>

                <PlotModal
                    isOpen={!!editingPlotId}
                    onClose={() => setEditingPlotId(null)}
                    plot={currentEditingPlot}
                    onUpdatePlot={handleUpdatePlot}
                    availableTables={availableTables}
                    getAvailableColumns={getAvailableColumns}
                />

                <ExportModal
                    isOpen={isExportModalOpen}
                    onClose={() => setIsExportModalOpen(false)}
                    plots={plots}
                />

                <ImportModal
                    isOpen={isImportModalOpen}
                    onClose={() => setIsImportModalOpen(false)}
                    onImport={setPlots}
                />
            </MultiColumnPanelContainer>
        </>
    );
};
