'use client';

import { useAlert } from '@/lib/components/client_components/AlertContext';
import {
    useWebSocket,
    WebSocketMessage,
} from '@/lib/components/client_components/WebsocketSubscriptionProvider';
import LoadingIndicator from '@/lib/components/server_components/LoadingIndicator';
import {
    sensorDataBatch,
    sensorDataBatchSchema,
    TableSchemaMap
} from '@/lib/models/autogenerated/generated_models';
import { logMessage } from '@/lib/utils/utilities';
import React, { useEffect, useState } from 'react';
import {
    CartesianGrid,
    Legend,
    Line,
    LineChart,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis,
} from 'recharts';
import { validateWebsocketData } from '@/lib/models/validators';

interface PlotProperties {
    table_name: string;
    column: string;
    // schema: z.ZodSchema
}

interface PlotDataPoint {
    time: Date,
    value: number
}

export function PlotComponentFactory<T>(
    // props: PlotProperties
): (props: PlotProperties) => React.ReactElement<PlotProperties> {
    // }
    // export const TestPlotComponent: React.FC<PlotProperties> = (
    //     props: PlotProperties
    // ) => {
    const PlotComponent = (props: PlotProperties): React.ReactElement<PlotProperties> => {
        const [chartData, setChartData] = useState([]);
        const { registerMessageListener, subscribe, unsubscribe, isConnected } =
            useWebSocket();
        const { showAlert } = useAlert();
        const [websocketDataState, setWebsocketDataState] = useState<
            'connected' | 'waiting' | 'invalid_data'
        >('waiting');

        // This effect registers and unregisters the listener
        useEffect(() => {
            if (!isConnected) return; // Only register if connected

            const listenerId = props.table_name;

            // Register to listen for 'live' messages from 'special_alerts_table'
            const unregister_listener = registerMessageListener(
                listenerId,
                websocketMessageCallback,
                {
                    types: ['live', 'historical'],
                    table: props.table_name,
                }
            );

            subscribe(props.table_name, true, 50);

            return () => {
                unsubscribe(props.table_name);
                unregister_listener(); // Clean up listener when component unmounts or isConnected changes
            };
        }, [isConnected, registerMessageListener]); // Re-register if connection status or register function changes

        const websocketMessageCallback = (message: WebSocketMessage) => {
            logMessage(`Plot received: ${JSON.stringify(message)}`, 'received');

            // let validatedData;
            try {
                const validatedData = validateWebsocketData<T>(
                    message,
                    // props.table_name,
                    // sensorDataBatchSchema
                    TableSchemaMap[props.table_name]
                );

                setWebsocketDataState('connected');

                try {
                    if (validatedData) {
                        if (validatedData.type === 'historical') {
                            const parsedData = parseData(message);
                            setChartData(parsedData);
                        } else if (message.type === 'live') {
                            // const parsedData = parseLiveData(message);
                            const parsedData = parseData(message);
                            setChartData((prevData) => {
                                return [...prevData, ...parsedData].slice(-100);
                            });
                        } else {
                            logMessage(
                                'Received message is not valid data for chart.',
                                'info'
                            );
                        }
                    } else {
                        logMessage('Received message has no data.', 'info');
                    }
                } catch (e) {
                    logMessage('Received message is not valid JSON.', 'info');
                }
            } catch (error) {
                showAlert(
                    `Unvalidated websocket data: ${error.message}`,
                    'error'
                );
                setWebsocketDataState('invalid_data');
                return;
            }
        };

        // const basicApiResponseSchema = z.object({
        //     success: z.boolean(),
        //     message: z.string(),
        // });

        // const parseLiveData = (rawData) => {
        //     if (!rawData || !rawData.data) {
        //         return [];
        //     }
        //     return {
        //         time: new Date(rawData.data.time).toLocaleTimeString(),
        //         value: rawData.data[props.column],
        //     };
        // };

        const parseData = (rawData): Array<PlotDataPoint> => {
            // Check if the data is valid and has a 'data' array
            if (!rawData || !rawData.data || !Array.isArray(rawData.data)) {
                return [];
            }
            // Map the historical data to the format Recharts expects: [{ name: '...', value: ... }]
            return rawData.data.map((item) => ({
                time: new Date(item.time).toLocaleTimeString(),
                value: item[props.column],
            }));
        };

        return (
            <div>
                <h1 className="text-3xl font-bold text-gray-800 mb-6 text-center">
                    {`${props.table_name} : ${props.column}`}
                </h1>
                {chartData.length > 0 ? (
                    <ResponsiveContainer width="100%" height={300}>
                        <LineChart
                            margin={{
                                top: 5,
                                right: 30,
                                left: 20,
                                bottom: 5,
                            }}
                        >
                            <CartesianGrid
                                strokeDasharray="3 3"
                                stroke="#e5e7eb"
                            />
                            <XAxis
                                dataKey="time"
                                stroke="#6b7280"
                                label={{
                                    value: 'Time',
                                    position: 'insideBottom',
                                    offset: -5,
                                }}
                            />
                            <YAxis
                                stroke="#6b7280"
                                label={{
                                    value: 'Temperature',
                                    angle: -90,
                                    position: 'insideLeft',
                                    dy: 45,
                                }}
                            />
                            <Tooltip
                                contentStyle={{
                                    backgroundColor: '#fff',
                                    border: '1px solid #d1d5db',
                                    borderRadius: '8px',
                                }}
                                labelStyle={{ color: '#1f2937' }}
                            />
                            <Legend />
                            <Line
                                data={chartData}
                                key={'time'}
                                type="monotone"
                                dataKey="value"
                                stroke="#8884d8"
                                strokeWidth={2}
                                activeDot={{ r: 8 }}
                                // animateNewValues={false}
                                isAnimationActive={false}
                            />
                        </LineChart>
                    </ResponsiveContainer>
                ) : (
                    <LoadingIndicator
                        text={
                            websocketDataState === 'waiting'
                                ? `WAITING FOR WEBSOCKET`
                                : `WAITING FOR VALID DATA`
                        }
                    />
                )}
            </div>
        );
    };
    return PlotComponent;
};
