'use client';

import { useAlert } from '@/lib/components/client_components/AlertContext';
import {
    useWebSocket,
    WebSocketMessage,
} from '@/lib/components/client_components/WebsocketSubscriptionProvider';
import LoadingIndicator from '@/lib/components/server_components/LoadingIndicator';
import {
    DatabaseData,
    TableSchemaMap
} from '@/lib/models/autogenerated/generated_models';
import { logMessage } from '@/lib/utils/utilities';
import React, { useEffect, useState, useCallback, useRef } from 'react';
import {
    CartesianGrid,
    Legend,
    Line,
    LineChart,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis,
} from 'recharts';
import { validateWebsocketData } from '@/lib/models/validators';
import { chartTraceMetadata } from '@/lib/models/ui_configuration';
// export interface PlotProperties {
//     table_name: string;
//     column: string;
//     max_length?: number
// }

// export interface TraceProperties {
//     table_name: string;
//     column: string;
// }

export interface MultiPlotProperties {
    traces: chartTraceMetadata;//TraceProperties[];
    max_length?: number;
}

interface PlotDataPoint {
    time: Date,
    value: number
}

const colors = [
    '#8884d8',
    '#82ca9d',
    '#ffc658',
    '#ff7300',
    '#00c49f',
    '#ffc658',
];

export function PlotComponentFactory<T extends {stamp: number, [key: string]: unknown}[]>(
// ): () => React.FC<PlotProperties> {
): React.FC<MultiPlotProperties> {
    const PlotComponent: React.FC<MultiPlotProperties> = ({traces, max_length = 100}) => {
        // const PlotComponent: React.FC<MultiPlotProperties> = ({table_name, column, max_length = 100}) => {
        const [chartData, setChartData] = useState([]);
        const [maxLength, setMaxLength] = useState(max_length);
        const [inputValue, setInputValue] = useState(max_length);
        const plotLength = useRef(max_length);

        const { registerMessageListener, subscribe, unsubscribe, isConnected } =
            useWebSocket();
        const { showAlert } = useAlert();
        const [websocketDataState, setWebsocketDataState] = useState<
            'connected' | 'waiting' | 'invalid_data'
        >('waiting');

        useEffect(() => {
            plotLength.current = maxLength;
        }, [maxLength]);

        // This effect handles the WebSocket subscriptions and message listener registration
        useEffect(() => {
            if (!isConnected) return;

            // Use a Set to handle cases where multiple traces are from the same table
            const uniqueTables = new Set(traces.map((t) => t.table_name));
            const listenerId = traces
                .map((t) => `${t.table_name}-${t.column}`)
                .join(',');

            const unregister_listeners: (() => void)[] = [];
            const subscriptions: string[] = [];

            // Register one listener for the entire component
            const unregister_main_listener = registerMessageListener(
                listenerId,
                websocketMessageCallback,
                { types: ['live', 'historical'] }
            );
            unregister_listeners.push(unregister_main_listener);

            // Subscribe to each unique table. This avoids redundant subscriptions.
            uniqueTables.forEach((tableName) => {
                subscribe(tableName, true, maxLength);
                subscriptions.push(tableName);
            });

            // Cleanup function
            return () => {
                subscriptions.forEach((tableName) => unsubscribe(tableName));
                unregister_listeners.forEach((unregister) => unregister());
            };
        // }, [isConnected, traces]);
        }, [isConnected]);

        const websocketMessageCallback = useCallback(
            (message: WebSocketMessage) => {
                logMessage(
                    `Plot received: ${JSON.stringify(message)}`,
                    'debug'
                );

                try {
                    const validatedData = validateWebsocketData<T>(
                        message,
                        TableSchemaMap[message.table]
                    );

                    if (
                        !validatedData ||
                        !validatedData.data ||
                        !Array.isArray(validatedData.data)
                    ) {
                        logMessage('Received message has no data.', 'info');
                        return;
                    }

                    setWebsocketDataState('connected');

                    // Find the traces that match the incoming message's table
                    const tracesToUpdate = traces.filter(
                        (t) => t.table_name === message.table
                    );

                    setChartData((prevData) => {
                        const updatedData = { ...prevData };

                        tracesToUpdate.forEach((trace) => {
                            // <--- FIXED: Looping over only relevant traces
                            const traceId = `${trace.table_name}-${trace.column}`;
                            const currentTraceData = updatedData[traceId] || [];

                            const parsedTraceData = validatedData.data
                                .map((item) => ({
                                    time: new Date(
                                        item.stamp
                                    ).toLocaleTimeString(),
                                    value: item[trace.column] as number,
                                }))
                                .filter(
                                    (point) => typeof point.value === 'number'
                                );

                            const newTraceData = [
                                ...currentTraceData,
                                ...parsedTraceData,
                            ];

                            if (newTraceData.length > plotLength.current) {
                                updatedData[traceId] = newTraceData.slice(
                                    -plotLength.current
                                );
                            } else {
                                updatedData[traceId] = newTraceData;
                            }
                        });

                        return updatedData;
                    });

                    // // Update the state based on the incoming message's table
                    // setChartData((prevData) => {
                    //     const updatedData = { ...prevData };
                    //     const incomingDataMap = new Map();

                    //     // Collect all incoming data points, keyed by time
                    //     validatedData.data.forEach((item) => {
                    //         const time = new Date(
                    //             item.stamp
                    //         ).toLocaleTimeString();
                    //         incomingDataMap.set(time, item);
                    //     });

                    //     traces.forEach((trace) => {
                    //         const traceId = `${trace.table_name}-${trace.column}`;
                    //         const currentTraceData = updatedData[traceId] || [];

                    //         const parsedTraceData = validatedData.data
                    //             .map((item) => ({
                    //                 time: new Date(
                    //                     item.stamp
                    //                 ).toLocaleTimeString(),
                    //                 value: item[trace.column] as number,
                    //             }))
                    //             .filter(
                    //                 (point) => typeof point.value === 'number'
                    //             );

                    //         const newTraceData = [
                    //             ...currentTraceData,
                    //             ...parsedTraceData,
                    //         ];

                    //         if (newTraceData.length > plotLength.current) {
                    //             updatedData[traceId] = newTraceData.slice(
                    //                 -plotLength.current
                    //             );
                    //         } else {
                    //             updatedData[traceId] = newTraceData;
                    //         }
                    //     });

                    //     return updatedData;
                    // });
                } catch (error) {
                    showAlert(
                        `Unvalidated websocket data: ${error.message}`,
                        'error'
                    );
                    setWebsocketDataState('invalid_data');
                }
            },
            [traces, maxLength, showAlert]
        );

        // Handler for applying the new length
        const handleApplyLength = () => {
            const newLength = Number(inputValue);
            if (newLength > 0) {
                setMaxLength(newLength);
            }
        };

        const hasData = Object.values(chartData).some(
            (data) => data.length > 0
        );

        // Recharts expects a single array of objects with keys for each line.
        // We need to merge the separate trace data arrays into a single array for rendering.
        const mergedChartData = () => {
            const dataMap = new Map();
            Object.entries(chartData).forEach(([traceId, dataPoints]) => {
                dataPoints.forEach((point) => {
                    const { time, value } = point;
                    if (!dataMap.has(time)) {
                        dataMap.set(time, { time });
                    }
                    dataMap.get(time)[traceId] = value;
                });
            });
            return Array.from(dataMap.values());
        };

        // const websocketMessageCallbackOld = useCallback(
        //     (message: WebSocketMessage) => {
        //         logMessage(
        //             `Plot received: ${JSON.stringify(message)}`,
        //             'debug'
        //         );

        //         try {
        //             const validatedData = validateWebsocketData<T>(
        //                 message,
        //                 TableSchemaMap[table_name]
        //             );

        //             setWebsocketDataState('connected');

        //             try {
        //                 if (validatedData) {
        //                     if (validatedData.type === 'historical') {
        //                         const parsedData = parseData(message);
        //                         setChartData(parsedData);
        //                     } else if (message.type === 'live') {
        //                         // const parsedData = parseLiveData(message);
        //                         const parsedData = parseData(message);
        //                         setChartData((prevData) => {
        //                             return [...prevData, ...parsedData].slice(
        //                                 -plotLength.current
        //                             );
        //                         });
        //                     } else {
        //                         logMessage(
        //                             'Received message is not valid data for chart.',
        //                             'info'
        //                         );
        //                     }
        //                 } else {
        //                     logMessage('Received message has no data.', 'info');
        //                 }
        //             } catch (e) {
        //                 logMessage(
        //                     'Received message is not valid JSON.',
        //                     'info'
        //                 );
        //             }
        //         } catch (error) {
        //             showAlert(
        //                 `Unvalidated websocket data: ${error.message}`,
        //                 'error'
        //             );
        //             setWebsocketDataState('invalid_data');
        //             return;
        //         }
        //     },
        //     [column, maxLength, showAlert]
        // );

        // const parseData = (rawData): Array<PlotDataPoint> => {
        //     // Check if the data is valid and has a 'data' array
        //     if (!rawData || !rawData.data || !Array.isArray(rawData.data)) {
        //         return [];
        //     }
        //     // Map the historical data to the format Recharts expects: [{ name: '...', value: ... }]
        //     return rawData.data.map((item) => ({
        //         time: new Date(item.stamp).toLocaleTimeString(),
        //         value: item[column],
        //     }));
        // };

        // // Handler for applying the new length
        // const handleApplyLength = () => {
        //     const newLength = Number(inputValue);
        //     if (newLength > 0) {
        //         setMaxLength(newLength);
        //     }
        // };

        return (
            // <div>
            <div className="flex flex-col items-center justify-center  rounded-xl shadow-2xl m-4 border border-gray-700 w-full max-w-2xl">
                <h1 className="text-3xl font-bold text-gray-800 mb-6 text-center">
                    {/* {`${table_name} : ${column}`} */}
                    MULTI TRACE PLOT
                </h1>
                {/* Control panel for the user, now inside the component */}

                {/* <div className="flex items-center gap-4 mb-8">
                    <label
                        htmlFor={`maxLengthInput-${table_name}`}
                        className="text-white text-sm"
                    >
                        Max Plot Length:
                    </label>
                    <input
                        id={`maxLengthInput-${table_name}`}
                        type="number"
                        value={inputValue}
                        onChange={(e) => setInputValue(Number(e.target.value))}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter') handleApplyLength();
                        }}
                        className="w-24 p-2 rounded-md bg-gray-700 text-white border border-gray-600 focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                        min="1"
                    />
                    <button
                        onClick={handleApplyLength}
                        className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                    >
                        Apply
                    </button>
                </div> */}
                <div className="flex items-center gap-4 mb-8">
                    <label
                        htmlFor={`maxLengthInput`}
                        className="text-gray-800 text-sm"
                    >
                        Max Plot Length:
                    </label>
                    <input
                        id={`maxLengthInput`}
                        type="number"
                        value={inputValue}
                        onChange={(e) => setInputValue(Number(e.target.value))}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter') handleApplyLength();
                        }}
                        className="w-24 p-2 rounded-md bg-white text-gray-800 border border-gray-600 focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                        min="1"
                    />
                    <button
                        onClick={handleApplyLength}
                        className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                    >
                        Apply
                    </button>
                </div>

                {/* {chartData.length > 0 ? ( */}
                {hasData ? (
                    <ResponsiveContainer width="100%" height={300}>
                        <LineChart
                            data={mergedChartData()}
                            margin={{
                                top: 5,
                                right: 30,
                                left: 20,
                                bottom: 5,
                            }}
                        >
                            <CartesianGrid
                                strokeDasharray="3 3"
                                stroke="#e5e7eb"
                            />
                            <XAxis
                                dataKey="time"
                                stroke="#6b7280"
                                label={{
                                    value: 'Time',
                                    position: 'insideBottom',
                                    offset: -5,
                                }}
                            />
                            <YAxis
                                stroke="#6b7280"
                                label={{
                                    value: 'Temperature',
                                    angle: -90,
                                    position: 'insideLeft',
                                    dy: 45,
                                }}
                            />
                            <Tooltip
                                contentStyle={{
                                    backgroundColor: '#fff',
                                    border: '1px solid #d1d5db',
                                    borderRadius: '8px',
                                }}
                                labelStyle={{ color: '#1f2937' }}
                            />
                            <Legend />
                            {traces.map((trace, index) => {
                                const traceId = `${trace.table_name}-${trace.column}`;
                                return (
                                    <Line
                                        key={traceId}
                                        type="monotone"
                                        dataKey={traceId}
                                        stroke={colors[index % colors.length]}
                                        strokeWidth={2}
                                        activeDot={{ r: 8 }}
                                        isAnimationActive={false}
                                    />
                                );
                            })}
                            {/* <Line
                                data={chartData}
                                key={'time'}
                                type="monotone"
                                dataKey="value"
                                stroke="#8884d8"
                                strokeWidth={2}
                                activeDot={{ r: 8 }}
                                // animateNewValues={false}
                                isAnimationActive={false}
                            /> */}
                        </LineChart>
                    </ResponsiveContainer>
                ) : (
                    <LoadingIndicator
                        text={
                            websocketDataState === 'waiting'
                                ? `WAITING FOR WEBSOCKET`
                                : `WAITING FOR VALID DATA`
                        }
                    />
                )}
            </div>
        );
    };
    // return PlotComponent;
    return useCallback(() => PlotComponent, [])();
};
