# ./utilities/generate_models.py

import os
import sys
import yaml
import re
import argparse
from pathlib import Path
from typing import Dict, Any, List, Optional
from loguru import logger
from jinja2 import Environment, FileSystemLoader

# Adjust sys.path to ensure 'backend' is recognized as a package root
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.join(current_dir, "..")
backend_root = os.path.join(project_root, "backend")
dashboard_root = os.path.join(project_root, "dashboard")
sys.path.insert(0, project_root)

# --- Configuration ---
SCHEMA_FILE_PATH = os.getenv(
    "SCHEMA_FILE_PATH", os.path.join(project_root, "config", "database_schema.yml")
)
PYDANTIC_GENERATED_MODELS_DIR = os.getenv(
    "GENERATED_MODELS_DIR", os.path.join(backend_root, "api", "autogenerated")
)
PYDANTIC_GENERATED_MODELS_FILE = os.path.join(PYDANTIC_GENERATED_MODELS_DIR, "database_models.py")

ZOD_GENERATED_MODELS_DIR = os.getenv(
    "GENERATED_MODELS_DIR", os.path.join(dashboard_root, "src", "lib", "models", "autogenerated")
)
ZOD_GENERATED_MODELS_FILE = os.path.join(ZOD_GENERATED_MODELS_DIR, "database_models.ts")

# --- Template Configuration ---
TEMPLATE_DIR = os.path.join(current_dir, "templates")
PYDANTIC_TEMPLATE_FILE = "pydantic_database_template.jinja"
ZOD_TEMPLATE_FILE = "zod_database_template.jinja"

# --- Loguru Configuration ---
logger.remove()
logger.add(
    sys.stderr,
    level="INFO",
    format="{time} | {level} | {module}:{function}:{line} - {message}",
    colorize=True,
)

# --- Utility Functions ---
def to_camel_case(snake_case_str: str) -> str:
    """Converts a snake_case string to camelCase."""
    components = snake_case_str.split("_")
    return components[0] + "".join(x.title() for x in components[1:])

def to_pascal_case(snake_case_str: str) -> str:
    """Converts a snake_case string to PascalCase."""
    return "".join(x.title() for x in snake_case_str.split("_"))

def postgres_type_to_zod_type(pg_type: str) -> str:
    """Maps a PostgreSQL type string to a Zod type string."""
    normalized_pg_type = pg_type.upper().strip()
    return ZOD_TYPE_MAPPINGS.get(normalized_pg_type, "z.any()")

def postgres_type_to_ts_type(pg_type: str) -> str:
    """Maps a PostgreSQL type string to a TypeScript type string."""
    normalized_pg_type = pg_type.upper().strip()
    return TS_TYPE_MAPPINGS.get(normalized_pg_type, "any")

# --- PostgreSQL to Python Type Mappings ---
PYDANTIC_TYPE_MAPPINGS = {
    "TEXT": "Optional[str]",
    "TEXT NOT NULL": "str",
    "TEXT NOT NULL UNIQUE": "str",
    "INTEGER": "Optional[int]",
    "INTEGER NOT NULL": "int",
    "SMALLINT": "Optional[int] = None",
    "SMALLINT NOT NULL": "int",
    "DOUBLE PRECISION": "Optional[float] = None",
    "DOUBLE PRECISION NOT NULL": "float",
    "NUMERIC": "Optional[float] = None",
    "NUMERIC NOT NULL": "float",
    "BOOLEAN": "Optional[bool] = None",
    "BOOLEAN NOT NULL": "bool",
    "TIMESTAMPTZ": "Optional[datetime]",
    "TIMESTAMPTZ NOT NULL": "datetime",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "datetime",
    "JSONB": "Optional[Dict[str, Any]]",
    "JSONB NOT NULL": "Dict[str, Any]",
    "UUID": "Optional[UUID]",
    "UUID NOT NULL": "UUID",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "UUID",
}

PYDANTIC_DEFAULT_MAPPINGS = {
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "datetime.utcnow",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "uuid4",
}

# Special handling for tables with list-like columns
PYDANTIC_SPECIAL_TABLE_LIST_FIELDS = {
    "analog_in_data": {
        "read_channels": "List[bool]",
        "values": "List[float]",
        "types": "List[int]",
    },
    "analog_out_data": {
        "write_channels": "List[bool]",
        "values": "List[float]",
    },
    "digital_in_data": {
        "read_channels": "List[bool]",
        "values": "List[bool]",
    },
    "digital_out_data": {
        "write_channels": "List[bool]",
        "values": "List[bool]",
    },
}

def postgres_type_to_python_type(pg_type: str) -> str:
    """
    Maps a PostgreSQL type string to a Python type string.
    """
    normalized_pg_type = pg_type.upper().strip()
    return PYDANTIC_TYPE_MAPPINGS.get(normalized_pg_type, "Any")

def get_default_factory(pg_type: str) -> Optional[str]:
    """
    Returns the default factory function for a given PostgreSQL type.
    """
    normalized_pg_type = pg_type.upper().strip()
    return PYDANTIC_DEFAULT_MAPPINGS.get(normalized_pg_type)

def to_pascal_case(snake_case_str: str) -> str:
    """Converts a snake_case string to PascalCase."""
    return "".join(word.capitalize() for word in snake_case_str.split("_"))

def generate_pydantic_models(schema_file: Path, output_file: Path):
    """
    Generates Pydantic models from a YAML schema definition.
    """
    logger.info(f"Starting Pydantic model generation from '{schema_file}'")

    if not schema_file.exists():
        logger.error(f"Schema file not found: {schema_file}")
        raise FileNotFoundError(f"Schema file not found: {schema_file}")

    # Set up Jinja2 environment and load the template from the file system
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True
    )
    template = env.get_template(PYDANTIC_TEMPLATE_FILE)

    with open(schema_file, "r") as f:
        raw_yaml_data = yaml.safe_load(f)

    static_models_data: List[Dict[str, Any]] = []
    dynamic_base_models_data: List[Dict[str, Any]] = []

    for table_name, table_def in raw_yaml_data.get("tables", {}).items():
        # Check for dynamic tables specified by 'number_of_tables'
        num_tables = table_def.get("number_of_tables")
        if num_tables is not None and isinstance(num_tables, int) and num_tables > 0:
            logger.info(f"Handling dynamic table '{table_name}' with {num_tables} instances.")
            
            base_model_name = to_pascal_case(table_name)
            base_model = {
                "name": base_model_name,
                "table_name": table_name,
                "fields": [],
                "num_instances": num_tables
            }
            
            for col_name, pg_type in table_def.get("columns", {}).items():
                field_type = postgres_type_to_python_type(pg_type)
                default_factory = get_default_factory(pg_type)
                base_model["fields"].append({
                    "name": col_name,
                    "type": field_type,
                    "default_factory": default_factory,
                })
            
            dynamic_base_models_data.append(base_model)
            continue

        # Handle static tables
        model_name = to_pascal_case(table_name)
        columns = table_def.get("columns", {})
        
        fields = []
        is_special_table = table_name in PYDANTIC_SPECIAL_TABLE_LIST_FIELDS
        special_fields = PYDANTIC_SPECIAL_TABLE_LIST_FIELDS.get(table_name, {})
        all_field_names = set(columns.keys())
        
        # Add special list-like fields as single fields first
        if is_special_table:
            for field_name, python_type in special_fields.items():
                fields.append({"name": field_name, "type": python_type, "is_special": True})

        # Add all other fields
        for col_name, pg_type in columns.items():
            if is_special_table and col_name in special_fields:
                continue

            field_type = postgres_type_to_python_type(pg_type)
            default_factory = get_default_factory(pg_type)
            fields.append({
                "name": col_name,
                "type": field_type,
                "default_factory": default_factory,
                "is_special": False
            })

        # Determine the maximum index for computed fields
        computed_fields = []
        if is_special_table:
            max_indices = {field: -1 for field in special_fields}
            for col_name in all_field_names:
                match = re.match(r'^(.+)__(\d+)$', col_name)
                if match:
                    field_name, index_str = match.groups()
                    if field_name in max_indices:
                        max_indices[field_name] = max(max_indices[field_name], int(index_str))

            for field_name, python_type in special_fields.items():
                inner_type = python_type.split("[")[-1].replace("]", "")
                for i in range(max_indices.get(field_name, -1) + 1):
                    computed_field_name = f"{field_name}__{i}"
                    computed_fields.append({
                        "name": computed_field_name,
                        "type": f"Optional[{inner_type}]",
                        "index": i,
                        "source_list": field_name,
                    })

        static_models_data.append({
            "name": model_name,
            "table_name": table_name,
            "fields": fields,
            "is_special_table": is_special_table,
            "special_fields": special_fields,
            "computed_fields": computed_fields,
        })

    # Render the models using the Jinja2 template
    rendered_code = template.render(
        static_models=static_models_data,
        dynamic_base_models=dynamic_base_models_data,
    )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write(rendered_code)

    logger.info(f"Successfully generated Pydantic models to '{output_file}'.")


# --- PostgreSQL to Zod/TypeScript Type Mappings ---
ZOD_TYPE_MAPPINGS = {
    "TEXT": "z.string().optional()",
    "TEXT NOT NULL": "z.string()",
    "TEXT NOT NULL UNIQUE": "z.string()",
    "INTEGER": "z.number().optional()",
    "INTEGER NOT NULL": "z.number()",
    "SMALLINT": "z.number().optional()",
    "SMALLINT NOT NULL": "z.number()",
    "DOUBLE PRECISION": "z.number().optional()",
    "DOUBLE PRECISION NOT NULL": "z.number()",
    "NUMERIC": "z.number().optional()",
    "NUMERIC NOT NULL": "z.number()",
    "BOOLEAN": "z.boolean().optional()",
    "BOOLEAN NOT NULL": "z.boolean()",
    "TIMESTAMPTZ": "z.string().datetime().optional()",
    "TIMESTAMPTZ NOT NULL": "z.string().datetime()",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "z.string().datetime().default(new Date().toISOString())",
    "JSONB": "z.record(z.string(), z.unknown()).optional()",
    "JSONB NOT NULL": "z.record(z.string(), z.unknown())",
    "UUID": "z.string().uuid().optional()",
    "UUID NOT NULL": "z.string().uuid()",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "z.string().uuid().default(crypto.randomUUID())",
}

TS_TYPE_MAPPINGS = {
    "TEXT": "string | undefined",
    "TEXT NOT NULL": "string",
    "TEXT NOT NULL UNIQUE": "string",
    "INTEGER": "number | undefined",
    "INTEGER NOT NULL": "number",
    "SMALLINT": "number | undefined",
    "SMALLINT NOT NULL": "number",
    "DOUBLE PRECISION": "number | undefined",
    "DOUBLE PRECISION NOT NULL": "number",
    "NUMERIC": "number | undefined",
    "NUMERIC NOT NULL": "number",
    "BOOLEAN": "boolean | undefined",
    "BOOLEAN NOT NULL": "boolean",
    "TIMESTAMPTZ": "string | undefined",
    "TIMESTAMPTZ NOT NULL": "string",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "string",
    "JSONB": "Record<string, unknown> | undefined",
    "JSONB NOT NULL": "Record<string, unknown>",
    "UUID": "string | undefined",
    "UUID NOT NULL": "string",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "string",
}

# Special handling for tables with list-like columns
ZOD_SPECIAL_TABLE_LIST_FIELDS = {
    "analog_in_data": {
        "read_channels": {"zod": "z.array(z.boolean())", "ts": "boolean[]", "inner_zod": "z.boolean()", "inner_ts": "boolean"},
        "values": {"zod": "z.array(z.number())", "ts": "number[]", "inner_zod": "z.number()", "inner_ts": "number"},
        "types": {"zod": "z.array(z.number())", "ts": "number[]", "inner_zod": "z.number()", "inner_ts": "number"},
    },
    "digital_in_data": {
        "read_channels": {"zod": "z.array(z.boolean())", "ts": "boolean[]", "inner_zod": "z.boolean()", "inner_ts": "boolean"},
        "values": {"zod": "z.array(z.boolean())", "ts": "boolean[]", "inner_zod": "z.boolean()", "inner_ts": "boolean"},
    },
    "digital_out_data": {
        "write_channels": {"zod": "z.array(z.boolean())", "ts": "boolean[]", "inner_zod": "z.boolean()", "inner_ts": "boolean"},
        "values": {"zod": "z.array(z.boolean())", "ts": "boolean[]", "inner_zod": "z.boolean()", "inner_ts": "boolean"},
    },
}

def generate_zod_models(schema_file: Path, output_file: Path, template_path: Path):
    """
    Generates Zod schemas and TypeScript interfaces from a YAML schema definition
    using a Jinja2 template.
    """
    logger.info(f"Starting Zod model generation from '{schema_file}' using '{template_path}'.")

    if not schema_file.exists():
        logger.error(f"Schema file not found: {schema_file}")
        raise FileNotFoundError(f"Schema file not found: {schema_file}")

    with open(schema_file, "r") as f:
        raw_yaml_data = yaml.safe_load(f)

    # Setup Jinja2 environment
    env = Environment(loader=FileSystemLoader(template_path.parent))
    template = env.get_template(template_path.name)

    # Prepare data for the template
    # models = []
    # --- ADDED: New data structures for separating schema generation from map creation ---
    schemas_to_generate = []
    tables_for_map = []

    for table_name, table_def in raw_yaml_data.get("tables", {}).items():
        fields = []
        is_special_table = table_name in ZOD_SPECIAL_TABLE_LIST_FIELDS

        # Handle all columns, including special and flattened fields
        columns = table_def.get("columns", {})
        
        # Add the core fields from the schema, filtering out old flattened fields
        for col_name, pg_type in columns.items():
            # Skip any fields that are part of the list-like columns or are old flattened fields
            if is_special_table and (col_name in ZOD_SPECIAL_TABLE_LIST_FIELDS[table_name] or re.match(r'.+_\d+$', col_name)):
                continue
            
            fields.append({
                # "name": to_camel_case(col_name),
                "name": col_name,
                "zod_type": postgres_type_to_zod_type(pg_type),
                "ts_type": postgres_type_to_ts_type(pg_type),
            })
            
        if is_special_table:
            special_fields = ZOD_SPECIAL_TABLE_LIST_FIELDS[table_name]
            for field_name, types in special_fields.items():
                # camel_field_name = to_camel_case(field_name)

                # Add the list-based field
                fields.append({
                    # "name": camel_field_name,
                    "name": field_name,
                    "zod_type": types["zod"],
                    "ts_type": types["ts"],
                })

                # Add the flattened fields with the correct __ naming convention
                for i in range(8):
                    flattened_field = f"{field_name}__{i}"
                    
                    fields.append({
                        "name": flattened_field,
                        "zod_type": f"{types['inner_zod']}.optional()",
                        "ts_type": f"{types['inner_ts']} | undefined",
                    })

        # --- ADDED: Logic to populate the two new lists instead ---
        # Create a single model object to generate schema/types
        model_object = {
            "name": to_pascal_case(table_name),
            "camel_case_name": to_camel_case(table_name),
            "fields": fields
        }
        schemas_to_generate.append(model_object)
    
        # Logic for populating the TableSchemaMap entries
        if "number_of_tables" in table_def:
            for i in range(table_def["number_of_tables"]):
                tables_for_map.append({
                    "table_name": f"{table_name}_{i}",
                    "camel_case_name": to_camel_case(table_name),
                })
        else:
            tables_for_map.append({
                "table_name": table_name,
                "camel_case_name": to_camel_case(table_name),
            })
        
    # Render the template
    # rendered_code = template.render(models=models)
    rendered_code = template.render(
        schemas_to_generate=schemas_to_generate,
        tables_for_map=tables_for_map
    )

    # Write the output file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write(rendered_code)

    logger.info(f"Successfully generated Zod models and interfaces to '{output_file}'.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Pydantic and Zod schemas from YAML configuration files.")
    parser.add_argument("--pydantic", action="store_true", help="Generate Pydantic schemas.")
    parser.add_argument("--zod", action="store_true", help="Generate Zod schemas.")
    args = parser.parse_args()
    
    # If neither flag is set, generate both
    if not args.pydantic and not args.zod:
        args.pydantic = True
        args.zod = True

    if args.pydantic:
        try:
            generate_pydantic_models(Path(SCHEMA_FILE_PATH), Path(PYDANTIC_GENERATED_MODELS_FILE))
        except Exception as e:
            logger.error(f"Error during Pydantic model generation: {e}")
    
    if args.zod:
        try:
            template_path = Path(TEMPLATE_DIR) / ZOD_TEMPLATE_FILE
            generate_zod_models(Path(SCHEMA_FILE_PATH), Path(ZOD_GENERATED_MODELS_FILE), template_path)
        except Exception as e:
            logger.error(f"Error during Zod model generation: {e}")

    print("Finished code generation!")
