# generate_schemas.py
import yaml, os, sys, re, argparse
from jinja2 import Environment, FileSystemLoader

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.join(current_dir, "..")
backend_root = os.path.join(project_root, "backend")
dashboard_root = os.path.join(project_root, "dashboard")
sys.path.insert(0, project_root)

PYTHON_TYPE_MAPPINGS = {
    'boolean': 'bool',
    'float': 'float',
    'integer': 'int',
    'number': 'float',
    'string': 'str'
}

ZOD_TYPE_MAPPINGS = {
    'boolean': 'z.boolean()',
    'inteter': 'z.number()',
    'float': 'z.number()',
    'string': 'z.string()'
}

def to_pascal_case(string: str) -> str:
    return "".join(x.title() for x in string.split("_"))
    
def to_camel_case(string: str) -> str:
    components = string.split("_")
    return components[0] + "".join(x.title() for x in components[1:])

def generate_code(schema_name: str, schema_file: str, generate_pydantic: bool, generate_zod: bool):
    """Generates Pydantic and Zod code from the YAML schema."""
    with open(os.path.join(project_root, "config", schema_file), 'r') as f:
        config = yaml.safe_load(f)

    env = Environment(loader=FileSystemLoader(project_root))
    
    env.filters['pascalcase'] = to_pascal_case
    env.filters['camelcase'] = to_camel_case
    
    if generate_pydantic:
        print(f"Rendering Pydantic template for {schema_name}...")
        try:
            pydantic_template = env.get_template(os.path.join("utilities", "templates", "pydantic_config_template.jinja"))
            pydantic_code = pydantic_template.render(schema_name=schema_name, schemas=config['schemas'], type_mappings=PYTHON_TYPE_MAPPINGS)
            # with open(output_file, 'w') as f:
            with open(os.path.join(backend_root,"api", "autogenerated", f"{schema_name}_models.py"), 'w') as f:
                f.write(pydantic_code)
        except Exception as e:
            print(f"Error during Pydantic rendering: {e}")
            # You can also print the data that caused the error
            # This requires a more complex template modification for logging
            raise  # Re-raise the exception to see the full traceback


    # Load and render Zod template
    if generate_zod:
        print(f"Rendering Zod template for {schema_name}...")
        try:
            zod_template = env.get_template(os.path.join("utilities", "templates", "zod_config_template.jinja"))
            zod_code = zod_template.render(schema_name=schema_name, schemas=config['schemas'], type_mappings=ZOD_TYPE_MAPPINGS)
            with open(os.path.join(dashboard_root, "src","lib","models","autogenerated", f"{schema_name}_models.ts"), 'w') as f:
                f.write(zod_code)
        except Exception as e:
            print(f"Error during Zod rendering: {e}")
            raise

    print("Finished code generation!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Pydantic and Zod schemas from YAML configuration files.")
    parser.add_argument("--pydantic", action="store_true", help="Generate Pydantic schemas.")
    parser.add_argument("--zod", action="store_true", help="Generate Zod schemas.")
    args = parser.parse_args()
    
    # If neither flag is set, generate both
    if not args.pydantic and not args.zod:
        args.pydantic = True
        args.zod = True

    schemas_to_generate = [
        {
            "schema_name": "configuration",
            "schema_file": "config_schemas.yml",
        },
        # {
        #     "schema_name": "io_configuration",
        #     "schema_file": "io_config_schemas.yml",
        #     # "output_file": os.path.join(dashboard_root, "src","lib","models","autogenerated", "ui_config_models.ts")
        # },
    ]

    [generate_code(**schema, generate_pydantic=args.pydantic, generate_zod=args.zod) for schema in schemas_to_generate]