# ./utilities/generate_models.py

import os
import sys
import yaml
from pathlib import Path
from typing import Dict, Any, List, Optional
from loguru import logger
from jinja2 import Environment, FileSystemLoader

# Adjust sys.path to ensure 'backend' is recognized as a package root
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.join(current_dir, "..")
backend_root = os.path.join(project_root, "backend")
sys.path.insert(0, project_root)

# --- Configuration ---
SCHEMA_FILE_PATH = os.getenv(
    "SCHEMA_FILE_PATH", os.path.join(project_root, "config", "schema.yml")
)
GENERATED_MODELS_DIR = os.getenv(
    "GENERATED_MODELS_DIR", os.path.join(backend_root, "api", "autogenerated")
)
GENERATED_MODELS_FILE = os.path.join(GENERATED_MODELS_DIR, "generated_models.py")

# --- Template Configuration ---
TEMPLATE_DIR = os.path.join(current_dir, "templates")
TEMPLATE_FILE = "pydantic_models.py.j2"

# --- Loguru Configuration ---
logger.remove()
logger.add(
    sys.stderr,
    level="INFO",
    format="{time} | {level} | {module}:{function}:{line} - {message}",
    colorize=True,
)

# --- PostgreSQL to Python Type Mappings ---
TYPE_MAPPINGS = {
    "TEXT": "Optional[str]",
    "TEXT NOT NULL": "str",
    "TEXT NOT NULL UNIQUE": "str",
    "INTEGER": "Optional[int]",
    "INTEGER NOT NULL": "int",
    "SMALLINT": "Optional[int]",
    "SMALLINT NOT NULL": "int",
    "DOUBLE PRECISION": "Optional[float]",
    "DOUBLE PRECISION NOT NULL": "float",
    "NUMERIC": "Optional[float]",
    "NUMERIC NOT NULL": "float",
    "BOOLEAN": "Optional[bool]",
    "BOOLEAN NOT NULL": "bool",
    "TIMESTAMPTZ": "Optional[datetime]",
    "TIMESTAMPTZ NOT NULL": "datetime",
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "datetime",
    "JSONB": "Optional[Dict[str, Any]]",
    "JSONB NOT NULL": "Dict[str, Any]",
    "UUID": "Optional[UUID]",
    "UUID NOT NULL": "UUID",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "UUID",
}

DEFAULT_MAPPINGS = {
    "TIMESTAMPTZ NOT NULL DEFAULT NOW()": "datetime.utcnow",
    "UUID PRIMARY KEY DEFAULT gen_random_uuid()": "uuid4",
}

# Special handling for tables with list-like columns
SPECIAL_TABLE_LIST_FIELDS = {
    "analog_in_data": {
        "read_channels": "List[bool]",
        "values": "List[float]",
        "types": "List[int]",
    },
    "digital_in_data": {
        "read_channels": "List[bool]",
        "values": "List[bool]",
    },
    "digital_out_data": {
        "write_channels": "List[bool]",
        "values": "List[bool]",
    },
}


def postgres_type_to_python_type(pg_type: str) -> str:
    """
    Maps a PostgreSQL type string to a Python type string.
    """
    normalized_pg_type = pg_type.upper().strip()
    return TYPE_MAPPINGS.get(normalized_pg_type, "Any")


def get_default_factory(pg_type: str) -> Optional[str]:
    """
    Returns the default factory function for a given PostgreSQL type.
    """
    normalized_pg_type = pg_type.upper().strip()
    return DEFAULT_MAPPINGS.get(normalized_pg_type)


def to_pascal_case(snake_case_str: str) -> str:
    """Converts a snake_case string to PascalCase."""
    return "".join(word.capitalize() for word in snake_case_str.split("_"))


def generate_pydantic_models(schema_file: Path, output_file: Path):
    """
    Generates Pydantic models from a YAML schema definition.
    """
    logger.info(f"Starting Pydantic model generation from '{schema_file}'")

    if not schema_file.exists():
        logger.error(f"Schema file not found: {schema_file}")
        raise FileNotFoundError(f"Schema file not found: {schema_file}")

    # Set up Jinja2 environment and load the template from the file system
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True
    )
    template = env.get_template(TEMPLATE_FILE)

    with open(schema_file, "r") as f:
        raw_yaml_data = yaml.safe_load(f)

    models_data: List[Dict[str, Any]] = []

    for table_name, table_def in raw_yaml_data.get("tables", {}).items():
        model_name = to_pascal_case(table_name)
        columns = table_def.get("columns", {})

        fields = []
        all_field_names = set(columns.keys())

        is_special_table = table_name in SPECIAL_TABLE_LIST_FIELDS
        special_fields = SPECIAL_TABLE_LIST_FIELDS.get(table_name, {})

        if is_special_table:
            for field_name, python_type in special_fields.items():
                fields.append(
                    {"name": field_name, "type": python_type, "is_special": True}
                )

            for col_name, pg_type in columns.items():
                if col_name in special_fields:
                    continue

                field_type = postgres_type_to_python_type(pg_type)
                default_factory = get_default_factory(pg_type)

                fields.append(
                    {
                        "name": col_name,
                        "type": field_type,
                        "default_factory": default_factory,
                        "is_special": False,
                    }
                )

        else:
            for col_name, pg_type in columns.items():
                field_type = postgres_type_to_python_type(pg_type)
                default_factory = get_default_factory(pg_type)

                fields.append(
                    {
                        "name": col_name,
                        "type": field_type,
                        "default_factory": default_factory,
                        "is_special": False,
                    }
                )

        computed_fields = []
        if is_special_table:
            for field_name, python_type in special_fields.items():
                inner_type = python_type.split("[")[-1].replace("]", "")
                for i in range(8):
                    computed_field_name = f"{field_name}__{i}"

                    if computed_field_name in all_field_names:
                        logger.warning(
                            f"Skipping computed field '{computed_field_name}' "
                            f"for table '{table_name}' to avoid name conflict with "
                            f"a regular column defined in the schema."
                        )
                        continue

                    computed_fields.append(
                        {
                            "name": computed_field_name,
                            "type": f"Optional[{inner_type}]",
                            "index": i,
                            "source_list": field_name,
                        }
                    )

        models_data.append(
            {
                "name": model_name,
                "table_name": table_name,
                "fields": fields,
                "is_special_table": is_special_table,
                "special_fields": special_fields,
                "computed_fields": computed_fields,
            }
        )

    # Render the models using the Jinja2 template
    rendered_code = template.render(
        models=models_data, special_table_list_fields=SPECIAL_TABLE_LIST_FIELDS
    )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write(rendered_code)

    logger.info(f"Successfully generated Pydantic models to '{output_file}'.")


if __name__ == "__main__":
    try:
        generate_pydantic_models(Path(SCHEMA_FILE_PATH), Path(GENERATED_MODELS_FILE))
    except Exception as e:
        logger.error(f"Error during Pydantic model generation: {e}")
        sys.exit(1)
