import { createAPIResponse } from '@/lib/models/api_models';
import { authentication_enabled, debug_mode, logMessage, validateAuthentication } from '@/lib/utils/utilities';
import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { capturedImageType } from '@/lib/models/autogenerated/configuration_models';
import { auth } from '@/auth';

// async function handler(
//     request: NextRequest,
//     { params }: { params: { slug: string[] } }
// ) {
//     logMessage(
//         `Received ${request.method} request to /backend/${params.slug.join('/')}`,
//         'debug'
//     );

//     if (authentication_enabled() && !(await validateAuthentication())) {
//         logMessage(
//             `Unauthenicated ${request.method} request on /backend/${params.slug.join('/')}`,
//             'error'
//         );
//         return createAPIResponse({
//             authenticated: false,
//         });
//     }

//     try {
//         return await proxyBackendRequest({
//             request: request,
//             slug: params.slug,
//         });
//     } catch (e) {
//         return handleError(e, request, params.slug);
//     }
// }

// export { handler as GET, handler as POST };

interface ImageDetail {
    name: string;
    mimeType: string;
    dataUrl: string; // Base64 encoded string usable directly in the <img> src attribute
}

export async function GET(
    request: NextRequest // Changed signature for App Router handler
) {
    if (authentication_enabled() && !(await validateAuthentication())) {
        logMessage(
            `Unauthenicated ${request.method} request on /api/images}`,
            'error'
        );
        return createAPIResponse({
            authenticated: false,
        });
    }
    
    // Define the relative path to the image directory.
    const imagesDir: string = path.join(process.cwd(), '..', 'tests', 'test_images');

    // 1. Get the limit parameter from the URL search parameters (NextRequest method)
    const limitQuery: string | null = request.nextUrl.searchParams.get('limit');

    // Parse limit, default to 5 if not provided or invalid
    const limit: number = limitQuery ? parseInt(limitQuery, 10) : 3;

    if (isNaN(limit) || limit <= 0) {
        // Return response using NextResponse for App Router
        return createAPIResponse({
                authenticated: true,
                backend_response: {
                    success: false,
                    message: "Invalid limit query."
                    // data: ''
                },
                // proxy_error: false,
                // proxy_error_string: '',
            }, 400);
        // return NextResponse.json(
        //     {
        //         success: false,
        //         message:
        //             'Invalid limit parameter provided. Must be a positive integer.',
        //     } as ErrorResponse,
        //     { status: 400 }
        // );
    }

    try {
        // 2. Read all files in the directory
        const fileNames: string[] = await fs.readdir(imagesDir);

        // 3. Filter for common image extensions
        const imageExtensions: string[] = [
            '.jpg',
            '.jpeg',
            '.png',
            '.gif',
            '.webp',
        ];
        const imageFiles: string[] = fileNames.filter((fileName) =>
            imageExtensions.some((ext) => fileName.toLowerCase().endsWith(ext))
        );

        // 4. Limit the number of files returned
        const filesToRead: string[] = imageFiles.slice(0, limit);

        // 5. Read the content of each selected image file
        const imageDataPromises: Promise<capturedImageType>[] = filesToRead.map(
            async (fileName) => {
                const filePath: string = path.join(imagesDir, fileName);

                // Read the file content as a Buffer
                const fileBuffer: Buffer = await fs.readFile(filePath);
                const base64Data: string = fileBuffer.toString('base64');

                // Infer MIME type based on extension
                const extension: string = path.extname(fileName).toLowerCase();
                let mimeType: string = 'application/octet-stream';

                if (extension === '.png') {
                    mimeType = 'image/png';
                } else if (extension === '.gif') {
                    mimeType = 'image/gif';
                } else if (extension === '.webp') {
                    mimeType = 'image/webp';
                } else {
                    // Default for jpg/jpeg
                    mimeType = 'image/jpeg';
                }

                const capturedImage: capturedImageType = {
                    id: fileName,
                    timestamp: new Date().toISOString(),
                    status: 'fail',
                    defect_types: ['hole', 'paint'],
                    confidence: 95,
                    batch_id: 'batch',
                    // mimeType: mimeType,
                    image_src: `data:${mimeType};base64,${base64Data}`,
                };

                return capturedImage;
            }
        );

        // Resolve all promises to get the final list of image objects
        const images: capturedImageType[] =
            await Promise.all(imageDataPromises);

        // 6. Return a successful JSON response using NextResponse
        return createAPIResponse({
            // success: true,
            authenticated: true,
            backend_response: {
                success: true,
                data: {images: images}
            }
        })
        // const responseData: ApiResponse = {
        //     success: true,
        //     count: images.length,
        //     images: images,
        // };
        // return NextResponse.json(responseData, { status: 200 });
    } catch (error) {
        console.error('Error fetching images from disk:', error);
        // 7. Handle errors (e.g., directory not found, file read error) using NextResponse
        const errorMessage =
            error instanceof Error ? error.message : 'Unknown error occurred.';

        return createAPIResponse({
            authenticated: true,
            backend_response: {
                success: false,
                message: 'Failed to read images from server disk.',
                data: errorMessage
            },
        }, 500);
        // const errorData: ErrorResponse = {
        //     success: false,
        //     message: 'Failed to read images from server disk.',
        //     error: errorMessage,
        // };
        // return NextResponse.json(errorData, { status: 500 });
    }
}