# from flask import Flask, jsonify
from fastapi import FastAPI
import uvicorn, os, re
import subprocess

from typing import List, Dict
from loguru import logger

from common_models.autogenerated.system_models import ApiResponse, HostServicesError, NetworkInterfaceDefinition
from common_models.models import NetworkInterfaces
from backend.utilities.system_utilities import is_running_in_docker

ra_host_service_server = FastAPI()

def get_interfaces() -> NetworkInterfaces:
    output_string = subprocess.check_output(
        ["nmcli", "dev", "show"], text=True, stderr=subprocess.PIPE
    )

    # interfaces_by_type: Dict[str, List[str]] = {}
    interfaces: List[NetworkInterfaces] = []

    # Regex to find a block for a device. We'll capture the device name and the rest of the block.
    # The pattern looks for 'GENERAL.DEVICE:', captures the device name, and then captures
    # everything until the next 'GENERAL.DEVICE:' or the end of the string.
    device_blocks = re.findall(r"GENERAL\.DEVICE:\s+(.*?)\n(.*?)(?=\nGENERAL\.DEVICE:|\Z)", output_string, re.DOTALL)
    
    for device_name, block in device_blocks:
        device_name = device_name.strip()

        # Use regex to find the GENERAL.TYPE line and capture the type.
        type_match = re.search(r"GENERAL\.TYPE:\s+(.+)", block)
        interface_type = type_match.group(1).strip() if type_match else "unknown"
        
        # Use regex to find the IP4.ADDRESS line and capture the IP address.
        # This will be None if no IP address is found.
        ip_match = re.search(r"IP4\.ADDRESS\[\d+\]:\s+([\d.]+)", block)
        ip_address = ip_match.group(1).strip() if ip_match else None
        
        # Use regex to find the SSID for wireless interfaces.
        ssid = None
        if interface_type == "wifi":
            ssid_match = re.search(r"GENERAL\.CONNECTION:\s+(.+)", block)
            if ssid_match and ssid_match.group(1).strip() != '--':
                ssid = ssid_match.group(1).strip()

        interfaces.append(NetworkInterfaceDefinition(
            name=device_name,
            type=interface_type,
            address=ip_address,
            ssid=ssid
        ))

        # # Add the device to the list for its type
        # if interface_type not in interfaces_by_type:
        #     interfaces_by_type[interface_type] = []
        
        # interfaces_by_type[interface_type].append(NetworkInterfaceDefinition(
        #     name=device_name,
        #     type=interface_type,
        #     address=ip_address,
        #     ssid=ssid
        # ))

    return NetworkInterfaces(interfaces=interfaces)

def connected_ssids() -> List[str]:
    interfaces = get_interfaces()
    return [interface.ssid for interface in interfaces.interfaces if interface.ssid is not None]

def wifi_interface_names() -> List[str]:
    interfaces = get_interfaces()
    return [interface.name for interface in interfaces.interfaces if interface.type == 'wifi']

def ethernet_interface_names() -> List[str]:
    interfaces = get_interfaces()
    return [interface.name for interface in interfaces.interfaces if interface.type == 'ethernet']

def get_interface_ip(interface_name: str) -> str | None:
    interfaces = get_interfaces()
    return interfaces.get_interface_ip(interface_name=interface_name)

def get_default_wifi_adapter() -> str | None:
    wifi_interfaces = wifi_interface_names()
    if len(wifi_interfaces) > 0:
        return wifi_interfaces[0]
    return None

@ra_host_service_server.get("/interfaces")
def get_available_interfaces() -> ApiResponse:
    return ApiResponse(
        message="Retrieved interface names",
        success=True,
        # error=False,
        data=get_interfaces()
    )

@ra_host_service_server.get("/connected_ssids")
def get_connected_ssids():
    return ApiResponse(
        success=True,
        # message=None,
        data=connected_ssids()
    )

@ra_host_service_server.get("/scan")
def scan_wifi():
    try:
        default_wifi_adapter = get_default_wifi_adapter()

        # For now assume only one wifi interface and take the first one
        if default_wifi_adapter is not None:
            if is_running_in_docker():
                # if os.environ["CONTAINERIZED"].lower() == "true":
                output = subprocess.check_output(
                    ["iwlist", default_wifi_adapter, "scanning"], text=True, stderr=subprocess.PIPE
                )
            else:
                output = subprocess.check_output(
                    ["sudo", "iwlist", default_wifi_adapter, "scanning"],
                    text=True,
                    stderr=subprocess.PIPE,
                )

            ssid_output = [
                line.strip()
                for line in output.splitlines()
                if line.strip() and line.strip().startswith("ESSID")
            ]
            ssids = [str(ssid.split(":")[1].replace('"', "")) for ssid in ssid_output]

            return ApiResponse(success=True, message='', data=ssids)
        else:
            return ApiResponse(success=False, message='No Wi-Fi adapters available')

    except subprocess.CalledProcessError as e:
        return ApiResponse(
            success=False,
            message="Wi-Fi scanning error.",
            data=HostServicesError(
                description="Subprocess error scanning Wi-Fi networks",
                details=str(e),
                stderr=e.stderr,
            ),
        )
    except Exception as e:
        return ApiResponse(
            success=False,
            message="Wi-Fi scanning error.",
            data=HostServicesError(
                description=f"Failed scanning Wi-Fi networks",
                details=f"{e}",
            ),
        )

@ra_host_service_server.get("/wifi_ip")
def wifi_ip():
    default_wifi_adapter = get_default_wifi_adapter()
    if default_wifi_adapter is not None:
        wifi_ip = get_interface_ip(interface_name=default_wifi_adapter)
        return ApiResponse(success=True, message='', data=wifi_ip)
    else:
        return ApiResponse(success=False, message="No Wi-Fi adapters found.")

    # try:
    #     return ApiResponse(error=False, data=get_interface_ip(interface_name="wlan0"))
    # except subprocess.CalledProcessError as e:
    #     return ApiResponse(
    #         error=True,
    #         error_details=HostServicesError(
    #             description="Subprocess error when getting Wi-Fi IP address",
    #             details=str(e),
    #             stderr=e.stderr,
    #         ),
    #     )
    # except Exception as e:
    #     return ApiResponse(
    #         error=True,
    #         error_details=HostServicesError(
    #             description=f"Failed to get Wi-Fi IP address",
    #             details=f"{e}",
    #         ),
    #     )




@ra_host_service_server.get("/ethernet_ips")
def ethernet_ips() -> ApiResponse:
    interfaces = get_interfaces()
    return ApiResponse(
        success=True,
        message=None,
        data=[i for i in interfaces.ethernet_interfaces if i.address is not None]
    )
    
    # try:
    #     return ApiResponse(error=False, data=get_interface_ip(interface_name="eth1"))
    # except subprocess.CalledProcessError as e:
    #     return ApiResponse(
    #         error=True,
    #         error_details=HostServicesError(
    #             description="Subprocess error when getting ethernet IP address",
    #             details=str(e),
    #             stderr=e.stderr,
    #         ),
    #     )
    # except Exception as e:
    #     return ApiResponse(
    #         error=True,
    #         error_details=HostServicesError(
    #             description=f"Failed to get ethernet IP address",
    #             details=f"{e}",
    #         ),
    #     )


@ra_host_service_server.post("/connect_wifi")
def connect_wifi(ssid: str, password: str) -> ApiResponse:
    try:
        active_ssids = connected_ssids()
        # Assume only one connection
        if len(active_ssids) > 0 and ssid in active_ssids:
            return ApiResponse(success=False, message=f"Wi-Fi already connected to {ssid}")
        # current_ssid = get_current_ssid()

        # if current_ssid == ssid:
        #     return ApiResponse(error=False, data={"already_connected": True})

        if is_running_in_docker():
        # if os.environ["CONTAINERIZED"].lower() == "true":
            output = subprocess.check_output(
                [
                    "nmcli",
                    "dev",
                    "wifi",
                    # get_default_wifi_adapter(),
                    "connect",
                    f"{ssid}",
                    "password",
                    f"{password}",
                ],
                text=True,
                stderr=subprocess.PIPE,
            )
        else:
            output = subprocess.check_output(
                [
                    "sudo",
                    "nmcli",
                    "dev",
                    "wifi",
                    # get_default_wifi_adapter(),
                    "connect",
                    f"{ssid}",
                    "password",
                    f"{password}",
                ],
                text=True,
                stderr=subprocess.PIPE,
            )

        connect_output = [line.strip() for line in output.splitlines() if line.strip()]
        if any(["successfully activated" in s for s in connect_output]):
            return ApiResponse(success=True, data={"connect_success": True})
        else:
            return ApiResponse(success=False, data={"connect_success": False})

    except subprocess.CalledProcessError as e:
        return ApiResponse(
            # error=True,
            success=False,
            data=HostServicesError(
                description=f"Subprocess error when connecting to Wi-Fi network {ssid}",
                details=str(e),
                stderr=e.stderr,
            ),
        )
    except Exception as e:
        return ApiResponse(
            # error=True,
            success=False,
            data=HostServicesError(
                description=f"Failed to connect to Wi-Fi network {ssid}",
                details=f"{e}",
            ),
        )


if __name__ == "__main__":
    logger.info(f"Starting host services API...")
    uvicorn.run(
        ra_host_service_server,
        host="0.0.0.0",
        port=int(os.environ.get("HOST_SERVICES_PORT", 8001)),
        timeout_keep_alive=0,
        log_level="warning",
    )
