import { ioConfigurationType, uiConfigurationType } from "@/lib/models/autogenerated/configuration_models";
import { v4 as uuidv4 } from 'uuid'; // Import uuid for generating default component IDs

export const DEFAULT_UI_CONFIG: uiConfigurationType = {
    theme: 'system', // Default from schema
    // layout: {
    //     sidebarEnabled: true, // Default from schema
    //     headerHeight: 80, // Default from schema, within min/max bounds
    // },
    components: [
        // At least one component is required by .min(1)
        {
            id: uuidv4(), // Generate a unique ID for the default component
            type: 'jogging',
            label: 'Welcome Widget',
            metadata: {
                message:
                    'This is a default widget. Please save your configuration to customize.',
                version: '1.0.0',
                pace: 5,
            },
        },
    ],
    plots: [],
    lastUpdated: new Date().toISOString(), // Current timestamp in ISO format
};

export const DEFAULT_IO_CONFIG: ioConfigurationType = {
    racks: [],
    lastUpdated: new Date().toISOString(),
};