import itertools
from pydantic import BaseModel, Field
from typing import Dict, List, Optional, Any
from r2_backend_models.autogenerated.system_models import (
    BaseNetworkInterfaces,
    NetworkInterfaceDefinition,
)


class NetworkInterfaces(BaseNetworkInterfaces):
    @property
    def interface_types(self) -> List[str]:
        return set([i.type for i in self.interfaces])

    @property
    def interface_names(self) -> List[str]:
        return [i.name for i in self.interfaces]

    @property
    def ethernet_interfaces(self) -> List[NetworkInterfaceDefinition]:
        return [i for i in self.interfaces if i.type == "ethernet"]

    def get_interface_ip(self, interface_name: str) -> str | None:
        for interface in self.interfaces:
            if interface_name == interface.name:
                return interface.address
        return None
