# This YAML defines the structure and validation rules for the schema.
# The Python script will use this to generate code for both TypeScript (Zod) and Python (Pydantic).
schemas:
  #############
  ## UI Schemas
  #############

  jogging_metadata:
    type: object
    properties:
      message: { type: string }
      version: { type: string }
      pace:
        type: float
        validations: { min: 5 }

  chart_trace_metadata:
    # type: array
    # elements:
    type: object
    properties:
      table_name: { type: string }
      column: { type: string }
      color: { type: string }

  plot_configuration:
    type: object
    properties:
      id: { type: uuid }
      name: { type: string }
      type:
        type: enum
        valid_values: [line, bar, scatter]
      traces: 
        type: array
        elements: { ref: chart_trace_metadata }
      max_length:
        type: number
        optional: true

  plot_configurations:
    type: array
    elements: { ref: plot_configuration }

  image_archive_metadata:
    type: object
    properties:
      number_of_images: { type: number }
      # src:
      #   type: string
      #   validations: { url: true }
      # altText:
      #   type: string
      #   validations: { minlength: 1 }
      # caption:
      #   type: string
      #   optional: true

  camera_metadata:
    type: object
    properties:
      source: { type: string }
  
  training_metadata:
    type: object
    properties:
      source: { type: string }

  vision_statistics_metadata:
    type: object
    properties:
      refresh_interval: { type: number }
      time_span: { type: number }
      defects_to_analyze:
        type: array
        elements: { type: string }

  jogging_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: jogging }
      metadata: { ref: jogging_metadata }
  
  chart_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: charts }
      metadata: { ref: plot_configuration }

  image_archive_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: image }
      metadata: { ref: image_archive_metadata }

  camera_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: camera }
      metadata: { ref: camera_metadata }

  training_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: training }
      metadata: { ref: training_metadata }

  vision_statistics_component:
    type: object
    properties:
      id: { type: uuid }
      label:
        type: string
        validations: { minlength: 1 }
      type: { type: literal, value: vision_statistics }
      metadata: { ref: vision_statistics_metadata }

  ui_component:
    type: union
    discriminator: type
    variants:
      - jogging_component
      - chart_component
      - image_archive_component
      - training_component
      - camera_component
      - vision_statistics_component

  ui_configuration:
    type: object
    properties:
      theme:
        type: enum
        valid_values: [light, dark, system]
        default: system
      # layout:
      #   type: object
      #   properties:
      #     sidebarEnabled:
      #       type: boolean
      #       default: true
      #     headerHeight:
      #       type: number
      #       validations: { min: 50, max: 200 }
      #       default: 80
      components:
        type: array
        elements: { ref: ui_component }
        validations: { min_items: 0 }
        default: []
      # plots: { ref: plot_configurations }
      plots:
        type: array
        elements: { ref: plot_configuration }
        default: []
      last_updated:
        type: datetime
        # validations: { datetime: true }
        default: ''

  # ui_config_api_response:
  #   type: object
  #   properties:
  #     client_id: { type: string }
  #     config_data: { ref: ui_configuration }
  #     last_updated:
  #       type: string
  #       validations: { datetime: true, precision: 6 }
  
  #############
  ## IO Schemas
  #############
  io_point_description:
    type: object
    properties:
      label: { type: string }
      type:
        type: enum
        valid_values: [DI, DO, AI, AO]

  io_point:
    type: object
    properties:
      id: { type: string }
      point_type: { ref: io_point_description }
      point_value:
          type: union
          variants: [float, boolean]

  io_module_description:
    type: object
    properties:
      name: { type: string }
      icon: { type: string }
      points:
        type: array
        elements: { ref: io_point_description }

  io_module:
    type: object
    properties:
      id: { type: string }
      name: { type: string }
      type: { ref: io_module_description }
      points:
        type: array
        elements: { ref: io_point }
  
  io_rack_config:
    type: object
    properties:
      name: { type: string }
      address: { type: string }
      max_modules:
        type: integer
        validations: { minimum: 1 }
  
  io_rack:
    type: object
    properties:
      id: { type: string }
      modules:
        type: array
        elements: { ref: io_module }
      rack_config: { ref: io_rack_config }
  
  io_configuration:
    type: object
    properties:
      racks:
        type: array
        elements: { ref: io_rack }
        default: []
      last_updated:
        type: datetime
        # type: string
        # validations: { datetime: true }
        default: ''

  ##############
  ## OPC Schemas
  ##############
  opc_data_point:
    type: object
    properties:
      id: { type: string }
      name: { type: string }
      node_id: { type: string }
      is_writable: { type: boolean }
  
  opc_subscription_group:
    type: object
    properties:
      id: { type: string }
      name: { type: string }
      endpoint: { type: string }
      interval: { type: integer }
      data_points:
        type: array
        elements: { ref: opc_data_point }
  
  opc_configuration:
    type: object
    properties:
      subscription_groups:
        type: array
        elements: { ref: opc_subscription_group }
        default: []
      last_updated:
        # type: string
        type: datetime
        # validations: { datetime: true }
        default: ''

  ###################
  ## Combined Schemas
  ###################

  full_configuration:
    type: object
    properties:
      client_id: { type: string }
      ui_configuration: { ref: ui_configuration }
      io_configuration: { ref: io_configuration }
      opc_configuration: { ref: opc_configuration }