database:
  database_synchronization_period_sec: 2
  synchronization_batch_size: 100
  queue_length_warning_threshold: 10
  queue_get_timeout_secs: 0.1

  collections:
    sensor_data:
      document_type: SENSOR_DATA
      drop_on_start: False
    events:
      document_type: EVENT
      drop_on_start: False
    frontend_messages:
      document_type: FRONTEND_MESSAGE
      drop_on_start: False
      capped: True
      collection_size_bytes: 1000
    io_state:
      document_type: IO_STATE
      drop_on_start: False
      capped: False
      collection_size_bytes: 10000
    analog_input_state:
      document_type: ANALOG_INPUT_STATE
      drop_on_start: False
      capped: False
      collection_size_bytes: 10000
    digital_input_state:
      document_type: DIGITAL_INPUT_STATE
      drop_on_start: False
      capped: False
      collection_size_bytes: 10000
    hardware_configuration:
      document_type: SYSTEM_CONFIGURATION
      drop_on_start: True
    ui_configuration:
      document_type: UI_CONFIGURATION
      drop_on_start: False
      # capped: True
      # collection_size_bytes: 1000

  local:
    enabled: True
    connection_timeout_ms: 1000
    socket_timeout_ms: 5000
    server_selection_timeout_ms: 5000
    cycle_count_before_yield: 150
    host: 127.0.0.1
    port: 27017
    username: r2
    password: password
    database_name: ra_data
    drop_database_on_start: False
  
  cloud:
    enabled: False
    connection_timeout_ms: 1000
    socket_timeout_ms: 15000
    server_selection_timeout_ms: 10000
    cycle_count_before_yield: 5
    host: 172.25.0.51
    port: 27017
    username: r2
    password: password
    database_name: cloud_ra_data
    drop_database_on_start: False