# Tihs file was autogenerated from config_schemas.yml.
# DO NOT EDIT MANUALLY

from __future__ import annotations
from typing import Literal, Union, List, Optional, Any
from pydantic import BaseModel, Field, field_serializer, ConfigDict
from datetime import datetime, timezone
from functools import partial
import uuid

# MODELS FOR SYSTEM


class ApiResponse(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    message: Optional[str] = None
    success: bool = Field(...)
    data: Optional[Any] = None

class NetworkInterfaceDefinition(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    name: str = Field(...)
    address: Optional[str] = None
    type: str = Field(...)
    ssid: Optional[str] = None

class HostServicesError(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    description: str = Field(...)
    details: Optional[str] = None
    stderr: Optional[str] = None

class BaseNetworkInterfaces(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    interfaces: List[NetworkInterfaceDefinition] = Field(...)
