// Frontend Web Application for RA Products
// Developed by R2 Labs

'use client';

import React, {
    Dispatch,
    ReactNode,
    SetStateAction,
    useContext,
    useEffect,
    useState,
} from 'react';

import { useAlert } from '@/lib/components/client_components/AlertContext';
import { R2Button } from '@/lib/components/client_components/ClickButton';
import {
    LoadingButton,
    SliderToggle,
} from '@/lib/components/client_components/Controls';
import { DashboardContext } from '@/lib/components/client_components/DashboardContextWrapper';
import { Modal } from '@/lib/components/client_components/Modal';
import LoadingIndicator from '@/lib/components/server_components/LoadingIndicator';
import { SimplifiedDashboardHeaderContainer } from '@/lib/components/server_components/SimplifiedDashboardHeaderContainer';
import {
    baseNetworkInterfacesType,
    interfaceSettingsType,
    networkInterfaceDefinitionType,
} from '@/lib/models/autogenerated/system_models';
import {
    asyncExponentialBackoffRetry,
    fetchFromBackendApi,
} from '@/lib/utils/timeoutFetch';
import { logMessage } from '@/lib/utils/utilities';

enum CONNECTION_STATE {
    INITIALIZING,
    DISCONNECTED,
    CONNECTING,
    CONNECTED,
}

enum WIFI_NEW_CONNECTION_STATE {
    IDLE,
    SCANNING,
    SCAN_COMPLETE,
    AWAITING_PASSWORD,
    CONNECTING,
    CONNECTION_SUCCESSFUL,
    CONNECTION_FAILED,
}

// interface InterfaceDefinition {
//     name: string;
//     address?: string;
// }

interface NetworkStats {
    current_ssid?: string | null;
    // ethernet_ip: string | null;
    ethernet_interfaces?: networkInterfaceDefinitionType[];
    wifi_ip?: string | null;
    tunnnel_interfaces?: networkInterfaceDefinitionType[];
    error_message?: string | null;
}

const TextBlock = (props: { children: ReactNode; className?: string }) => {
    return (
        <p className={`text-center text-r2-white font-bold ${props.className}`}>
            {props.children}
        </p>
    );
};

const ErrorDialog = (props: {
    error_message: string;
    set_network_stats: Dispatch<SetStateAction<NetworkStats>>;
}) => {
    return (
        <div className="grid grid-rows-3 grid-cols-1 bg-r2-red-300 border">
            <TextBlock>ERROR</TextBlock>
            <TextBlock>{`${props.error_message}`}</TextBlock>
            <R2Button
                text="Close"
                onClick={() => {
                    props.set_network_stats((stats) => ({
                        ...stats,
                        error_message: null,
                    }));
                }}
            />
        </div>
    );
};

const NetworkSelectionContainer = (props: {
    ssids: string[];
    set_ssids: React.Dispatch<React.SetStateAction<string[]>>;
    current_connection_state: CONNECTION_STATE;
    set_current_connection_state: React.Dispatch<
        React.SetStateAction<CONNECTION_STATE>
    >;
    new_connection_state: WIFI_NEW_CONNECTION_STATE;
    set_new_connection_state: React.Dispatch<
        React.SetStateAction<WIFI_NEW_CONNECTION_STATE>
    >;
    network_stats: NetworkStats;
    set_network_stats: Dispatch<SetStateAction<NetworkStats>>;
}) => {
    const [selectedWifiNetwork, setSelectedWifiNetwork] = useState<string>();
    const [wifiPassword, setWifiPassword] = useState<string>();

    const { showAlert } = useAlert();

    const scanSSIDs = async () => {
        props.set_new_connection_state(WIFI_NEW_CONNECTION_STATE.SCANNING);
        fetchFromBackendApi<string[]>(
            '/api/backend/system/ssids',
            'GET',
            undefined,
            undefined,
            25000
        )
            .then((ssids) => {
                props.set_ssids(ssids);
                props.set_new_connection_state(
                    WIFI_NEW_CONNECTION_STATE.SCAN_COMPLETE
                );
                setSelectedWifiNetwork(ssids[0]);
                logMessage(`Received SSIDs: ${ssids}`, 'info');
            })
            .catch((e) => {
                props.set_new_connection_state(
                    WIFI_NEW_CONNECTION_STATE.SCAN_COMPLETE
                );

                const message = `Error scanning Wi-Fi networks: ${e}`;

                props.set_network_stats((stats) => ({
                    ...stats,
                    error_message: message,
                }));

                logMessage(message, 'error');
                showAlert(message, 'error');
            });
    };

    const connect_wifi_network = async () => {
        props.set_network_stats((stats) => ({
            ...stats,
            wifi_ip: null,
            current_ssid: null,
        }));
        props.set_new_connection_state(WIFI_NEW_CONNECTION_STATE.CONNECTING);

        await fetchFromBackendApi<null>(
            `/api/backend/system/connect_wifi?ssid=${selectedWifiNetwork}&password=${wifiPassword}`,
            'POST',
            undefined,
            undefined,
            25000
        )
            .then(() => {
                const message = `Connected to Wi-Fi network ${selectedWifiNetwork}`;

                props.set_new_connection_state(
                    WIFI_NEW_CONNECTION_STATE.CONNECTION_SUCCESSFUL
                );
                props.set_current_connection_state(
                    CONNECTION_STATE.INITIALIZING
                );

                logMessage(message, 'success');
                showAlert(message, 'success');
            })
            .catch((e) => {
                const message = `Error connecting to Wi-Fi network ${selectedWifiNetwork}: ${e}`;
                logMessage(message, 'error');
                showAlert(message, 'error');
                props.set_network_stats((stats) => ({
                    ...stats,
                    error_message: `Error connecting to Wi-Fi network: ${e}`,
                }));
                props.set_new_connection_state(
                    WIFI_NEW_CONNECTION_STATE.CONNECTION_FAILED
                );
            });
    };

    const connection_state_handler = () => {
        switch (props.new_connection_state) {
            case WIFI_NEW_CONNECTION_STATE.SCANNING: {
                return <LoadingIndicator text={'Scanning Wi-Fi'} />;
            }
            case WIFI_NEW_CONNECTION_STATE.AWAITING_PASSWORD: {
                return (
                    <div className="grid grid-cols-2 gap-x-5">
                        <div className="flex flex-col">
                            <TextBlock>Password</TextBlock>
                            <input
                                className="text-center"
                                onChange={(e) =>
                                    setWifiPassword(e.target.value)
                                }
                                type="password"
                            />
                        </div>
                        <R2Button
                            text="Connect"
                            onClick={() => connect_wifi_network()}
                        />
                    </div>
                );
            }
            case WIFI_NEW_CONNECTION_STATE.CONNECTING: {
                return <LoadingIndicator text={'Connecting Wi-Fi'} />;
            }
            case WIFI_NEW_CONNECTION_STATE.CONNECTION_FAILED: {
                return (
                    <div className="flex flex-row justify-between items-center">
                        <TextBlock>{`Connection to ${selectedWifiNetwork} Failed`}</TextBlock>
                        <R2Button
                            text="Reset"
                            className="w-[20%]"
                            onClick={() =>
                                props.set_new_connection_state(
                                    WIFI_NEW_CONNECTION_STATE.IDLE
                                )
                            }
                        />
                    </div>
                );
            }
            case WIFI_NEW_CONNECTION_STATE.SCAN_COMPLETE:
            case WIFI_NEW_CONNECTION_STATE.CONNECTION_SUCCESSFUL:
            case WIFI_NEW_CONNECTION_STATE.IDLE: {
                if (props.ssids.length > 0) {
                    return (
                        <div className="grid grid-cols-2 gap-x-5">
                            <div className="flex flex-col">
                                <TextBlock>Available Networks</TextBlock>
                                <select
                                    className="text-center"
                                    onChange={(e) =>
                                        setSelectedWifiNetwork(e.target.value)
                                    }
                                >
                                    {props.ssids.map((ssid) => (
                                        <option key={ssid}>{ssid}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="flex flex-col">
                                <R2Button
                                    text="Connect"
                                    onClick={() =>
                                        props.set_new_connection_state(
                                            WIFI_NEW_CONNECTION_STATE.AWAITING_PASSWORD
                                        )
                                    }
                                />
                                <R2Button
                                    text="Rescan"
                                    onClick={() => {
                                        props.set_ssids([]);
                                        props.set_new_connection_state(
                                            WIFI_NEW_CONNECTION_STATE.SCANNING
                                        );
                                        scanSSIDs();
                                    }}
                                />
                            </div>
                        </div>
                    );
                } else {
                    return (
                        <div className="flex flex-row w-full justify-around">
                            <TextBlock>No Known Wireless Networks</TextBlock>
                            <R2Button
                                text="Scan SSIDs"
                                onClick={() => {
                                    props.set_ssids([]);
                                    scanSSIDs();
                                }}
                            />
                        </div>
                    );
                }
            }
        }
    };

    return (
        <div className="flex flex-col h-[20%] w-full justify-center">
            {/* <ErrorDialog error_message={'test message\ntest'} /> */}
            {props.network_stats?.error_message ? (
                <ErrorDialog
                    error_message={props.network_stats.error_message}
                    set_network_stats={props.set_network_stats}
                />
            ) : (
                connection_state_handler()
            )}
        </div>
    );
};

export const SubTile = (props: {
    header: string;
    children: ReactNode;
    className?: string;
}) => [
    <div className="border min-h-[40%] w-[50%] flex flex-col rounded-xl px-2 pb-2 bg-r2-dark-background-400">
        <TextBlock className="py-2">{props.header}</TextBlock>
        <div className="bg-r2-dark-background-300 rounded-xl grow">
            {props.children}
        </div>
    </div>,
];

// networkInterfaceModal = (
//     isOpen: boolean;
//     onClose: () => void;
//     // onSelectNode: (node: opcDataPointType) => void;
//     // endpoint: string;
// )

interface NetworkInterfaceSettingsModalProps {
    isOpen: boolean;
    onClose: () => void;
    interface_definition: networkInterfaceDefinitionType;
    // onSelectNode: (node: opcDataPointType) => void;
    // endpoint: string;
}

const NetworkInterfaceSettingsModal: React.FC<
    NetworkInterfaceSettingsModalProps
> = ({ isOpen, onClose, interface_definition }) => {
    if (!interface_definition) return <></>;

    const [formData, setFormData] = useState<interfaceSettingsType>({
        interface_name: interface_definition.name,
        ipv4_address: interface_definition.address,
        subnet_mask: interface_definition.subnet_mask,
        autoconnect: true,
        method: 'auto',
    });

    const [isApplying, setIsApplying] = useState(false);
    const { showAlert } = useAlert();

    const postSettings = async (settings: interfaceSettingsType) => {
        setIsApplying(true);
        // const settings: interfaceSettingsType = {
        //     interface_name: 'usb0',
        //     ipv4_address: '192.168.5.5',
        //     method: 'auto',
        //     subnet_mask: '255.255.255.0',
        //     autoconnect: true,
        // };
        await fetchFromBackendApi<null>(
            '/api/backend/system/set_interface_settings',
            'POST',
            settings
        )
            .then(() => {
                showAlert(
                    `Applied configuration to adapter ${formData.interface_name}`,
                    'success'
                );
            })
            .catch((e) => {
                showAlert(
                    `Error applying settings for adapter ${formData.interface_name}: ${e}`,
                    'error'
                );
            })
            .finally(() => setIsApplying(false));
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData((prev) => ({ ...prev, [name]: value }));
    };

    const isAutoConfiguration = () =>
        formData.method === 'auto' ? true : false;

    return (
        <Modal
            isOpen={isOpen}
            modalTitle={`${interface_definition.name} Interface Configuration`}
            onClose={onClose}
        >
            <form
                onSubmit={(e) => {
                    e.preventDefault();
                    // handleSave();
                    postSettings(formData);
                }}
                className="flex flex-col"
            >
                <div className="mb-4 flex flex-row justify-between">
                    <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                        Method:
                    </label>
                    {/* <input
                        type="checkbox"
                        name="address"
                        value={formData.name}
                        onChange={handleInputChange}
                        className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    /> */}
                    <div className="flex flex-row space-x-2">
                        <span>MANUAL</span>
                        <SliderToggle
                            // <button
                            onClick={() =>
                                setFormData((data) => ({
                                    ...data,
                                    method:
                                        data.method === 'manual'
                                            ? 'auto'
                                            : 'manual',
                                }))
                            }
                            isActive={isAutoConfiguration()}
                        />

                        <span>AUTO</span>
                    </div>
                </div>
                {!isAutoConfiguration() ? (
                    <>
                        <div className="mb-4">
                            <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                                IP Address:
                            </label>
                            <input
                                type="text"
                                name="ipv4_address"
                                value={formData.ipv4_address}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                                Subnet Mask:
                            </label>
                            <input
                                type="text"
                                name="subnet_mask"
                                value={formData.subnet_mask}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                                Gateway (Optional):
                            </label>
                            <input
                                type="text"
                                name="gateway"
                                value={formData.gateway}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4">
                            <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                                DNS (Optional):
                            </label>
                            <input
                                type="text"
                                name="dns"
                                value={formData.dns}
                                onChange={handleInputChange}
                                className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                            />
                        </div>
                        <div className="mb-4 flex flex-row justify-between">
                            <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                                Autoconnect:
                            </label>
                            <SliderToggle
                                isActive={formData.autoconnect}
                                onClick={() =>
                                    setFormData((data) => ({
                                        ...data,
                                        autoconnect: !data.autoconnect,
                                    }))
                                }
                            />
                            {/* <input
                        type="text"
                        name="dns"
                        value={formData.dns}
                        onChange={handleInputChange}
                        className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    /> */}
                        </div>
                    </>
                ) : (
                    <></>
                )}
                {/* <div className="mb-4">
                    <label className="block text-r2-dark-modal-subtext font-semibold mb-1">
                        Module Type:
                    </label>
                    <select
                        value={formData.type.name}
                        onChange={handleTypeChange}
                        className="w-full p-2 rounded-md bg-gray-100 text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                        {ioModuleTypes.map((type) => (
                            <option key={type.name} value={type.name}>
                                {type.name}
                            </option>
                        ))}
                    </select>
                </div>
                <h4 className="text-lg font-bold text-r2-dark-modal-subtext-header mt-6 mb-2">
                    I/O Points
                </h4> */}
                {/* <div className="space-y-2 flex-grow overflow-y-scroll">
                    {formData.points.map((point) => (
                        <IOPointComponent
                            key={point.id}
                            point={point}
                            onUpdateValue={handleUpdatePointValue}
                            // onUpdateValue={() => {}}
                        />
                    ))}
                </div> */}
                <div className="flex justify-end mt-6">
                    <LoadingButton
                        type="submit"
                        buttonText="Apply"
                        isLoading={isApplying}
                    />
                    {/* <button
                        type="submit"
                        className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-bold"
                    >
                        Apply
                    </button> */}
                </div>
            </form>
        </Modal>
    );
};

export default function AdministrationPanel(props: {
    id: string;
    className?: string;
    fill_tile_callback?: Dispatch<SetStateAction<string>>;
    force_expanded?: boolean;
}) {
    const { dashboardContext, setDashboardContext } =
        useContext(DashboardContext);

    const [SSIDs, setSSIDs] = useState<Array<string>>([]);
    const [networkStats, setNetworkStats] = useState<NetworkStats>({});
    const [
        interfaceConfigurationModalOpen,
        setInterfaceConfigurationModalOpen,
    ] = useState(false);
    const [selectedNetworkInterface, setSelectedNetworkInterface] =
        useState<networkInterfaceDefinitionType | null>();

    const [wifiConnectionState, setWifiConnectionState] =
        useState<CONNECTION_STATE>(CONNECTION_STATE.INITIALIZING);

    const [newWifiConnectionState, setNewWifiConnectionState] =
        useState<WIFI_NEW_CONNECTION_STATE>(WIFI_NEW_CONNECTION_STATE.IDLE);

    useEffect(() => {
        const get_interfaces = async () => {
            await asyncExponentialBackoffRetry(() =>
                fetchFromBackendApi<baseNetworkInterfacesType>(
                    `/api/backend/system/interfaces`
                ).then((interfaces) => {
                    const wifi_ip = interfaces.interfaces.find(
                        (i) => i.type === 'wifi' && i.address
                    )?.address;

                    const ssid = interfaces.interfaces.find(
                        (i) => i.ssid
                    )?.ssid;
                    ssid
                        ? setWifiConnectionState(CONNECTION_STATE.CONNECTED)
                        : setWifiConnectionState(CONNECTION_STATE.DISCONNECTED);

                    const ethernet_interfaces = interfaces.interfaces.filter(
                        (i) => i.type === 'ethernet'
                    );
                    const tunnnel_interfaces = interfaces.interfaces.filter(
                        (i) => i.type === 'tun'
                    );
                    // .map((i) => ({
                    //     name: i.name,
                    //     address: i.address,
                    // }));

                    // const tunnnel_interfaces = interfaces.interfaces
                    // .filter((i) => i.type === 'tun')
                    // .map((i) => ({
                    //     name: i.name,
                    //     address: i.address,
                    // }));

                    setNetworkStats((stats) => ({
                        ...stats,
                        ethernet_interfaces: ethernet_interfaces,
                        // ethernet_interfaces: interfaces.interfaces
                        //     .filter((i) => i.type === 'ethernet')
                        //     .map((i) => ({
                        //         name: i.name,
                        //         address: i.address ?? '',
                        //     })),
                        current_ssid: ssid, //interfaces.interfaces.find((i) => i.ssid)?.ssid,
                        wifi_ip: wifi_ip, //interfaces.interfaces.find((i) => i.type === 'wifi' && i.address)?.address
                        tunnnel_interfaces: tunnnel_interfaces,
                    }));
                })
            );
        };

        get_interfaces();
        // }, [JSON.stringify(wifiConnectionState === CONNECTION_STATE.INITIALIZING)]);
    }, [wifiConnectionState === CONNECTION_STATE.INITIALIZING]);

    // const set_interface_settings = async () => {
    //     const settings: interfaceSettingsType = {
    //         interface_name: 'usb0',
    //         ipv4_address: '192.168.5.5',
    //         method: 'manual',
    //         subnet_mask: '255.255.255.0',
    //         autoconnect: true,
    //     };
    //     fetchFromBackendApi<null>(
    //         '/api/backend/system/set_interface_settings',
    //         'POST',
    //         settings
    //     );
    // };

    return (
        <SimplifiedDashboardHeaderContainer
            title="Administration"
            icon_path={'/icons/user.svg'}
            className={props.className || ''}
        >
            <SubTile header="Select Wireless Network">
                {!(wifiConnectionState === CONNECTION_STATE.INITIALIZING) ? (
                    <>
                        <div className="flex flex-col h-full relative px-2 py-2">
                            <div className="grid grid-cols-[30%_70%] grid-rows-auto gap-x-2 gap-y-2 border rounded-xl items-center">
                                <TextBlock>Current SSID</TextBlock>
                                <TextBlock>
                                    {networkStats.current_ssid ??
                                        'No Wi-Fi Connection'}
                                </TextBlock>
                                <TextBlock>Wi-Fi IP</TextBlock>
                                <TextBlock>
                                    {networkStats.wifi_ip ??
                                        'No Wi-Fi IP Assigned'}
                                </TextBlock>
                                <TextBlock>Ethernet IPs</TextBlock>
                                <TextBlock>
                                    <div className="flex flex-col w-full">
                                        {networkStats.ethernet_interfaces ? (
                                            networkStats.ethernet_interfaces
                                                .filter(
                                                    (i) => i.address || true
                                                )
                                                .map((i) => (
                                                    <div className="grid grid-cols-3 items-center justify-center space-y-2">
                                                        <span>{i.name}</span>
                                                        <span>{i.address}</span>
                                                        <button
                                                            className="px-1 py-1 rounded-lg bg-blue-600 text-white font-semibold hover:bg-blue-700 transition-colors"
                                                            onClick={
                                                                // set_interface_settings
                                                                () => {
                                                                    setSelectedNetworkInterface(
                                                                        i
                                                                    );
                                                                    setInterfaceConfigurationModalOpen(
                                                                        true
                                                                    );
                                                                }
                                                            }
                                                        >
                                                            Set
                                                        </button>
                                                    </div>
                                                ))
                                        ) : (
                                            <span>
                                                No Known Ethernet Interfaces
                                            </span>
                                        )}
                                    </div>
                                </TextBlock>
                                <TextBlock>Tunnel IPs</TextBlock>
                                <TextBlock>
                                    <div className="flex flex-col w-full">
                                        {networkStats.tunnnel_interfaces ? (
                                            networkStats.tunnnel_interfaces
                                                .filter(
                                                    (i) => i.address || true
                                                )
                                                .map((i) => (
                                                    <div className="grid grid-cols-2 items-center justify-center">
                                                        <span>{i.name}</span>
                                                        <span>{i.address}</span>
                                                    </div>
                                                ))
                                        ) : (
                                            <span>No Known Tunnels</span>
                                        )}
                                    </div>
                                </TextBlock>
                            </div>
                            <div className="flex flex-col grow items-center justify-center">
                                <NetworkSelectionContainer
                                    ssids={SSIDs}
                                    set_ssids={setSSIDs}
                                    current_connection_state={
                                        wifiConnectionState
                                    }
                                    set_current_connection_state={
                                        setWifiConnectionState
                                    }
                                    new_connection_state={
                                        newWifiConnectionState
                                    }
                                    set_new_connection_state={
                                        setNewWifiConnectionState
                                    }
                                    network_stats={networkStats}
                                    set_network_stats={setNetworkStats}
                                />
                            </div>
                        </div>
                        <NetworkInterfaceSettingsModal
                            isOpen={interfaceConfigurationModalOpen}
                            // modalTitle={`${selectedNetworkInterface} Interface Configuration`}
                            interface_definition={selectedNetworkInterface}
                            onClose={() =>
                                setInterfaceConfigurationModalOpen(false)
                            }
                        />
                        {/* <Modal
                        isOpen={interfaceConfigurationModalOpen}
                        modalTitle={`${selectedNetworkInterface} Interface Configuration`}
                        onClose={() => setInterfaceConfigurationModalOpen(false)}
                    /> */}
                    </>
                ) : (
                    <LoadingIndicator />
                )}
            </SubTile>
            {/* </DashboardHeaderContainer> */}
        </SimplifiedDashboardHeaderContainer>
    );
}
