// This file is auto-generated by tools/generate_zod_models.py
// Do not edit this file manually.

import { z } from 'zod';

// Zod schemas for the database tables
// These schemas define the data structure and validation rules.

export const sensorDataSchema = z.object({
time: z.string().datetime(),
deviceId: z.string(),
temperature: z.number().optional(),
humidity: z.number().optional(),
});

export const logsSchema = z.object({
time: z.string().datetime(),
deviceId: z.string(),
messageLevel: z.string().optional(),
message: z.string().optional(),
});

export const projectMetricsSchema = z.object({
timestamp: z.string().datetime(),
projectName: z.string(),
value: z.number().optional(),
status: z.string().optional(),
});

export const userActivitySchema = z.object({
activityTime: z.string().datetime(),
userId: z.string(),
action: z.string().optional(),
durationMs: z.number().optional(),
});

export const frontendConfigsSchema = z.object({
clientId: z.string(),
configData: z.record(z.unknown()).optional(),
lastUpdated: z.string().datetime(),
});

export const usersSchema = z.object({
userId: z.any(),
username: z.string(),
hashedPassword: z.string(),
createdAt: z.string().datetime().default(new Date().toISOString()),
});

export const realtimeSysStateSchema = z.object({
stamp: z.string().datetime(),
state: z.number().optional(),
});

export const analogInConfigSchema = z.object({
stamp: z.string().datetime(),
channel: z.number(),
label: z.string().optional(),
unit: z.string().optional(),
minElectricalValue: z.number().optional(),
maxElectricalValue: z.number().optional(),
minMeasurementValue: z.number().optional(),
maxMeasurementValue: z.number().optional(),
transferFunctionType: z.number().optional(),
hardwareConfigConfigured: z.boolean().optional(),
hardwareConfigEnabled: z.boolean().optional(),
hardwareConfigChannelType: z.number().optional(),
});

export const analogInDataSchema = z.object({
stamp: z.string().datetime(),
readChannels: z.array(z.boolean()),
read_channels__0: z.boolean().optional(),
read_channels__1: z.boolean().optional(),
read_channels__2: z.boolean().optional(),
read_channels__3: z.boolean().optional(),
read_channels__4: z.boolean().optional(),
read_channels__5: z.boolean().optional(),
read_channels__6: z.boolean().optional(),
read_channels__7: z.boolean().optional(),
values: z.array(z.number()),
values__0: z.number().optional(),
values__1: z.number().optional(),
values__2: z.number().optional(),
values__3: z.number().optional(),
values__4: z.number().optional(),
values__5: z.number().optional(),
values__6: z.number().optional(),
values__7: z.number().optional(),
types: z.array(z.number()),
types__0: z.number().optional(),
types__1: z.number().optional(),
types__2: z.number().optional(),
types__3: z.number().optional(),
types__4: z.number().optional(),
types__5: z.number().optional(),
types__6: z.number().optional(),
types__7: z.number().optional(),
});

export const analogOutConfigSchema = z.object({
stamp: z.string().datetime(),
channel: z.number(),
label: z.string().optional(),
unit: z.string().optional(),
minElectricalValue: z.number().optional(),
maxElectricalValue: z.number().optional(),
minMeasurementValue: z.number().optional(),
maxMeasurementValue: z.number().optional(),
transferFunctionType: z.number().optional(),
hardwareConfigConfigured: z.boolean().optional(),
hardwareConfigEnabled: z.boolean().optional(),
hardwareConfigPwmPeriodMs: z.number().optional(),
hardwareConfigInitialValueVolts: z.number().optional(),
hardwareConfigEstopConfigured: z.boolean().optional(),
hardwareConfigEstopValueVolts: z.number().optional(),
});

export const digitalInConfigSchema = z.object({
stamp: z.string().datetime(),
channel: z.number(),
label: z.string().optional(),
hardwareConfigConfigured: z.boolean().optional(),
hardwareConfigEnabled: z.boolean().optional(),
});

export const digitalInDataSchema = z.object({
stamp: z.string().datetime(),
readChannels: z.array(z.boolean()),
read_channels__0: z.boolean().optional(),
read_channels__1: z.boolean().optional(),
read_channels__2: z.boolean().optional(),
read_channels__3: z.boolean().optional(),
read_channels__4: z.boolean().optional(),
read_channels__5: z.boolean().optional(),
read_channels__6: z.boolean().optional(),
read_channels__7: z.boolean().optional(),
values: z.array(z.boolean()),
values__0: z.boolean().optional(),
values__1: z.boolean().optional(),
values__2: z.boolean().optional(),
values__3: z.boolean().optional(),
values__4: z.boolean().optional(),
values__5: z.boolean().optional(),
values__6: z.boolean().optional(),
values__7: z.boolean().optional(),
});

export const digitalOutConfigSchema = z.object({
stamp: z.string().datetime(),
channel: z.number(),
label: z.string().optional(),
hardwareConfigConfigured: z.boolean().optional(),
hardwareConfigEnabled: z.boolean().optional(),
hardwareConfigInitialValue: z.boolean().optional(),
hardwareConfigEstopConfigured: z.boolean().optional(),
hardwareConfigEstopValue: z.boolean().optional(),
});

export const digitalOutDataSchema = z.object({
stamp: z.string().datetime(),
writeChannels: z.array(z.boolean()),
write_channels__0: z.boolean().optional(),
write_channels__1: z.boolean().optional(),
write_channels__2: z.boolean().optional(),
write_channels__3: z.boolean().optional(),
write_channels__4: z.boolean().optional(),
write_channels__5: z.boolean().optional(),
write_channels__6: z.boolean().optional(),
write_channels__7: z.boolean().optional(),
values: z.array(z.boolean()),
values__0: z.boolean().optional(),
values__1: z.boolean().optional(),
values__2: z.boolean().optional(),
values__3: z.boolean().optional(),
values__4: z.boolean().optional(),
values__5: z.boolean().optional(),
values__6: z.boolean().optional(),
values__7: z.boolean().optional(),
});

export const axisEstimatesSchema = z.object({
stamp: z.string().datetime(),
axisIndex: z.number(),
position: z.number().optional(),
velocity: z.number().optional(),
});


// TypeScript interfaces derived from the Zod schemas
// These interfaces provide type safety for your data.

export interface ISensorData {
time: string;
deviceId: string;
temperature: number | undefined;
humidity: number | undefined;
}

export interface ILogs {
time: string;
deviceId: string;
messageLevel: string | undefined;
message: string | undefined;
}

export interface IProjectMetrics {
timestamp: string;
projectName: string;
value: number | undefined;
status: string | undefined;
}

export interface IUserActivity {
activityTime: string;
userId: string;
action: string | undefined;
durationMs: number | undefined;
}

export interface IFrontendConfigs {
clientId: string;
configData: Record<string, unknown> | undefined;
lastUpdated: string;
}

export interface IUsers {
userId: any;
username: string;
hashedPassword: string;
createdAt: string;
}

export interface IRealtimeSysState {
stamp: string;
state: number | undefined;
}

export interface IAnalogInConfig {
stamp: string;
channel: number;
label: string | undefined;
unit: string | undefined;
minElectricalValue: number | undefined;
maxElectricalValue: number | undefined;
minMeasurementValue: number | undefined;
maxMeasurementValue: number | undefined;
transferFunctionType: number | undefined;
hardwareConfigConfigured: boolean | undefined;
hardwareConfigEnabled: boolean | undefined;
hardwareConfigChannelType: number | undefined;
}

export interface IAnalogInData {
stamp: string;
readChannels: boolean[];
read_channels__0: boolean | undefined;
read_channels__1: boolean | undefined;
read_channels__2: boolean | undefined;
read_channels__3: boolean | undefined;
read_channels__4: boolean | undefined;
read_channels__5: boolean | undefined;
read_channels__6: boolean | undefined;
read_channels__7: boolean | undefined;
values: number[];
values__0: number | undefined;
values__1: number | undefined;
values__2: number | undefined;
values__3: number | undefined;
values__4: number | undefined;
values__5: number | undefined;
values__6: number | undefined;
values__7: number | undefined;
types: number[];
types__0: number | undefined;
types__1: number | undefined;
types__2: number | undefined;
types__3: number | undefined;
types__4: number | undefined;
types__5: number | undefined;
types__6: number | undefined;
types__7: number | undefined;
}

export interface IAnalogOutConfig {
stamp: string;
channel: number;
label: string | undefined;
unit: string | undefined;
minElectricalValue: number | undefined;
maxElectricalValue: number | undefined;
minMeasurementValue: number | undefined;
maxMeasurementValue: number | undefined;
transferFunctionType: number | undefined;
hardwareConfigConfigured: boolean | undefined;
hardwareConfigEnabled: boolean | undefined;
hardwareConfigPwmPeriodMs: number | undefined;
hardwareConfigInitialValueVolts: number | undefined;
hardwareConfigEstopConfigured: boolean | undefined;
hardwareConfigEstopValueVolts: number | undefined;
}

export interface IDigitalInConfig {
stamp: string;
channel: number;
label: string | undefined;
hardwareConfigConfigured: boolean | undefined;
hardwareConfigEnabled: boolean | undefined;
}

export interface IDigitalInData {
stamp: string;
readChannels: boolean[];
read_channels__0: boolean | undefined;
read_channels__1: boolean | undefined;
read_channels__2: boolean | undefined;
read_channels__3: boolean | undefined;
read_channels__4: boolean | undefined;
read_channels__5: boolean | undefined;
read_channels__6: boolean | undefined;
read_channels__7: boolean | undefined;
values: boolean[];
values__0: boolean | undefined;
values__1: boolean | undefined;
values__2: boolean | undefined;
values__3: boolean | undefined;
values__4: boolean | undefined;
values__5: boolean | undefined;
values__6: boolean | undefined;
values__7: boolean | undefined;
}

export interface IDigitalOutConfig {
stamp: string;
channel: number;
label: string | undefined;
hardwareConfigConfigured: boolean | undefined;
hardwareConfigEnabled: boolean | undefined;
hardwareConfigInitialValue: boolean | undefined;
hardwareConfigEstopConfigured: boolean | undefined;
hardwareConfigEstopValue: boolean | undefined;
}

export interface IDigitalOutData {
stamp: string;
writeChannels: boolean[];
write_channels__0: boolean | undefined;
write_channels__1: boolean | undefined;
write_channels__2: boolean | undefined;
write_channels__3: boolean | undefined;
write_channels__4: boolean | undefined;
write_channels__5: boolean | undefined;
write_channels__6: boolean | undefined;
write_channels__7: boolean | undefined;
values: boolean[];
values__0: boolean | undefined;
values__1: boolean | undefined;
values__2: boolean | undefined;
values__3: boolean | undefined;
values__4: boolean | undefined;
values__5: boolean | undefined;
values__6: boolean | undefined;
values__7: boolean | undefined;
}

export interface IAxisEstimates {
stamp: string;
axisIndex: number;
position: number | undefined;
velocity: number | undefined;
}
